import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {readContext,digest} from '../../../scripts/research-common.mjs';
const b='research/completion-01/events',old='research/bulk-02/events',load=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const raw=load(old+'/cow-events-extracted.json'),prior=load(old+'/independent-review.json'),original=load(old+'/independent-original-csv-rows.json'),queue=load('research/completion-01/reports/priority-queue.json'),c=readContext();const excluded=new Set(prior.rows.filter(r=>r.sourceIdentityApproval).map(r=>r.eventId));
const proposals=[
 {entityId:'qing-imperial-framework',labels:['China'],codes:['710'],reason:'Literal China710 before1912 is proposed only against the existing Qing imperial framework, not a modern Chinese state or Taiwan administration.'},
 {entityId:'china-republic-nationalist-framework',labels:['China'],codes:['710'],until:'1949-10-01',reason:'Literal China710 in1945 is proposed against existing Republic of China Nationalist framework. Stop before PRC proclamation; no automatic transfer of earlier Republic events to PRC.'},
 {entityId:'china-republic-nationalist-framework',labels:['Taiwan','Taiwan (ROC)'],codes:['713'],from:'1949-10-01',reason:'Source participant713 Taiwan/ROC is proposed as Nationalist Republic of China government only; not independent evidence of island sovereignty or modern nationality. Existing1960raw identity is entity-taiwan.'},
 {entityId:'china-prc-framework',labels:['China','China (PRC)'],codes:['710'],reason:'Literal China710 after existing1949-10-01 PRC framework start, and explicit China(PRC), proposed as source state-participant bridge. Coexisting ROC framework is not merged.'},
 {entityId:'estonian-constituent-framework',labels:['Estonia'],codes:['366'],reason:'Literal Estonia participant intersects existing Republic constituent framework; pre-July1919 combat starts cannot be borrowed.'},
 {entityId:'lithuanian-constituent-seimas-framework',labels:['Lithuania'],codes:['368'],reason:'Literal Lithuania participant intersects existing constituent-Seimas framework; preserve exact combat dates and parliamentary bounds.'},
 {entityId:'polish-small-constitution-framework',labels:['Poland'],codes:['290'],reason:'Literal Poland participant intersects existing provisional parliamentary framework. Russo-Polish transformation-coded endpoints remain held.'},
 {entityId:'mongolia-peoples-republic-framework',labels:['Mongolia'],codes:['712'],reason:'Literal Mongolia participant is proposed against existing Mongolian Peoples Republic only; do not equate earlier Bogd/occupation frameworks.'},
 {entityId:'saudi-1932-monarchical-core',labels:['Saudi Arabia'],codes:['670'],reason:'Literal Saudi Arabia participant1934 intersects already sourced post1932 monarchic framework; no succession/warwide inference.'},
 {entityId:'b19-south-africa-later-union',labels:['South Africa'],codes:['560'],reason:'Literal South Africa state participant1945 proposed against existing1935–1948 Union framework. Do not attribute Union-wide combat to Natal/colonial subterritories.'}
];
const day=s=>s.length===4?s+'-01-01':s.length===7?s+'-01':s;const max=(...s)=>s.filter(Boolean).map(day).sort().at(-1),min=(...s)=>s.filter(Boolean).map(day).sort()[0];
const contracts=proposals.map((p,n)=>{const e=c.db.entities.find(e=>e.id===p.entityId);assert(e);const name=e.names.find(n=>n.kind==='primary')??e.names[0];let f=e.existence?.validFrom??name.validFrom; // month/year precision remains explicit in originalIdentity; coding window conservative
if(f.length===7){const dt=new Date(f+'-01T00:00:00Z');dt.setUTCMonth(dt.getUTCMonth()+1);f=dt.toISOString().slice(0,10);}if(f.length===4)f=(Number(f)+1)+'-01-01';const from=max(f,p.from),until=min(e.existence?.validUntil??name.validUntil??'1961-01-01',p.until,'1961-01-01');return{...p,id:'completion-cow-alias-'+String(n+1).padStart(2,'0'),from,until,existingIdentity:{name:name.value,existence:e.existence,names:e.names,entityRecordDigest:digest(e),sourceIds:[...new Set([...(e.existence?.sourceIds??[]),...(name.sourceIds??[])])]},disposition:'historical-review-required'};});
const candidates=[],held=[];let comparisons=0;for(const ev of raw.events){if(excluded.has(ev.id))continue;assert.deepEqual(ev.originalRow,original[ev.originalRowNumber-2]);comparisons++;const possible=contracts.filter(mp=>mp.labels.includes(ev.rawParticipant)&&mp.codes.includes(ev.sourceCountryCode));for(const mp of possible){if(!ev.eventDate||ev.eventDate<mp.from||ev.eventDate>=mp.until){held.push({eventId:ev.id,entityId:mp.entityId,reason:'Actual coded event outside bounded existing historical framework; do not transfer across regimes.'});continue;}const slots=queue.filter(q=>q.entityId===mp.entityId&&q.category==='events-context'&&q.status==='missing'&&Number(ev.eventDate.slice(0,4))<=q.snapshotYear&&q.snapshotYear-Number(ev.eventDate.slice(0,4))<=5).map(q=>({snapshotYear:q.snapshotYear,entityId:q.entityId,mapIds:q.mapIds,context:Number(ev.eventDate.slice(0,4))===q.snapshotYear?'event-in-selected-year':'explicitly dated prior-context',actualEventDate:ev.eventDate,ageYears:q.snapshotYear-Number(ev.eventDate.slice(0,4)),status:'missing'}));if(ev.eventPrecision!=='day'||ev.reviewIssues.length){held.push({eventId:ev.id,entityId:mp.entityId,reason:'Inherited source/date/episode review flags',reviewIssues:ev.reviewIssues,potentialMissingSlots:slots});continue;}if(!slots.length){held.push({eventId:ev.id,entityId:mp.entityId,reason:'No currently missing entity/snapshot event slot within five-year explicitly dated past-context policy.'});continue;}
candidates.push({...ev,entityId:mp.entityId,mappingContractId:mp.id,originalEventDigest:digest(ev),originalCsvRowDigest:digest(ev.originalRow),snapshotSlots:slots,sourceIdentityApproval:false,status:'historical-review',qualification:(ev.endpoint==='Start'?'COW-coded participant sustained-combat start, not legal declaration or war-wide beginning. ':'COW-coded participant sustained-combat endpoint, possibly day after last major engagement; not peace treaty or war-wide cessation. ')+ev.qualification});}}
const slots=[...new Set(candidates.flatMap(e=>e.snapshotSlots.map(s=>s.entityId+':'+s.snapshotYear)))].sort();const ranked=contracts.map(mp=>({...mp,candidateEventIds:candidates.filter(e=>e.mappingContractId===mp.id).map(e=>e.id),missingSlots:[...new Set(candidates.filter(e=>e.mappingContractId===mp.id).flatMap(e=>e.snapshotSlots.map(s=>s.entityId+':'+s.snapshotYear)))].sort()})).sort((a,b)=>b.missingSlots.length-a.missingSlots.length||a.entityId.localeCompare(b.entityId));
const bindings=[old+'/cow-events-extracted.json',old+'/independent-review.json',old+'/independent-original-csv-rows.json',old+'/cache/Inter-StateWarData_v4.0.csv',old+'/cache/Inter-StateWars_Codebook.pdf',old+'/cache/codebook-text.txt',old+'/extract-cow.py',old+'/independent-parse.py','research/completion-01/reports/priority-queue.json'].map(path=>({path,sha256:sha(path)}));
const out={schemaVersion:1,sourceBindings:bindings,sourceCatalogue:raw.sources,definitionLocators:raw.definitionLocators,codebookReview:'Cached full four-page codebook read. Exact literal participant combat endpoints retained. Ccode identifies source system member; participant alias is a separate unaccepted historical review contract. No legal declaration/peace/status/control/succession inferred.',policy:'No new downloads. Exclude45 original accepted events. Missing-slot targeting only, actual event date retained, max5calendar-year explicit past context. No framework-crossing carryover. All candidates await independent coordinator historical/source review.',contracts:ranked,candidates,held,namespaceHolds:[{literal:'Yugoslavia',period:'before1918',reason:'Anachronistic literal label requires independent COW345-to-Serbia namespace certification, never infer succession.'},{literal:'Yemen Arab Republic',period:'1934',reason:'Anachronistic source label cannot be automatically normalized to Yahya monarchy; source namespace certification required.'},{literal:'Russia',period:'1918–1920',reason:'Neither SovietUnion1922 nor imperial framework ending1915 may absorb revolutionary Russia combat endpoints.'},{literal:'Ethiopia',period:'1935–1953',reason:'Occupation/restored1945/revised1955 framework gaps do not authorize borrowing earlier combat episodes.'}],summary:{candidateEvents:candidates.length,missingSlots:slots.length,slots,proposedContracts:ranked.length,contractsWithUsefulMissingSlots:ranked.filter(x=>x.missingSlots.length).length,heldMappedRows:held.length,originalCsvRowComparisons:comparisons,priorAcceptedEventsExcluded:excluded.size},productionEdited:false,historicalAcceptance:false};fs.writeFileSync(b+'/candidate-tranche.json',JSON.stringify(out,null,2)+'\n');console.log(out.summary);
