// Independent coordinator review of the frozen worker tranche; no production writes.
import fs from 'node:fs';
import {readJSON,readContext,digest,saveJSON} from '../../../scripts/research-common.mjs';
import {bytesHash} from '../../../scripts/research-bulk.mjs';
const base='research/completion-01/events/',raw=readJSON(base+'candidate-tranche.json'),context=readContext();
for(const b of raw.sourceBindings)if(bytesHash(b.path)!==b.sha256)throw Error('Worker input binding changed: '+b.path);
fs.copyFileSync('research/completion-01/reports/priority-queue.json',base+'priority-input.json');
const original=readJSON('research/bulk-02/events/independent-original-csv-rows.json');
const approvedAliases=new Set(['completion-cow-alias-01','completion-cow-alias-02','completion-cow-alias-03','completion-cow-alias-04','completion-cow-alias-05','completion-cow-alias-06','completion-cow-alias-07','completion-cow-alias-08','completion-cow-alias-09','completion-cow-alias-10']);
const rows=raw.candidates.map(r=>{
 const m=raw.contracts.find(m=>m.id===r.mappingContractId),e=context.db.entities.find(e=>e.id===r.entityId);
 if(!approvedAliases.has(m.id)||digest(e)!==m.existingIdentity.entityRecordDigest||digest(original[r.originalRowNumber-2])!==r.originalCsvRowDigest||r.eventDate<m.from||r.eventDate>=m.until||r.eventPrecision!=='day'||r.reviewIssues.length)throw Error('Unsafe event candidate');
 const o=original[r.originalRowNumber-2],date=[o[r.endpoint+'Year1'],o[r.endpoint+'Month1'],o[r.endpoint+'Day1']].map((n,i)=>String(n).padStart(i?2:4,'0')).join('-');
 if(date!==r.eventDate||String(o.ccode)!==r.sourceCountryCode||o.StateName!==r.rawParticipant)throw Error('Independent literal endpoint check failed');
 return{eventId:r.id,originalEventDigest:digest(r),decision:'source-date-mapping-approved',approvedMappedFields:{entityId:e.id,value:r.value,eventDate:r.eventDate,eventPrecision:'day',locator:r.locator,scope:'Source-coded sustained-combat participation of '+e.names[0].value+'; no polygon-wide authority or sovereignty assertion.',qualification:r.qualification},mapping:{from:m.from,until:m.until,entityRecordDigest:digest(e),reason:m.reason+' Coordinator independently compared original dated sourced identity/existence bounds, literal COW code/name and selected endpoint; no successor or territorial bridge inferred.'}};
});
const review={schemaVersion:1,reviewer:'coordinator-independent-COW-source-and-framework-review',worker:'campaign2_flags',inputCanonicalDigest:digest(raw),bodyReviewed:true,reviewScope:'Original cached four-page codebook read in full; original CSV independently extracted rows compared for all selected endpoints. Codebook defines Ccode as system-member identity and sustained-combat dates. Existing curated names/existence/source references independently inspected for Qing, Nationalist ROC versus PRC, Estonia/Lithuania/Poland constituent frames, Mongolia, Saudi1932 and Union of South Africa. Source-coded participants are not territorial sovereignty. Taiwan713 explicitly labels ROC in selected1958 row; same bounded Nationalist government mapping is used for1955 Taiwan713 with no island-sovereignty conclusion. Start/end are neither declarations nor peace treaties. Transformation, occupation, anachronistic Yugoslavia/Yemen and outside-framework cases remain held.',sourceBindings:raw.sourceBindings.filter(b=>!b.path.endsWith('/priority-queue.json')).concat([{path:base+'priority-input.json',sha256:bytesHash(base+'priority-input.json')}]),parserBindings:[{path:base+'build-tranche.mjs',sha256:bytesHash(base+'build-tranche.mjs')},{path:base+'coordinator-review.mjs',sha256:bytesHash(base+'coordinator-review.mjs')}],rows};
saveJSON(base+'independent-review.json',review);console.log(JSON.stringify({accepted:rows.length,held:raw.held.length,sourceBodiesReused:2,downloadRequests:0}));
