import crypto from 'node:crypto';import fs from 'node:fs';
import {saveJSON,readJSON,digest} from '../../../scripts/research-common.mjs';
const base='research/regional-01/western';
const sources=[
 ['regional01-bde-history','History of the Banco de España','Banco de España','https://www.bde.es/wbe/en/sobre-banco/mision/historia-del-banco/'],
 ['regional01-bdf-history','L’histoire de la Banque de France','Banque de France','https://www.banque-france.fr/fr/banque-de-france/institution-ancree-histoire/histoire-banque-de-france'],
 ['regional01-boe-history','History of the Bank of England','Bank of England','https://www.bankofengland.co.uk/about/history?level=1'],
 ['regional01-boe-convertibility','Exchanging banknotes for gold: historical statutory framework','Bank of England','https://www.bankofengland.co.uk/freedom-of-information/2015/9-april-2015'],
 ['regional01-portugal-bank','History of the Bank of Portugal to 1914','Instituto de Ciências Sociais, Universidade de Lisboa','https://www.ics.ulisboa.pt/en/projeto/history-bank-portugal-1914'],
 ['regional01-lisbon-history','Lisboa: national capital since 1255','Turismo de Portugal','https://www.visitportugal.com/en/NR/exeres/98BE771F-120C-4A83-A18B-DFC8C7907F5B'],
 ['regional01-madrid-history','Historia: Madrid and the royal court','Comunidad de Madrid','https://www.comunidad.madrid/gobierno/historia'],
].map(([id,title,institution,url])=>({id,title,institution,url,accessed:'2026-10-02',kind:'institutional-historical-account',usage:'Factual paraphrases only; no wholesale source republication. Scope qualifications and conservative intervals retained.'}));
const claims=[];
function fact(entityId,category,value,from,until,sourceIndex,locator,note,qualifications=[]){
 const temporal={kind:'interval',from,until,certainty:'exact'},source=sources[sourceIndex];
 claims.push({id:'regional01-western-'+digest({entityId,category,value,temporal}).slice(0,24),entityId,category,value,temporal,
  scope:{id:entityId+'-documented-institutional-scope',description:'Historical institution or capital of the named polity; monetary statements apply only to the territorial reach explicitly stated, not a polygon-wide statistical measurement.',relationship:'same'},
  sourceIds:[source.id],evidence:[{sourceId:source.id,locator,note,precision:'year',temporal,interpretation:'direct'}],status:'supported',risks:[],qualifications,
  origin:{kind:'new-research',reference:source.url,sourceIdentifier:locator}});
}
// Conservative year-bounded periods; transition years omitted unless separately evidenced.
fact('spain-political-frameworks','economy','The Banco Nacional de San Carlos provided state finance and credit for trade and industry.', '1800','1828',0,'1782 and 1829 sections','Founded1782; objectives include state finance and trade/industry credit; successor Banco Español de San Fernando established1829. No assumption of a modern central bank.');
fact('spain-political-frameworks','economy','The Banco de España held the banknote-issue monopoly for mainland Spain and its islands; Spain did not adopt exclusive gold convertibility.', '1875','1920',0,'1874 and 1921 sections','1874 monopoly explicitly mainland Spain and islands; source explicitly says Spain did not adopt the gold standard. Cambó law changed central banking framework1921.', ['Monetary scope is mainland Spain and islands; no claim of identical colonial arrangements.']);
fact('spain-political-frameworks','economy','Civil-war Spain had separate Republican and Nationalist issuing institutions and pesetas, each recognised in its own area.', '1937','1938',0,'1936–39 section','Source explicitly distinguishes the two zones and issuing institutions; no flattening into a single nationwide monetary authority.', ['Competing territorial monetary systems; this does not assign one issuer to the entire atlas polygon.']);
fact('spain-political-frameworks','capital','Madrid', '1814','1935',6,'Historical royal court and subsequent national history','Madrid became the capital with the royal court in1561. Period is conservatively restricted to restored post-Peninsular-War court through pre-Civil-War Spain; no wartime or exile capital inferred.', ['Civil-war and wartime seats excluded from this interval.']);
fact('spain-political-frameworks','capital','Madrid', '1940','1960',6,'Historical capital and present continuity','Madrid historical capital with national institutional continuity; post-Civil-War interval excludes1939 transition.', ['Conservative postwar interval; no retrospective claim about the competing governments of1938.']);
fact('portugal-political-frameworks','capital','Lisbon', '1822','1960',5,'City history: capital since1255','Official tourism history establishes Lisbon national capital since1255; this accepted window excludes the Portuguese court’s Brazilian residence and1821 return transition.', ['No claim about the royal court or seat of government in Brazil before1822.']);
fact('portugal-political-frameworks','economy','The Banco de Portugal operated in a gold-standard financial system, with expanding commercial activity and increasing autonomy.', '1860','1890',4,'Principal historical phases','University institutional history distinguishes recovery at end1850s, subsequent expansion, gold-standard monetary intervention, ending with1891 crisis.');
fact('portugal-political-frameworks','economy','After the1891 financial crisis, Portugal left the gold standard and unredeemable banknotes circulated; the Banco de Portugal became more subject to state objectives.', '1892','1913',4,'Third phase and project results','Source explicitly identifies1891 departure from gold, unredeemable notes, state subjection, and scope endingFirstWorldWar.');
fact('france-political-frameworks','economy','The Banque de France held the privilege of issuing banknotes in Paris.', '1804','1847',1,'1800–1806 and1806–1870 sections','Privilege forParis granted1803; national monopoly obtained1848. Paris privilege is not nationwide monopoly.');
fact('france-political-frameworks','economy','The Banque de France held the nationwide banknote-issue monopoly after absorbing departmental issuing banks as branches.', '1849','1935',1,'1848 monopoly;1936 governance reform','Nationwide monopoly granted1848; institutional governance subsequently changed1936. No GDP or statistical territorial equivalence inferred.');
fact('france-political-frameworks','economy','The1936 reform broadened Banque de France shareholder participation and placed most General Council appointments with public authorities; legal nationalisation followed in December1945.', '1937','1944',1,'1936–1945 section','Source distinguishes1936 de facto governance change from de jure1945 nationalisation. Claim does not present legal nationalisation as already complete.');
fact('united-kingdom','economy','During the Restriction Period, the Bank of England was relieved of its obligation to exchange banknotes for gold.', '1801','1820',2,'Restriction Period1797–1821','Explicit dated restriction period; claim restricted torepresentedUK after1801, no projection of later gold convertibility.');
fact('united-kingdom','economy','The Bank Charter Act1844 restricted existing note issuers in England and Wales and prohibited new banks from commencing note issue across the United Kingdom.', '1845','1930',2,'1844 Bank Charter Act','Source explicitly separates England/Wales restrictions from UK-wide prohibition of new issuers; does not assert early universal monopoly.', ['England/Wales issuing restrictions are not identical to arrangements in Scotland and Ireland.']);
fact('united-kingdom','economy','After Britain left the gold standard in1931, holders had no right to convert Bank of England notes into gold or another asset.', '1932','1960',3,'Gold standard departure1931','Official disclosure explicitly says link finallybroken1931 and no otherasset redemption since. Not a claim that all UK noteissuers were identical.');
const heldEconomy=claims.filter(c=>c.category==='economy');
saveJSON(base+'/held-monetary-context.json',{reason:'Existing validator and frozen production reader support Economy statistics only. Qualitative monetary intervals are evidenced but cannot be integrated into the current category without a separately reviewed compatibility change. No statistics are manufactured.',claims:heldEconomy,sources});
claims.splice(0,claims.length,...claims.filter(c=>c.category!=='economy'));
function figure(entityId,name,personId,from,until,lifeFrom,lifeUntil,url,title,institution,relationship,activity,contribution,categories,extra=[]){
 const source={id:'regional01-figure-'+personId,title,institution,url,accessed:'2026-10-02',kind:'institutional-biographical-history',usage:'Bounded factual paraphrase; territorial association is activity/residence, not birthplace or assumed nationality.'};sources.push(source);
 fact(entityId,'important-figures',name,from,until,sources.length-1,'Biographical chronology and institutional historical activity',relationship+' '+activity+' '+contribution,extra);
 claims.at(-1).figure={personId,name,categories,lifespan:{from:lifeFrom,until:lifeUntil},relationship,activity,contribution};
}
figure('portugal-political-frameworks','Fernando Pessoa','fernando-pessoa','1913','1934','1888','1935','https://casafernandopessoa.pt/en/fernando-pessoa/life','Fernando Pessoa: The Poet of Many Masks','Casa Fernando Pessoa / Richard Zenith','Adult residence and literary activity in Lisbon; childhood in Durban is distinguished.','Published literary criticism from1912, creative prose from1913 and poems from1914; participated in Portugal’s Modernist movement.','Poetry, prose and literary criticism using distinct authorial heteronyms.',['literary'],['No claim of contemporary worldwide recognition: much of his reputation developed after death.']);
figure('spain-political-frameworks','Francisco de Goya','francisco-goya','1800','1823','1746','1828','https://www.museodelprado.es/en/the-collection/artist/francisco-de-goya-y-lucientes/39568a17-81b5-4d6f-84fa-12db60780812','Francisco de Goya y Lucientes: artist biography','Museo Nacional del Prado','Painter working in Madrid and for Spanish patrons before departing for Bordeaux in1824.','Court painter from1799, with portraiture and printmaking in Spain.','Major portraiture and critical printmaking, including Los Caprichos, published1799.',['artistic'],['Political regimes changed during his career; artistic association does not imply allegiance to a particular government.']);
figure('united-kingdom','Charles Darwin','charles-darwin','1877','1881','1809','1882','https://www.english-heritage.org.uk/visit/places/home-of-charles-darwin-down-house/history/','History of Down House','English Heritage','Lived and researched at Down House, Kent, from1842 until death in1882.','Continued botanical experimentation at Down House in the last two decades of his life.','Developed natural selection and wrote On the Origin of Species1859; later botanical research included Different Forms of Flowers1877.',['scientific']);
figure('united-kingdom','Rudyard Kipling','rudyard-kipling','1911','1935','1865','1936','https://www.nationaltrust.org.uk/visit/sussex/batemans/exhibition-room-at-batemans','Kipling Collection Exhibition Room at Bateman’s','National Trust','Residence and literary work at Bateman’s, Sussex, from1902 to1936; does not equate his Indian birthplace with this association.','Wrote at Bateman’s during this residence.','Influential and debated literary author; wrote Puck of Pook’s Hill and Rewards and Fairies, inspired by the Sussex landscape.',['literary'],['Imperial themes and historical controversy retained; no endorsement of political views.']);
// Complementary institutional references explicitly support lifespan/continuous residence.
const supplements=[
 ['charles-darwin','regional01-darwin-life','Charles Darwin: naturalist blue plaque','English Heritage','https://www.english-heritage.org.uk/visit/blue-plaques/charles-darwin/','Biographical lifespan1809–1882'],
 ['rudyard-kipling','regional01-kipling-residence','Bateman’s garden: heritage record MNA125459','National Trust','https://heritagerecords.nationaltrust.org.uk/HBSMR/MonRecord.aspx?uid=MNA125459','Bateman’s bought1902 and occupied until death1936'],
 ['rudyard-kipling','regional01-kipling-life','Bateman’s: writer’s home','National Trust','https://www.nationaltrust.org.uk/visit/sussex/batemans','Rudyard Kipling1865–1936'],
 ['francisco-goya','regional01-goya-life','Francisco de Goya: Spanish artist biography','Museo Nacional del Prado','https://www.museodelprado.es/coleccion/artista/goya-y-lucientes-francisco-de/39568a17-81b5-4d6f-84fa-12db60780812','Lifespan1746–1828; Madrid activity; departureBordeaux1824'],
];
for(const [personId,id,title,institution,url,note]of supplements){sources.push({id,title,institution,url,accessed:'2026-10-02',kind:'institutional-biographical-history',usage:'Factual paraphrase only.'});for(const c of claims.filter(c=>c.figure?.personId===personId)){c.sourceIds.push(id);c.evidence.push({sourceId:id,locator:'Biographical/residence chronology',note,precision:'year',temporal:c.temporal,interpretation:'direct'});}}
const matrix=readJSON('research/completion-01/reports/completion.json');
const candidates=claims.filter(c=>matrix.rows.some(r=>r.entityId===c.entityId&&r.snapshotYear>=+c.temporal.from.slice(0,4)&&r.snapshotYear<=+c.temporal.until.slice(0,4)&&r.categories[c.category].status!=='supported'));
const cohort={id:'regional01-western-institutional-systems',worker:'western-source-packet-normalizer',sources,claims:candidates};saveJSON(base+'/cohort.json',cohort);
saveJSON(base+'/source-review.json',{scope:'Bounded France/Iberia/UK institutional source packets, all represented snapshots considered; no supported-category duplication intended.',sources,claimsReviewed:candidates.map(c=>({id:c.id,evidence:c.evidence,qualifications:c.qualifications})),held:['Portugal early real interval lacks adequate continuous source in this packet.','Spain1938 capital cannot be flattened across competing governments.','France1815 capital/leadership transitions left open.','No population-to-area scope equivalence or density inferred.','Figures not supplied without activity and significance evidence.']});
console.log(JSON.stringify({claims:candidates.length,sources:sources.length}));
