import fs from 'node:fs';
const out='research/flagship-01/canada';fs.mkdirSync(out,{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));const w=read('research/flagship-01/tier-a-workload.json').find(g=>g.id==='canadian-systems');
const source=read('data/historical-sources.json').sources.find(s=>s.id==='b08-canada-institutions');
const id='canadas-1791-colonial-institutions-context';const temporal={kind:'interval',from:'1815-01-01',until:'1816-01-01',certainty:'exact'};
const scope={id:id+'-upper-lower-canada',description:'The distinct central colonial institutions of Upper Canada and Lower Canada only. Composite research context, not a single colonial government, modern Canadian state, uniform territory, or claim of Indigenous consent.',relationship:'partial'};
const note='Parliamentary history identifies separate provinces under the1791Act, each with its own Crown-appointed legislative/executive councils and elected assembly; the1840union is later. January1bounds are researched calendar clipping, not founding or dissolution dates.';
function claim(key,category,value,metric){return {id:'flagship01-canada-'+key,entityId:id,category,value,temporal,scope,sourceIds:[source.id],evidence:[{sourceId:source.id,locator:'Canadian Parliamentary Institutions, Historical Perspective; Constitutional Act1791 paragraphs (web lines179–184); chronology1791/1840rows',note,precision:'year',temporal:{kind:'interval',from:'1791',until:'1840',certainty:'exact'},interpretation:'contextual'}],status:'supported',risks:[],qualifications:[note,'Upper and Lower Canada had separate institutions; representative assemblies did not establish responsible government in1815.'],origin:{kind:'new-research',reference:'Flagship01 Canadian systems; reuse accepted parliamentary history source with bounded1815institutional subset',sourceIdentifier:key},...(metric?{metric}:{})};}
const claims=[claim('1815-status','political-institutional','Upper Canada and Lower Canada: distinct British colonial provinces','state-type'),claim('1815-government','political-institutional','Each province had a governor advised by an appointed executive council, an appointed legislative council and an elected assembly','government-system'),claim('1815-overview','overview','In1815, Upper Canada and Lower Canada remained separate colonial provinces under the1791constitutional arrangements. Each had its own appointed councils and elected assembly. Their union into the Province of Canada belonged to a later constitutional phase; the federal Dominion established in1867 is not projected backward.')];
const entity={id,names:[{value:'Upper and Lower Canada — separate colonial institutions',validFrom:temporal.from,validUntil:temporal.until,sourceIds:[source.id],confidence:'documented',kind:'primary'}],aliases:[],flags:[],politicalStatus:[],capitals:[],governments:[],leaders:[],population:[],economy:[],area:[],currencies:[],relationships:[],predecessors:[],successors:[],events:[],descriptions:[],existence:{validFrom:temporal.from,validUntil:temporal.until,sourceIds:[source.id],note:'Bounded1815research context for separate Upper/Lower Canada institutions; neither a whole modern-country polity nor an exhaustive British North America profile.'}};
const mapping={mapId:'entity-canada',entityId:id,validFrom:temporal.from,validUntil:temporal.until,sourceIds:[source.id],note:'Partial institutional association with Upper/Lower Canada only. Other colonial administrations and Indigenous polities are excluded. No claim that raw map polygon matches either province.'};
const assessment=w.occurrences.map(o=>({id:o.id,mapId:o.mapId,snapshotYear:o.snapshotYear,entityId:o.entityId,stateBefore:o.state,fieldsBefore:Object.fromEntries(Object.entries(o.categories).map(([k,v])=>[k,v.status])),action:o.id==='entity-canada@1815'?'New bounded partial colonial-institutional context: identity/status/government/overview; leadership/capital held.':o.entityId?'Retain accepted evidence; no duplicated core research or rewritten claims.':'Hold raw-label identity pending administrative scope evidence; do not map to modernCanada.',remainingCoreGaps:['leadership','capital'].filter(k=>['missing','held','partial'].includes(o.categories[k]?.status)),unimplemented:['religion'],claimsAdded:o.id==='entity-canada@1815'?claims.map(c=>c.id):[]}));
function readable(obj){if(Array.isArray(obj))return obj.map(readable);if(obj&&typeof obj==='object')return Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,typeof v==='string'&&['value','note','action','reason','locator'].includes(k)?v.replace(/([A-Za-z])(\d)/g,'$1 $2').replace(/(\d)([A-Za-z])/g,'$1 $2').replace('In1815','In 1815'):readable(v)]));return obj;}
const write=(name,obj)=>fs.writeFileSync(out+'/'+name,JSON.stringify(readable(obj),null,2)+'\n');
write('cohort.json',{id:'flagship01-canadian-systems-core',worker:'flagship01-canada',claims,sources:[source]});
write('registry-patch.json',{mode:'proposal-only',entities:[entity],mappings:[mapping],note:'No existing mappings/accepted entities or claims overwritten;1815gap only. Partial scope is mandatory.'});
write('source-review.json',{status:'root-independent-review-required',sources:[{sourceId:source.id,url:source.url,bodyReviewed:true,reusedExactSourceObject:true,locator:'Historical Perspective:1791constitutional arrangements, lines179–184; chronological1791and1840rows',supports:claims.map(c=>c.id),scope:'Separate Upper and Lower Canada provincial institutions only',precision:'1791and1840year-level chronology;1815calendar interior clipping'}],budgetDecision:'Parent primary usage92%: stopped new research after one strong accepted-source body read; three bounded proposals only.'});
write('held.json',{items:[{occurrences:['entity-acadian-peninsula-uk@1800','entity-quebec@1800'],reason:'Raw labels do not prove exact colonial administrative scope. No modernCanadian/Quebec identity fallback.'},{occurrences:['entity-canada@1815'],fields:['capital','leadership','currency'],reason:'Separate provincial offices and seats require dated evidence; no single allCanada capital/governor invented.'},{occurrences:w.occurrences.filter(o=>/newfoundland/.test(o.entityId||'')).map(o=>o.id),fields:['capital','leadership','currency'],reason:'Governor catalogue retrieval502; search snippets not promoted to reviewed claims; officeholders/seat/monetary continuity held.'},{occurrences:w.occurrences.filter(o=>o.categories.currency.status==='missing').map(o=>o.id),fields:['currency'],reason:'1871dollar-reform discovery not body-reviewed; insufficient verified continuing interval for new multi-snapshot monetary claims.'},{occurrences:w.occurrences.filter(o=>o.entityId==='ruperts-land-chartered-framework').map(o=>o.id),fields:['capital','leadership'],reason:'Chartered company territory does not establish one uniform governmental seat or governor tenure from raw label.'}],note:'Religion is unimplemented; Density unchanged. Existing1878leadership gap is retained; no fabricated inter-ministry dates.'});
write('all-snapshot-assessment.json',{group:w.id,name:w.name,occurrenceCount:assessment.length,assessedAll:true,newClaims:claims.length,newlyAffectedOccurrences:['entity-canada@1815'],retainedAcceptedOccurrences:assessment.filter(o=>o.entityId).length,assessment});
console.log({claims:claims.length,assessed:assessment.length});
