import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const out=path.dirname(fileURLToPath(import.meta.url));
const registry=[...JSON.parse(fs.readFileSync('data/historical-sources.json','utf8')).sources,...JSON.parse(fs.readFileSync('data/comprehensive-dossiers.json','utf8')).packages.flatMap(p=>p.sources)];
const sources=[];
const normal=u=>u.replace(/\/$/,'').replace(/%27/g,"'");
function source(id,title,institution,url,kind='official-institutional-history'){
  const existing=registry.find(s=>normal(s.url||'')===normal(url));
  const s=existing?{...existing}:{id,title,institution,url,accessed:'2026-10-02',kind,usage:'Individual factual paraphrases and source locators; no source images or full source text redistributed.'};
  if(!sources.some(x=>x.id===s.id))sources.push(s);
  return s.id;
}
const palaces=source('r15-unesco-abomey','Royal Palaces of Abomey','UNESCO World Heritage Centre','https://whc.unesco.org/en/list/323/');
const gl=source('r15-quai-branly-royal-treasures','Restitution de 26 œuvres à la République du Bénin','Musée du quai Branly – Jacques Chirac','https://www.quaibranly.fr/fr/collections/vie-des-collections/actualites/restitution-de-26-oeuvres-a-la-republique-du-benin/','official-museum-catalogue');
const aof=source('r15-national-archives-aof-place','Afrique Occidentale Française. 1895–1958 — place authority record','Archives nationales de France','https://rdf.archives-nationales.culture.gouv.fr/garance/entities/place/FRAN_RI_005-d5bdp4q7h6-ul70lkju24s3/','official-archival-authority');
const anom=source('r15-anom-territorial-fonds','Les fonds territoriaux','Archives nationales d’outre-mer','https://archives-nationales-outre-mer.culture.gouv.fr/faire-une-recherche/les-fonds-territoriaux');
const cirad=source('r15-cirad-tourte-vol4','Histoire de la recherche agricole en Afrique tropicale francophone, volume IV — René Tourte','CIRAD; René Tourte','https://collaboratif.cirad.fr/alfresco/s/d/workspace/SpacesStore/f5efb13a-b1f6-4c07-974e-4d96dfd6d469/217506.pdf','institutional-scholarly-history');
const bank=source('r15-bceao-institutional-chronology','Chronologie des événements marquants de l’histoire de la BCEAO et de l’UMOA','Banque Centrale des États de l’Afrique de l’Ouest','https://www.bceao.int/sites/default/files/2019-12/Chronologie%20des%20%C3%A9venements%20marquants%20de%20l%27histoire%20de%20la%20BCEAO%20et%20de%20l%27UMOA.pdf');
const cfa=source('r15-bceao-cfa-history','Histoire du franc CFA','Banque Centrale des États de l’Afrique de l’Ouest','https://www.bceao.int/fr/content/histoire-du-franc-cfa');
const mandate=source('r15-togo-mandate-original','Togo — occupation decrees and French mandate of 20 July 1922','League of Nations / French government / Université de Perpignan','https://mjp.univ-perp.fr/constit/tg1920.htm','primary-legal-document');
const independence=source('r15-togo-independence-history','Togo — recognition and diplomatic history','United States Department of State, Office of the Historian','https://history.state.gov/countries/togo');
const diagne=source('r15-assemblee-diagne','Blaise Diagne — parliamentary mandates and Jean Jolly biographical entry','Assemblée nationale de France','https://www2.assemblee-nationale.fr/sycomore/fiche/2496','official-parliamentary-biography');
const claims=[];
const interval=(from,until)=>({kind:'interval',from,until,certainty:'exact'});
const event=date=>({kind:'event',date,certainty:'exact'});
const observation=observationDate=>({kind:'observation',observationDate,certainty:'exact'});
function claim(id,entityId,category,value,temporal,refs,locator,note,extra={}){
  claims.push({id:'r15-french-'+id,entityId,category,value,temporal,
    scope:{id:entityId+'-'+id,description:'Named historical administration or royal polity; no geometry-derived sovereignty or modern-country backprojection.',relationship:'same'},
    sourceIds:refs,evidence:refs.map(sourceId=>({sourceId,locator,note,precision:[temporal.date,temporal.observationDate,temporal.from,temporal.until].some(d=>/^\d{4}-\d{2}-\d{2}$/.test(d||''))?'day':'year',temporal,interpretation:'direct'})),
    status:'supported',risks:[],qualifications:['Curated research bounds are not historical foundation, accession or dissolution dates. Year-only evidence is not given invented event precision.'],
    origin:{kind:'new-research',reference:'Regional Batch 15 French West African original institutional source packet',sourceIdentifier:id},...extra});
}
claim('abomey-1800','dahomey-1800-royal-core','capital','Abomey — royal palace decision-making centre',interval('1800','1800'),[palaces],'Description; Outstanding Universal Value, historical decision-making centre','UNESCO locates the royal decision-making centre in Abomey. The one-year window follows the existing royal entity, not modern Benin.',{role:'Royal capital'});
claim('abomey-1878-1880','dahomey-1880-royal-core','capital','Abomey — royal palace decision-making centre',interval('1878','1880'),[palaces],'Description; Outstanding Universal Value','Royal political centre; research window excludes colonial conquest and post-conquest monarchs.',{role:'Royal capital'});
claim('glele-1878-1880','dahomey-1880-royal-core','leadership','Glélé',interval('1878','1880'),[gl],'Royal bochio statue of Glélé, inventory 71.1893.45.2; royal throne','Museum dates Glélé to 1858–1889. Only complete interior royal years are used.',{role:'King of Dahomey'});
claim('dakar-federal-capital','aof-1904-federal-framework-core','capital','Dakar',interval('1905','1938'),[aof,anom],'Archives authority generalDescription; ANOM AOF territorial fonds','Archival authority identifies Dakar as federal capital; ANOM places the former Governor-General seat there. Restricted post-1904 window avoids initial Saint-Louis headquarters.',{role:'Federal administrative capital'});
claim('ponty-governor-general','aof-1904-federal-framework-core','leadership','William Merlaud-Ponty',interval('1909','1914'),[cirad],'Volume IV printed pp103,169; PDF pp116,182','Tourte explicitly dates Governor-General Ponty 1908–1915. Conservative interior omits both transition years.',{role:'Governor-General of French West Africa'});
claim('aof-colonial-franc','aof-1904-federal-framework-core','currency','Franc — colonial monetary issue',interval('1905','1938'),[bank],'Introduction pI; monetary chronology BAO 1901–1955','BCEAO traces franc introduction in western French colonies and BAO issuance. This does not claim cash exclusively displaced local exchange media.',{qualifications:['Colonial franc before CFA creation in December 1945; CFA is not projected backward. Historical issuance regime, not a claim of exclusive use in every local transaction.']});
claim('togo-colonial-franc','togo-1922-mandate-core','currency','Franc — BAO monetary issue',interval('1923','1944'),[bank],'Introduction pI; printed p8 BAO Lomé agency; printed p14 CFA creation','BAO operations at Lomé precede the curated mandate window; CFA begins only in December 1945. No claim about British Togoland.',{qualifications:['Conservative full-year window ends before the 1945 monetary transition; no current currency backprojection.']});
claim('togo-cfa-1945','togo-1922-mandate-core','currency','CFA franc — colonial monetary issue',interval('1945-12-26','1946-01-01'),[bank,cfa],'BCEAO chronology printed p14; CFA history Origine and parities table','CFA creation is dated 26 December 1945; BCEAO chronology explicitly covers AOF and Togo. Applies only to the last six days of the mandate entity window.',{qualifications:['Within-year monetary transition. Not evidence that CFA existed throughout 1945. Historical 1945 name referred to French African colonies.']});
claim('togo-cfa-1960','togo-1960-independent-core','currency','CFA franc — BCEAO issue',interval('1960-04-27','1961-01-01'),[bank,cfa],'BCEAO chronology Introduction, Institut d’Émission AOF/Togo 1955–1959 and BCEAO from1959; CFA historical parities','The emission history includes Togo and continues through 1960. Research bounds follow the independent entity rather than dating a currency introduction to independence.',{qualifications:['No claim that the 1962 UMOA treaty had already entered force, or that its later currency-name expansion applied in 1960. Start/end are curated entity-window bounds.']});
claim('togo-cfa-first-parity','togo-1922-mandate-core','economy',1.7,observation('1945-12-26'),[cfa],'Historical parity table, Création du FCFA row','Official initial parity: one CFA franc equals 1.70 French francs on 26 December 1945.',{metric:'exchange-rate',unit:'French francs per CFA franc',qualifications:['Dated monetary parity, not GDP or national income; counterpart is the pre-1960 French franc. Actual observation date retained.']});
claim('togo-cfa-transition','togo-1922-mandate-core','events-context','Creation of the CFA franc in the French African monetary system, including French-administered Togo',event('1945-12-26'),[bank,cfa],'Chronology printed p14; CFA history Origine','Regionally significant monetary transition; no assertion of independence or change in mandatory power.');
claim('togo-mandatory-france','togo-1922-mandate-core','relationships','France was the mandatory power administering French Togoland under the League of Nations mandate',interval('1923','1945'),[mandate],'Mandat français sur le Togo, Acte de Londres 20 July1922, Articles2–12','Mandate legal powers and reporting duties name France. The mandate is not annexation, and British Togoland is not included.',{relatedEntityIds:['france-political-frameworks'],qualifications:['Mandate administration distinguished from sovereignty and the later United Nations trusteeship. Existing entity bounds end before1946.']});
claim('togo-independence-event','togo-1960-independent-core','events-context','Togo became independent from French-administered United Nations trusteeship',event('1960-04-27'),[independence],'U.S. Recognition of Togo,1960','Official diplomatic history dates independence and U.S. recognition to27April1960. British Togoland is not merged into this entity.');
claim('diagne-election','aof-1904-federal-framework-core','events-context','Blaise Diagne was elected deputy for Senegal to the French Chamber of Deputies',event('1914-05-10'),[diagne],'Mandats, XIe législature; Jean Jolly biography election paragraph','Senegal constituency within AOF, not election as ruler of the federation.');
claim('blaise-diagne-rights','aof-1904-federal-framework-core','important-figures','Blaise Diagne — Senegal parliamentary representative and advocate concerning African political rights',interval('1919','1933'),[diagne],'Jean Jolly biography: political rights legislation1915–1916, recruitment mission1918; mandates1914–1934','Significance rests on documented rights advocacy and regional political intervention, not officeholding alone. The account also records his support for colonial military recruitment.',{figure:{personId:'blaise-diagne',name:'Blaise Diagne',categories:['political','reformist'],lifespan:{from:'1872-10-13',until:'1934-05-11'},relationship:'Representative of Senegal, a constituent territory of AOF; regional recruitment commissioner in1918, not Governor-General.',activity:'Continued Senegal parliamentary representation and Dakar municipal political activity.',contribution:'Advocacy linking African political rights and military obligations, documented in legislation1915–1916.'},qualifications:['Regional association is constituency and political activity, not projected modern nationality. Later1931 ministerial office is not presented as a1920 fact. Recruitment role was part of colonial government and is not idealised.']});
const cohort={id:'regional15-french-institutional-systems',worker:'regional15-french-source-worker',sources,claims};
fs.writeFileSync(path.join(out,'cohort.json'),JSON.stringify(cohort,null,2)+'\n','utf8');
console.log(JSON.stringify({claims:claims.length,sources:sources.length,categories:claims.reduce((a,c)=>(a[c.category]=(a[c.category]||0)+1,a),{})}));
