import fs from 'node:fs';import crypto from 'node:crypto';import{readContext,digest}from'../../../scripts/research-common.mjs';
const dir='research/regional-01/treaties';fs.mkdirSync(dir,{recursive:true});const ctx=readContext(),store=JSON.parse(fs.readFileSync('data/comprehensive-dossiers.json'));const known=[...ctx.registry.sources,...store.packages.flatMap(p=>p.sources)];const sources=[];function source(id,title,institution,url){const s=known.find(s=>s.url===url)||{id,title,institution,url,accessed:'2026-10-02',kind:'institutional-treaty-history',usage:'Individual factual relationship paraphrases; no images, media or full source copied.'};sources.push(s);return s.id;}
const nato=source('r01-nato-founders','NATO member countries: founding membership and treaty ratification history','North Atlantic Treaty Organization','https://www.nato.int/en/about-us/organization/nato-member-countries');
const nbb=source('b01-belgian-franc','A brief history of the Belgian franc','National Bank of Belgium','https://www.nbb.be/en/banknotes-and-coins/history-euro-and-belgian-franc/brief-history-belgian-franc');
const no=source('r01-nordic-norges-history','History of Norges Bank','Norges Bank','https://www.norges-bank.no/en/topics/about/History/history-of-norges-bank/');
const claims=[];function add(e,value,from,until,sid,targets,locator,qualifications=[]){const t={kind:'interval',from,until,certainty:'exact'};claims.push({id:'r01-treaty-'+digest({e,value,t}).slice(0,20),entityId:e,category:'relationships',value,temporal:t,scope:{id:e+'-sourced-treaty-relationships-'+sid,description:'Documented inter-state treaty relationship; does not imply merged sovereignty, uniform borders or currency issuer.',relationship:'same'},relatedEntityIds:targets,sourceIds:[sid],evidence:[{sourceId:sid,locator,note:'Official institutional account identifies parties and historical relationship; selected interval conservatively excludes transition years.',precision:'year',temporal:t,interpretation:'direct'}],status:'supported',risks:[],qualifications,origin:{kind:'new-research',reference:sid}});}
const founders=['belgium-kingdom','denmark-post-kiel','france-political-frameworks','iceland-sovereign','luxembourg-grand-duchy','netherlands-kingdom','norway-constitutional-kingdom','portugal-political-frameworks','united-kingdom'];const needs=JSON.parse(fs.readFileSync('research/regional-01/workload.json')).batches[0].needs;
for(const e of founders)if(needs.some(n=>n.entityId===e&&n.snapshot===1960&&n.categories.relationships))add(e,'A founding participant in the North Atlantic Treaty collective-defence alliance alongside the other founding states.', '1950','1960',nato,founders.filter(x=>x!==e),'1949 – The 12 founding members: original signatories named; all ratified within five months. Historical France 1966 military-command withdrawal is distinguished from alliance membership.', ['Related entities list the Western/Northern European founding partners represented in this research batch; Canada, Italy and the United States are also founding parties but not enumerated here.','No assertion that all members have identical armed forces or military-command participation.']);
add('france-political-frameworks','Participated in the Latin Monetary Union with Belgium, Switzerland and Italy, coordinating national coin standards.','1866','1924',nbb,['belgium-kingdom','swiss-federal-state'],'Latin Monetary Union (1865–1926): official institutional history identifies France, Italy, Switzerland, Belgium and Greece among participating countries.', ['Monetary agreement, not a merged state or common sovereign currency issuer.','Interval bounded conservatively before dissolution; no assertion that convertibility and practical monetary operation remained unchanged throughout.','Related IDs enumerate Belgium and Switzerland only; the existing Italian framework IDs do not cover the entire claim interval, so Italy remains a sourced literal name without an invented target. Greece is a later participant.']);
if(needs.some(n=>n.entityId==='denmark-post-kiel'&&n.snapshot>=1876&&n.snapshot<=1913&&n.categories.relationships))add('denmark-post-kiel','Participated with Sweden and Norway in the Scandinavian Monetary Union; member-country coins circulated as legal tender on the same basis as domestic coins.','1876','1913',no,['sweden-kingdom','norway-constitutional-kingdom'],'1875 section: Denmark and Sweden established union 1873; Norway joined 16 October 1875; union functioned until 1914.', ['Separate national currencies and monetary institutions remained.','Norway retained its constitutional institutions while sharing a crown with Sweden; this is not an attribution to one undifferentiated Sweden–Norway currency/state.']);
const missing=claims.flatMap(c=>c.relatedEntityIds.filter(id=>!ctx.db.entities.some(e=>e.id===id)));if(missing.length)throw Error('Missing targets '+missing);
const cohort={id:'regional01-western-northern-treaty-relationships',worker:'regional-nordic-treaty-research-worker',sources,claims};fs.writeFileSync(dir+'/cohort.json',JSON.stringify(cohort,null,2)+'\n');console.log({claims:claims.length,sources:sources.length});
