import test from 'node:test';
import assert from 'node:assert/strict';
import {readAtlasState,atlasUrl,createAtlasHistory} from '../atlas-state.js';
const root='https://example.org/atlas/';
test('normal landing and malformed years use 1938',()=>{for(const q of ['','?year=hello','?year=1938.5','?year=-4001','?year=0','?year=1961','?year='])assert.equal(readAtlasState(root+q).year,1938);});
test('exact and between-snapshot years retain requested year',()=>{for(const year of [1800,1815,1939,1960])assert.equal(readAtlasState(root+'?year='+year).year,year);});
test('only bounded stable map IDs are accepted syntactically',()=>{assert.equal(readAtlasState(root+'?territory=entity-france').territory,'entity-france');for(const raw of ['France','<script>','entity-','entity-'+ 'a'.repeat(200)])assert.equal(readAtlasState(root+'?territory='+encodeURIComponent(raw)).territory,null);});
test('URL generation preserves unrelated queries and non-source fragments',()=>{const u=new URL(atlasUrl(root+'?campaign=demo&year=1938&territory=entity-france#notes',{year:1960,territory:'entity-italy'}));assert.equal(u.searchParams.get('campaign'),'demo');assert.equal(u.searchParams.get('year'),'1960');assert.equal(u.searchParams.get('territory'),'entity-italy');assert.equal(u.hash,'#notes');});
test('deselection removes territory and canonical navigation drops internal source anchors',()=>{const u=new URL(atlasUrl(root+'?year=1938&territory=entity-france#dossier-source-a',{year:1939,territory:null}));assert.equal(u.searchParams.has('territory'),false);assert.equal(u.hash,'');});
function fake(){const urls=[root+'?year=1938'],listeners={};let i=0;const w={location:{href:urls[0]},addEventListener:(n,f)=>listeners[n]=f,history:{state:null,pushState:(s,t,u)=>{urls.splice(i+1);urls.push(u);i++;w.location.href=u;},replaceState:(s,t,u)=>{urls[i]=u;w.location.href=u;}},move:d=>{i+=d;w.location.href=urls[i];listeners.popstate();},urls};return w;}
test('dragging creates one recoverable history entry and commits the final year',()=>{const w=fake(),restored=[],h=createAtlasHistory(w,s=>restored.push(s));for(const year of [1939,1940,1941])h.navigate({year,territory:null},'transient');h.navigate({year:1941,territory:null},'commit');assert.equal(w.urls.length,2);w.move(-1);assert.equal(restored.at(-1).year,1938);w.move(1);assert.equal(restored.at(-1).year,1941);});
test('no-op input does not discard the pre-drag navigation state',()=>{const w=fake(),h=createAtlasHistory(w,()=>{});h.navigate({year:1938,territory:null},'transient');h.navigate({year:1940,territory:null},'transient');assert.equal(w.urls.length,2);});
test('meaningful selection and deselection are distinct history entries',()=>{const w=fake(),h=createAtlasHistory(w,()=>{});h.navigate({year:1938,territory:'entity-france'});h.navigate({year:1938,territory:null});assert.equal(w.urls.length,3);});
test('citation/hash history does not rerender the current dossier',()=>{const w=fake(),restored=[],h=createAtlasHistory(w,s=>restored.push(s));w.history.pushState(null,'',root+'?year=1938#dossier-source-a');w.move(-1);assert.equal(restored.length,0);h.navigate({year:1960,territory:null});w.move(-1);assert.equal(restored.at(-1).year,1938);});
test('URL construction deduplicates atlas parameters without touching unrelated state',()=>{const u=new URL(atlasUrl(root+'?year=1900&year=1938&territory=entity-france&territory=entity-italy&x=1',{year:1960,territory:'entity-france'}));assert.equal(u.searchParams.getAll('year').length,1);assert.equal(u.searchParams.getAll('territory').length,1);assert.equal(u.searchParams.get('x'),'1');});
