import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {renderDossier,resolveDossierRecords} from '../dossier.js';import {createMetadataIndex} from '../historical-metadata.js';import {createRichDossierIndex} from '../rich-dossier.js';import {canonicalSections,communityIds,politicalIds,dataState,exchangeGroups,isExchange} from '../dossier-layout.js';
class Element{constructor(tag,text=''){this.tagName=tag;this.text=text;this.childNodes=[];this.dataset={};this.attrs={};}set textContent(v){this.text=String(v);this.childNodes=[];}get textContent(){return this.text+this.childNodes.map(x=>x.textContent).join('');}append(...nodes){for(let n of nodes){if(typeof n==='string')n=new Element('#text',n);if(n.parent){n.parent.childNodes=n.parent.childNodes.filter(x=>x!==n);}n.parent=this;this.childNodes.push(n);}}prepend(n){this.append(n);this.childNodes.pop();this.childNodes.unshift(n);}replaceChildren(...n){this.childNodes=[];this.append(...n);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(){} }
globalThis.document={createElement:t=>new Element(t)};
const read=p=>JSON.parse(fs.readFileSync(new URL('../'+p,import.meta.url))),db=read('data/historical-entities.json'),source=read('data/historical-sources.json'),store=read('data/comprehensive-dossiers.json'),metadata=createMetadataIndex(db,source),rich=createRichDossierIndex(store),registry=new Map([...metadata.registry,...rich.registry]);
const flatten=n=>[n,...n.childNodes.flatMap(flatten)];
function render(id,year,extra={}){const root=new Element('div');renderDossier(root,{stableId:id,savedName:id.replace('entity-',''),year,snapshotYear:year,metadata,rich,features:[{}],...extra});return root.childNodes[0];}
const cases=[['entity-france',1960],['entity-italy',1960],['entity-united-kingdom',1914],['entity-russian-empire',1800],['entity-united-kingdom',1960],['entity-mexico',1938],['entity-france',1800]];
for(const [id,y]of cases)test('canonical sections and stable header: '+id+' '+y,()=>{let d=render(id,y);assert.deepEqual(d.childNodes.filter(x=>x.dataset.section).map(x=>x.dataset.section),['Identity Header',...canonicalSections,'Sources & Methodology']);const header=d.childNodes.find(n=>n.tagName==='header');assert.equal(flatten(header).filter(n=>n.dataset.field).length,7);assert.ok(d.textContent.includes(String(y)));});
test('community exclusion is an exact projection of existing classification, never name guessing',()=>{const m=read('development/coverage/manifest.json');assert.deepEqual([...communityIds],[...m.identities.filter(x=>x.classification?.classification==='community-people').map(x=>x.stableMapId)].sort());assert.ok(politicalIds.has('entity-russian-empire'));assert.ok(!render('entity-aboriginal-tasmanians',1800).childNodes.some(n=>n.dataset.section==='Leadership'));});
test('sparse political sections have one compact missing state and no inferred not-applicable concepts',()=>{let d=render('entity-russian-empire',1800),sections=d.childNodes.filter(n=>canonicalSections.includes(n.dataset.section));assert.ok(sections.every(s=>s.childNodes.filter(n=>n.className==='dossier-empty').length<=1));assert.ok(!d.textContent.includes('Not applicable'));});
test('four states remain distinct and require explicit underlying declarations',()=>{assert.equal(dataState(), 'missing');assert.equal(dataState({value:'known'}),'supported');assert.equal(dataState({confidence:'disputed'}),'uncertain');assert.equal(dataState({status:'not-applicable'}),'not-applicable');const d=render('entity-russian-empire',1800,{metadata:{registry:new Map(),resolve:()=>({fieldStates:{leadership:{status:'uncertain'},economy:{status:'not-applicable'}}})}});assert.ok(d.textContent.includes('Uncertain'));assert.ok(d.textContent.includes('Not applicable'));});
test('exchange grouping preserves all records, exact-year preference, counterparts and actual dates',()=>{const row=(id,date,unit='US cents per pound')=>({id,category:'economy',metric:'Foreign exchange quotation — pound',unit,temporal:{kind:'observation',observationDate:date}}),input=[row('a','1937'),row('b','1938-01'),row('c','1938-10'),row('d','1937','francs per pound')],before=JSON.stringify(input),groups=exchangeGroups(input,1938);assert.equal(groups.length,2);assert.equal(groups[0].primary.id,'c');assert.equal(groups.flatMap(g=>[g.primary,...g.additional]).length,input.length);assert.equal(JSON.stringify(input),before);assert.equal(exchangeGroups([row('x','1935'),row('y','1937')],1938)[0].primary.id,'y');});
test('many quotations are compact and fully inspectable, one quotation needs no extra control, none creates no component',()=>{for(const [id,y,expected]of [['entity-united-kingdom',1960,'many'],['entity-mexico',1938,'one'],['entity-united-kingdom',1914,'none']]){const r=metadata.resolve(id,y),rows=resolveDossierRecords(r,rich,y,registry,{mappings:r.mappings}),count=rows.filter(isExchange).length,d=render(id,y),nodes=flatten(d);if(expected==='many'){assert.ok(count>1);assert.equal(nodes.filter(n=>n.className==='dossier-exchange').length,1);assert.equal(nodes.filter(n=>n.className==='quotation-notes').length,count);assert.ok(nodes.some(n=>n.className==='dossier-more exchange-additional'));}if(expected==='one'){assert.equal(count,1);assert.ok(!nodes.some(n=>n.className==='dossier-more exchange-additional'));}if(expected==='none')assert.equal(nodes.filter(n=>n.className==='dossier-exchange').length,0);}});
test('all resolved claim values survive rendering and dated population scope remains explicit',()=>{for(const [id,y]of cases){const r=metadata.resolve(id,y);if(!r.entity)continue;const rows=resolveDossierRecords(r,rich,y,registry,{mappings:r.mappings}),d=render(id,y);for(const c of rows.filter(c=>typeof c.value==='string'&&c.category!=='overview'&&c.category!=='identity'&&c.category!=='historical-flag'))assert.ok(d.textContent.includes(c.value),id+' '+c.id);}const d=render('entity-japan',1938);assert.ok(d.textContent.includes('1935'));assert.ok(d.textContent.includes('excludes imperial colonies'));});
test('transition frameworks retain separate named labels inside fixed ordered sections',()=>{const d=render('entity-japan',1947);assert.deepEqual(d.childNodes.filter(x=>x.dataset.section).map(x=>x.dataset.section),['Identity Header',...canonicalSections,'Sources & Methodology']);assert.ok(flatten(d).some(n=>n.className==='dossier-framework-title'));});
test('rendering never changes accepted production data or legacy metadata',()=>{const before=JSON.stringify([db,source,store]);for(const [id,y]of cases)render(id,y);assert.equal(JSON.stringify([db,source,store]),before);});
