import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readJSON,digest} from '../scripts/research-common.mjs';
const db=readJSON('data/historical-entities.json'),store=readJSON('data/comprehensive-dossiers.json'),report=readJSON('research/completion-01/reports/occurrence-completion.json');
test('both NewGranada occurrences gain useful evidence independently',()=>{for(const y of [1800,1815]){const r=report.rows.find(r=>r.mapId==='entity-viceroyalty-of-new-granada'&&r.snapshotYear===y);assert.ok(r.substantiveEvidenceCount>=4);assert.notEqual(r.status,'completely-empty');}assert.equal(report.metrics.confirmedEligibleOccurrences,1588);assert.equal(report.metrics.excludedOccurrences,585);assert.equal(report.metrics.pendingEligibilityOccurrences,179);});
test('1815 composite receives no fictional leader or uniform capital',()=>{const p=store.packages.find(p=>p.entityId==='new-granada-recovery-1815');assert.ok(!p.claims.some(c=>['leadership','capital'].includes(c.category)));assert.match(db.mappings.find(m=>m.entityId===p.entityId).displayName,/fragmented|reconquest/i);assert.equal(report.rows.find(r=>r.entityId===p.entityId).eligibility.classification,'composite-political-region');});
test('year-only reconquest chronology remains a dated event without invented day',()=>{const p=store.packages.find(p=>p.entityId==='new-granada-recovery-1815'),c=p.claims.find(c=>c.category==='events-context');assert.equal(c.temporal.kind,'event');assert.equal(c.temporal.date,'1815');assert.ok(c.evidence.every(e=>e.precision==='year'&&e.temporal.date==='1815'));});
test('completed first recovery checkpoint remains immutable',()=>{for(const [file,key]of [['data/comprehensive-dossiers.json','packages'],['data/historical-entities.json','entities'],['data/historical-sources.json','sources']]){const old=JSON.parse(execFileSync('git',['show','aa0553c:'+file],{encoding:'utf8',maxBuffer:100*1024*1024}));const hashes=new Set(readJSON(file)[key].map(digest));for(const v of old[key])assert.ok(hashes.has(digest(v)),v.id);}});
