import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {assetHash,inspectFlagAsset,validateFlagClaim,auditResearchFlags} from '../scripts/research-flags.mjs';
import {validatePackage} from '../scripts/research-validator.mjs';
import {planIntegration} from '../scripts/research-integrate.mjs';
import {scan} from '../scripts/research-scan.mjs';
import {digest,productionFingerprint,productionFiles} from '../scripts/research-common.mjs';
const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3 2"><path fill="red" d="M0 0h3v2H0z"/></svg>';
function fixture(){
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-flag-'));fs.mkdirSync(path.join(directory,'assets/flags'),{recursive:true});fs.writeFileSync(path.join(directory,'assets/flags/example.svg'),svg);
 const pkg=JSON.parse(fs.readFileSync(new URL('../research/fixtures/valid-package.json',import.meta.url)));
 pkg.category='core-state';pkg.categories=['historical-flag'];pkg.worker.specialism='entity-core';const c=pkg.claims[0];c.category='historical-flag';c.value='Documented state flag';delete c.metric;c.evidence[0].from=c.temporal.from;c.evidence[0].until=c.temporal.until;
 c.flag={asset:'./assets/flags/example.svg',type:'state flag',alt:'Documented flag',license:'Public domain',attribution:'Archive creator',assetSourceIds:['synthetic-source'],sha256:assetHash(Buffer.from(svg))};
 Object.assign(pkg.sources[0],{license:'Public domain',attribution:'Archive creator',assetUrl:'https://example.org/flag.svg'});
 const entity={id:pkg.entityId,existence:{validFrom:'1800',validUntil:'1961'},flags:[]};
 const context={directory,productionFingerprint:pkg.productionFingerprint,db:{entities:[entity],mappings:[{entityId:entity.id,mapId:pkg.mapIds[0],validFrom:'1800',validUntil:'1961'}]},registry:{sources:[]},manifest:{identities:[]},plan:{reviews:{}}};
 const job={id:pkg.jobId,category:pkg.category,categories:pkg.categories,entityId:pkg.entityId,mapIds:pkg.mapIds,period:pkg.period,productionFingerprint:pkg.productionFingerprint,cautions:[]};
 return {directory,pkg,context,job,cleanup:()=>fs.rmSync(directory,{recursive:true,force:true})};
}
function use(run){const f=fixture();try{run(f);}finally{f.cleanup();}}
test('dated licensed flag package validates with exact hash and needs independent review',()=>use(f=>{const r=validatePackage(f.pkg,f.job,f.context);assert.equal(r.valid,true,r.errors.join('\n'));assert.ok(r.review.some(x=>/INDEPENDENT/.test(x)));}));
test('flag missing file, traversal, changed bytes and executable SVG fail closed',()=>use(f=>{for(const asset of ['./assets/flags/missing.svg','../flag.svg','https://example.org/flag.svg'])assert.ok(inspectFlagAsset(asset,f.directory).length);fs.writeFileSync(path.join(f.directory,'assets/flags/example.svg'),svg.replace('<path','<script>alert(1)</script><path'));assert.equal(validatePackage(f.pkg,f.job,f.context).valid,false);}));
test('embedded external or data references fail while local symbol references may pass',()=>use(f=>{for(const markup of ['<image href="data:image/png;base64,ABC"/>','<use href="https://example.org/a"/>','<path onclick="alert(1)"/>','<style>@import "a";</style>']){fs.writeFileSync(path.join(f.directory,'assets/flags/example.svg'),svg.replace('</svg>',markup+'</svg>'));assert.ok(inspectFlagAsset('./assets/flags/example.svg',f.directory).length);}fs.writeFileSync(path.join(f.directory,'assets/flags/example.svg'),svg.replace('</svg>','<path id="a"/><use href="#a"/></svg>'));assert.deepEqual(inspectFlagAsset('./assets/flags/example.svg',f.directory),[]);}));
test('flag licensing and download-source provenance fail closed',()=>use(f=>{for(const mutate of [c=>c.flag.license='All rights reserved',c=>c.flag.assetSourceIds=['missing'],c=>c.flag.sha256='0'.repeat(64),c=>c.flag.attribution='Other',c=>c.flag.type='modern fallback']){const c=structuredClone(f.pkg.claims[0]);mutate(c);assert.ok(validateFlagClaim(c,new Map(f.pkg.sources.map(s=>[s.id,s])),f.directory).length);}}));
test('flag temporal leakage and point observation cannot pass',()=>use(f=>{f.pkg.claims[0].temporal={kind:'observation',observationDate:'1905'};assert.equal(validatePackage(f.pkg,f.job,f.context).valid,false);f.pkg.claims[0].temporal={kind:'interval',from:'1935',until:'1939'};assert.equal(validatePackage(f.pkg,f.job,f.context).valid,false);}));
test('flag adapter retains explicit historical type, license and provenance without production mutation',()=>use(f=>{const validation=validatePackage(f.pkg,f.job,f.context),receipt={status:'accepted',jobId:f.job.id,packageHash:digest(f.pkg),productionFingerprint:f.context.productionFingerprint,coordinator:{id:'reviewer',role:'coordinator'},rationale:'Independently read archival flag evidence',reviewResolved:true,reviewedIssues:validation.review};const before=digest(f.context.db);const plan=planIntegration(f.pkg,f.job,f.context,receipt),flag=plan.db.entities[0].flags[0];assert.equal(digest(f.context.db),before);assert.equal(flag.flagType,'state flag');assert.equal(flag.assetSha256,f.pkg.claims[0].flag.sha256);assert.match(flag.note,/Type: state flag/);assert.equal(auditResearchFlags({...f.context,db:plan.db,registry:plan.registry}).valid,true);}));
test('dated flag completeness excludes undated assets and distinguishes qualified ensigns',()=>use(f=>{const e=f.context.db.entities[0];f.context.registry.sources=f.pkg.sources;e.flags=[{value:'Flag',validFrom:'1900-01-01',validUntil:'1901-01-01',sourceIds:['synthetic-source'],asset:'./assets/flags/example.svg',flagType:'state flag',license:'Public domain',attribution:'Archive creator'}];let r=scan(f.context,{from:1900,until:1901});assert.equal(r.metrics.flagCoverage.fullySupportedYears,1);assert.equal(r.metrics.flagCoverage.missingYears,1);e.flags[0].flagType='colonial ensign';r=scan(f.context,{from:1900,until:1900});assert.equal(r.metrics.flagCoverage.partialYears,1);e.flags[0].flagType='state flag';delete e.flags[0].validFrom;delete e.flags[0].validUntil;r=scan(f.context,{from:1900,until:1900});assert.equal(r.metrics.flagCoverage.fullySupportedYears,0);}));
test('new integrated asset bytes change fingerprint, legacy baseline remains unaffected',()=>use(f=>{const db=f.context.db;for(const file of productionFiles){fs.mkdirSync(path.dirname(path.join(f.directory,file)),{recursive:true});fs.writeFileSync(path.join(f.directory,file),file.includes('historical-entities')?JSON.stringify(db):'fixture');}const before=productionFingerprint(f.directory);fs.writeFileSync(path.join(f.directory,'assets/flags/example.svg'),svg+'\n');assert.equal(productionFingerprint(f.directory),before);db.entities[0].flags=[{asset:'./assets/flags/example.svg',researchProvenance:{claimId:'flag'}}];fs.writeFileSync(path.join(f.directory,'data/historical-entities.json'),JSON.stringify(db));const integrated=productionFingerprint(f.directory);fs.writeFileSync(path.join(f.directory,'assets/flags/example.svg'),svg);assert.notEqual(productionFingerprint(f.directory),integrated);}));

test('safe SVG clip paths permit declared internal fragments but refuse external or missing resources',()=>use(f=>{for(const target of ['#clip','https://example.org/clip','#missing']){fs.writeFileSync(path.join(f.directory,'assets/flags/example.svg'),svg.replace('</svg>','<clipPath id="clip"><path/></clipPath><g clip-path="url('+target+')"/></svg>'));const errors=inspectFlagAsset('./assets/flags/example.svg',f.directory);assert.equal(errors.length===0,target==='#clip');}}));

test('flag asset source URL reuse resolves nested provenance aliases without duplicate source records',()=>use(f=>{const proposed=f.pkg.sources[0],old={...proposed,id:'existing-asset-source'};f.context.registry.sources=[old];const r=validatePackage(f.pkg,f.job,f.context);assert.equal(r.valid,true,r.errors.join('\n'));const receipt={status:'accepted',jobId:f.job.id,packageHash:digest(f.pkg),productionFingerprint:f.context.productionFingerprint,coordinator:{id:'reviewer',role:'coordinator'},rationale:'Independent review confirms reused historical asset source',reviewResolved:true,reviewedIssues:r.review};const plan=planIntegration(f.pkg,f.job,f.context,receipt),flag=plan.db.entities[0].flags[0];assert.equal(plan.registry.sources.length,1);assert.deepEqual(flag.sourceIds,['existing-asset-source']);assert.deepEqual(flag.assetSourceIds,['existing-asset-source']);assert.equal(auditResearchFlags({...f.context,db:plan.db,registry:plan.registry}).valid,true);}));
