import test from 'node:test';
import assert from 'node:assert/strict';
import {completionMatrix,validateResolutions,completionCategories} from '../scripts/research-completion.mjs';
import {digest,readContext,productionFingerprint} from '../scripts/research-common.mjs';
const source={id:'s',title:'Historical document',institution:'Archive',url:'https://example.org/document'};
function fixture(){const categories=Object.fromEntries(completionCategories.slice(0,-1).map(c=>[c,{status:'missing',records:[],issues:[]}])) ;return{context:{db:{entities:[{id:'state',names:[{value:'State'}]}]},registry:{sources:[source]},productionFingerprint:'unchanged'},options:{rich:{packages:[]},scan:{rows:[{entityId:'state',snapshotYear:1900,mapIds:['raw'],categories}],snapshots:[{year:1900}],rawReview:[],errors:[],configurationWarnings:[],metrics:{supportedSnapshotCategorySlots:0,applicableSnapshotCategoryOpportunities:14}}}};}
function assessment(status='uncertain'){const r={id:'assessment',entityId:'state',category:'density',period:{from:'1899-01-01',until:'1901-01-01'},status,rationale:'Evidence cannot resolve this historical question',evidenceNote:'Explicit assessment from cited source',scope:'Historical territory',sourceIds:['s'],worker:'researcher'};r.review={reviewer:'independent-reviewer',decision:'accepted',contentHash:digest(r)};return r;}
test('missing is not resolved and status category remains visible',()=>{const{context,options}=fixture(),r=completionMatrix(context,options);assert.equal(r.metrics.totalSlots,15);assert.equal(r.metrics.researchResolution,0);assert.equal(r.rows[0].categories['historical-context-status'].status,'missing');});
test('partial evidence has no arbitrary fractional score',()=>{const{context,options}=fixture();options.scan.rows[0].categories.capital.status='partial';const r=completionMatrix(context,options);assert.equal(r.metrics.states.partial,1);assert.equal(r.metrics.evidenceCoverage,0);assert.equal(r.metrics.researchResolution,0);});
test('independently established uncertainty counts resolution but not evidence',()=>{const{context,options}=fixture();options.resolutions=[assessment()];const r=completionMatrix(context,options);assert.equal(r.metrics.states.uncertain,1);assert.equal(r.metrics.evidenceCoverage,0);assert.equal(r.metrics.researchResolution,100/15);});
test('established non-applicability removes applicable denominator only',()=>{const{context,options}=fixture();options.resolutions=[assessment('not-applicable')];const r=completionMatrix(context,options);assert.equal(r.metrics.applicableSlots,14);assert.equal(r.metrics.totalSlots,15);assert.equal(r.metrics.researchResolution,100/15);});
test('held source evidence is neither uncertainty nor resolution',()=>{const{context,options}=fixture();options.held=[{id:'candidate',entityId:'state',category:'population-statistics',snapshotYears:[1900],reason:'Territory mismatch',evidencePath:'preserved.json'}];const r=completionMatrix(context,options);assert.equal(r.metrics.states.held,1);assert.equal(r.metrics.researchResolution,0);});
test('resolution needs provenance, independent review, hash and valid dates',()=>{for(const mutate of [r=>r.sourceIds=['orphan'],r=>r.review.reviewer=r.worker,r=>r.period.until='1898-01-01',r=>r.scope='',r=>r.evidenceNote='',r=>r.rationale='changed']){const{context,options}=fixture(),r=assessment();mutate(r);assert.throws(()=>validateResolutions([r],context,options.scan.rows,options.rich));}});
test('an incompatible candidate cannot resolve a whole category automatically',()=>{const{context,options}=fixture();assert.throws(()=>validateResolutions([assessment('territorially-incompatible')],context,options.scan.rows,options.rich),/incompatible candidate/);});
test('overlapping resolutions fail closed',()=>{const{context,options}=fixture(),a=assessment(),b={...assessment(),id:'other'};b.review={...b.review,contentHash:digest(Object.fromEntries(Object.entries(b).filter(([k])=>k!=='review')))};assert.throws(()=>validateResolutions([a,b],context,options.scan.rows,options.rich),/Overlapping/);});
test('imprecise transition year is not silently resolved for entire year',()=>{const{context,options}=fixture(),r=assessment();r.period.from='1900';r.review.contentHash=digest(Object.fromEntries(Object.entries(r).filter(([k])=>k!=='review')));options.resolutions=[r];assert.equal(completionMatrix(context,options).metrics.states.missing,15);});
test('resolution never overwrites existing sourced facts',()=>{const{context,options}=fixture();options.scan.rows[0].categories.density.records=[{claimId:'sourced'}];options.resolutions=[assessment()];assert.throws(()=>completionMatrix(context,options),/overwrite/);});
test('queue is bounded and deterministic with stable IDs',()=>{const{context,options}=fixture(),r=completionMatrix(context,options);assert.deepEqual(r,completionMatrix(context,options));assert.equal(r.queue[0].category,'identity');assert.ok(r.queue.every(j=>j.entityId==='state'&&j.snapshotYear===1900));assert.equal(new Set(r.queue.map(j=>j.id)).size,15);});
test('real database reports all snapshots without altering production',()=>{const before=productionFingerprint(),r=completionMatrix(readContext());assert.ok(r.metrics.dossiers>=1056);assert.equal(Object.keys(r.bySnapshot).length,11);assert.equal(r.metrics.totalSlots,r.metrics.dossiers*15);assert.equal(productionFingerprint(),before);assert.ok(r.errors.every(e=>e.reason.includes('temporal')));});
test('full-year government evidence does not make a partial political-status record complete',()=>{const{context,options}=fixture();const record={value:'Transitional status',validFrom:'1900-06-01',validUntil:'1901-01-01',sourceIds:['s']};context.db.entities[0].politicalStatus=[record];const temporal={kind:'interval',from:record.validFrom,until:record.validUntil};const claimId='legacy-'+digest({entityId:'state',category:'political-institutional',value:record.value,temporal,role:undefined,metric:undefined});options.scan.rows[0].categories['political-institutional']={status:'supported',records:[{claimId,actualTemporal:temporal,sourceIds:['s']}],issues:[]};assert.equal(completionMatrix(context,options).rows[0].categories['historical-context-status'].status,'partial');});
