import test from 'node:test';
import assert from 'node:assert/strict';
import {readContext,digest} from '../scripts/research-common.mjs';
import {temporalBounds} from '../scripts/research-comprehensive.mjs';
import {validateLiteralRelationshipReuse} from '../scripts/research-completion-reuse.mjs';
import {relationshipStatusPredicate} from '../research/completion-01/relationships/predicate.mjs';
function fixture(){const context=readContext(),e=context.db.entities.find(e=>e.id==='hong-kong-historical-administration'),r=e.politicalStatus.find(r=>r.value==='British colonial administration'),t={kind:'interval',from:r.validFrom,until:r.validUntil};const reference='legacy-'+digest({entityId:e.id,category:'political-institutional',value:r.value,temporal:t,role:r.role,metric:r.metric});return{context,claim:{category:'relationships',entityId:e.id,value:r.value,relatedParty:'British',temporal:{...t,certainty:'exact'},sourceIds:r.sourceIds,qualifications:r.note?[r.note]:[],origin:{kind:'production-reuse',reference,sourceIdentifier:digest(r)},evidence:r.sourceIds.map(sourceId=>({sourceId,locator:reference}))}};}
test('named literal colonial affiliation reuses exact evidence without creating target IDs',()=>{const {context,claim}=fixture();assert.ok(validateLiteralRelationshipReuse(claim,context,temporalBounds));assert.equal(claim.relatedEntityIds,undefined);});
test('changed wording, dates, sources or counterpart cannot reuse accepted status',()=>{const {context,claim}=fixture();for(const change of [{value:'British sovereign ownership'},{relatedParty:'French'},{sourceIds:['basemaps']},{temporal:{kind:'interval',from:'1800-01-01',until:'1961-01-01',certainty:'exact'}}])assert.equal(validateLiteralRelationshipReuse({...claim,...change},context,temporalBounds),false);});
test('unsupported or ambiguous status cannot be promoted',()=>{const {context,claim}=fixture(),c=structuredClone(context);c.db.entities.find(e=>e.id===claim.entityId).politicalStatus.find(r=>r.value===claim.value).confidence='uncertain';assert.equal(validateLiteralRelationshipReuse(claim,c,temporalBounds),false);});
test('predicate holds missing, future, former and unnamed affiliations',()=>{for(const value of ['Independent republic','Kingdom in dynastic personal union','Separate kingdom before union with Great Britain','Occupied former Italian colonial territory','Federal republic after termination of the Occupation Statute; continuing Allied reserved rights'])assert.equal(relationshipStatusPredicate(value).eligible,false,value);});
test('existing linked relationships do not silently use literal-party exception',()=>{const {context,claim}=fixture();assert.equal(validateLiteralRelationshipReuse({...claim,relatedEntityIds:['united-kingdom']},context,temporalBounds),false);assert.equal(validateLiteralRelationshipReuse({...claim,origin:{...claim.origin,kind:'new-research'}},context,temporalBounds),false);});
