import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {scanSnapshots,readSnapshotConfig,writeSnapshotReport} from '../scripts/research-snapshot-scan.mjs';
const source={id:'s',title:'Historical source',institution:'Archive',url:'https://example.org/primary'};
function fixture(years=[1878,1880]){return{directory:os.tmpdir(),db:{entities:[{id:'state',names:[{value:'State',validFrom:'1800',validUntil:'1901',sourceIds:['s']}]}],mappings:[{mapId:'raw-a',entityId:'state',validFrom:'1800',validUntil:'1901'},{mapId:'raw-b',entityId:'state',validFrom:'1800',validUntil:'1901'}]},registry:{sources:[source]},manifest:{identities:['raw-a','raw-b'].map(stableMapId=>({stableMapId,snapshotYears:years,classification:{classification:'political-polity'}})),classification:{politicalCoverage:{available:362,total:401}}},plan:{reviews:{}},rich:{packages:[]}};}
const snapshots=years=>years.map(year=>({year,file:'world_'+year+'.geojson'}));
function claim(category='leadership',temporal={kind:'interval',from:'1875',until:'1888'}){return{id:'claim',entityId:'state',category,value:'Ruler',role:'Head of state',sourceIds:['s'],temporal,status:'supported',risks:[],scope:{relationship:'same',description:'Historical polity'}};}
function rich(c,claims){c.rich.packages=[{entityId:'state',sources:[],claims,period:{from:'1800',until:'1901'},investigation:[]}];}
const scan=(c,years=[1878,1880],options={})=>scanSnapshots(c,{snapshots:snapshots(years),...options});
test('authoritative current list read from app and manifest presence deduplicated',()=>{assert.equal(readSnapshotConfig().length,11);const r=scan(fixture());assert.equal(r.rows.length,2);assert.deepEqual(r.rows[0].mapIds,['raw-a','raw-b']);assert.equal(r.metrics.snapshotCategoryOpportunities,28);assert.equal(r.metrics.resolverAvailability.available,362);});
test('one interval supports several snapshots without copying records',()=>{const c=fixture();rich(c,[claim()]);const r=scan(c);assert.equal(r.metrics.uniqueClaimsSupportingSnapshots,2);assert.equal(r.metrics.claimSnapshotApplications,4);assert.equal(r.metrics.reusedApplications,2);assert.equal(r.rows[0].categories.leadership.status,'supported');});
test('actual observation dates retained, prior compatible census supports nearby context',()=>{const c=fixture([1938]);c.db.mappings.forEach(m=>m.validUntil='1940');rich(c,[claim('population-statistics',{kind:'observation',observationDate:'1937'})]);const r=scan(c,[1938]);const f=r.rows[0].categories['population-statistics'].records[0];assert.equal(f.actualTemporal.observationDate,'1937');assert.equal(f.mode,'nearby-observation');});
test('future observation never leaks backwards',()=>{const c=fixture([1880]);rich(c,[claim('population-statistics',{kind:'observation',observationDate:'1881'})]);assert.equal(scan(c,[1880]).rows[0].categories['population-statistics'].status,'missing');});
test('nearby event retained at actual date, distant events and future events absent',()=>{const c=fixture([1880]);rich(c,[claim('events-context',{kind:'event',date:'1878'})]);assert.equal(scan(c,[1880]).rows[0].categories['events-context'].records[0].actualTemporal.date,'1878');assert.equal(scan(c,[1880],{contextWindowYears:1}).rows[0].categories['events-context'].status,'missing');});
test('statistical geography mismatch requires review',()=>{const c=fixture();const f=claim('population-statistics',{kind:'observation',observationDate:'1878'});f.scope.relationship='different';rich(c,[f]);assert.equal(scan(c).rows[0].categories['population-statistics'].status,'historical-review');});
test('legacy census scope string alone cannot prove compatible cross-snapshot geography',()=>{const c=fixture();c.db.entities[0].population=[{value:100,asOf:'1877',scope:'Census district',sourceIds:['s']}];assert.equal(scan(c).rows[0].categories['population-statistics'].status,'historical-review');});
test('missing source provenance fails closed',()=>{const c=fixture();const f=claim();f.sourceIds=['unknown'];rich(c,[f]);assert.equal(scan(c).rows[0].categories.leadership.status,'historical-review');});
test('two simultaneous incompatible same-role leaders require review',()=>{const c=fixture();rich(c,[claim(),{...claim(),id:'second',value:'Other ruler'}]);assert.equal(scan(c).rows[0].categories.leadership.status,'historical-review');});
test('different dated entities in transition year remain raw mapping review',()=>{const c=fixture([1880]);c.db.entities.push({id:'successor'});c.db.mappings=[{mapId:'raw-a',entityId:'state',validUntil:'1880-06-01'},{mapId:'raw-a',entityId:'successor',validFrom:'1880-06-01'}];const r=scan(c,[1880]);assert.equal(r.rows.length,0);assert.ok(r.rawReview.some(x=>x.issues.includes('Competing dated entity mappings')));});
test('BCE chronology uses astronomical years and preserves exact-day exclusive endpoint',()=>{const c=fixture([-10,-5]);c.db.mappings.forEach(m=>{m.validFrom='-000020';m.validUntil='0000';});c.db.entities[0].names=[];rich(c,[claim('leadership',{kind:'interval',from:'-000012',until:'-000005-01-01'})]);const r=scan(c,[-10,-5]);assert.equal(r.rows[0].categories.leadership.status,'supported');assert.equal(r.rows[1].categories.leadership.status,'missing');});
test('imprecise start boundary partial; impossible dates rejected from coverage',()=>{const c=fixture();rich(c,[claim('leadership',{kind:'interval',from:'1878',until:'1888'}),{...claim(),id:'invalid',temporal:{kind:'event',date:'1878-02-30'}}]);const r=scan(c);assert.equal(r.rows[0].categories.leadership.status,'partial');assert.equal(r.errors.length,1);});
test('community and Antarctica excluded, unresolved classification explicit',()=>{const c=fixture();c.manifest.identities[0].classification.classification='community-people';c.manifest.identities.push({stableMapId:'antarctica',snapshotYears:[1878],classification:{classification:'political-polity'}});c.manifest.identities[1].classification.classification='unresolved';const r=scan(c);assert.equal(r.rows.length,0);assert.equal(r.metrics.excludedRawIdentities,2);assert.equal(r.rawReview.length,2);});
test('invalid/orphan mapping and existence not guessed',()=>{const c=fixture();c.db.mappings[0].entityId='missing';c.db.entities[0].existence={validFrom:'1881',validUntil:'1900'};const r=scan(c);assert.equal(r.rows.length,0);assert.ok(r.rawReview.some(x=>x.issues.includes('Broken entity mapping')));assert.ok(r.rawReview.some(x=>x.issues.includes('Mapping outside entity existence')));});
test('equivalent legacy and rich record counted once, untrusted input remains unchanged',()=>{const c=fixture();c.db.entities[0].leaders=[{value:'Ruler',role:'Head of state',validFrom:'1875',validUntil:'1888',sourceIds:['s']}];rich(c,[{...claim(),temporal:{...claim().temporal,certainty:'exact'}}]);const before=JSON.stringify(c);const r=scan(c);assert.equal(r.rows[0].categories.leadership.records.length,1);assert.equal(JSON.stringify(c),before);assert.deepEqual(r,scan(c));});
test('explicit sourced applicability decision reported separately',()=>{const c=fixture();rich(c,[]);c.rich.packages[0].investigation=[{category:'density',status:'not-applicable',rationale:'No meaningful territorial density for this institutional entity',consultedSourceIds:['s']}];assert.equal(scan(c).metrics.fieldCoverage.density.notApplicable,2);});
test('partial-year non-applicability cannot erase an entire snapshot gap',()=>{const c=fixture();rich(c,[]);c.rich.packages[0].period={from:'1878-06-01',until:'1879-01-01'};c.rich.packages[0].investigation=[{category:'density',status:'not-applicable',rationale:'Bounded decision only',consultedSourceIds:['s']}];assert.equal(scan(c).metrics.fieldCoverage.density.notApplicable,0);});
test('Important Figure relevance outside lifespan requires review and future activity does not leak',()=>{const c=fixture();const f={...claim('important-figures'),figure:{lifespan:{from:'1880',until:'1900'}}};rich(c,[f]);assert.equal(scan(c).rows[0].categories['important-figures'].status,'historical-review');f.temporal={kind:'interval',from:'1890',until:'1895'};assert.equal(scan(c).rows[0].categories['important-figures'].status,'missing');});
test('reports deterministic and duplicate snapshot configs rejected',()=>{const c=fixture(),r=scan(c),dir=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-snapshot-'));try{writeSnapshotReport(r,dir);const first=fs.readFileSync(path.join(dir,'snapshot-coverage.json'),'utf8');writeSnapshotReport(r,dir);assert.equal(fs.readFileSync(path.join(dir,'snapshot-coverage.json'),'utf8'),first);assert.throws(()=>scan(c,[1880,1880]),/Unique/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('bounded snapshot gaps bind generator context and queue counters',()=>{const c=fixture();c.productionFingerprint='context-hash';const r=scan(c,[1878,1880],{queue:[{status:'researching'},{status:'accepted'},{status:'accepted'}]});assert.equal(r.productionFingerprint,'context-hash');assert.ok(r.gaps.every(g=>['1878','1880'].includes(g.period.from)));assert.ok(r.gaps.find(g=>g.category==='leadership').mappings.length);assert.deepEqual(r.metrics.queueTotals,{researching:1,accepted:2});});
test('exact-snapshot legacy observation retains qualified scope; missing values do not crash',()=>{const c=fixture();c.db.entities[0].population=[{value:100,asOf:'1878',scope:'Island census, qualified geography',sourceIds:['s']}];c.db.entities[0].governments=[{validFrom:'1870',validUntil:'1900',sourceIds:['s']}];const r=scan(c);assert.equal(r.rows[0].categories['population-statistics'].status,'supported');assert.equal(r.rows[0].categories['political-institutional'].status,'historical-review');});
test('authoritative parser refuses partially unparsed config',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-config-'));try{fs.writeFileSync(path.join(dir,'app.js'),"const SNAPSHOTS = [{year:1880,file:'a.geojson'}, {year:other,file:'b.geojson'}];");assert.throws(()=>readSnapshotConfig(dir),/Unparsed/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
