import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import test from 'node:test';import assert from 'node:assert/strict';
import {fields,dateBounds,temporalBounds,sourceIndex,lookupSources,ingestCandidates,validateDossier,generateDossierJob,selectForYear,acceptDossier,integrateDossier,recoverDossierIntegration,fingerprint} from '../scripts/research-comprehensive.mjs';
import {digest,saveJSON,productionFiles} from '../scripts/research-common.mjs';
const interval=(from='1900',until='1909')=>({kind:'interval',from,until,certainty:'exact'});
function fixture(){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-dossier-v2-'));for(const file of productionFiles){fs.mkdirSync(path.dirname(path.join(directory,file)),{recursive:true});fs.writeFileSync(path.join(directory,file),file.endsWith('.json')?'{}':'// synthetic');}const db={entities:[{id:'example',validFrom:'1800',validUntil:'1960',flags:[]}],mappings:[{mapId:'map-example',entityId:'example'}]},registry={sources:[{id:'s1',url:'https://archive.example.org/record',title:'Synthetic archive',institution:'Test archive'}]};saveJSON(path.join(directory,'data/historical-entities.json'),db);saveJSON(path.join(directory,'data/historical-sources.json'),registry);const context={directory,db,registry},job=generateDossierJob('example',{from:'1900',until:'1909'},context);const claim={id:'claim-1',category:'capital',value:'Example seat',entityId:'example',temporal:interval(),scope:{id:'example-core',description:'Synthetic identical geographic scope',relationship:'same'},sourceIds:['s1'],evidence:[{sourceId:'s1',locator:'Test page1',note:'Synthetic test only',precision:'year',temporal:interval(),interpretation:'direct'}],status:'supported',risks:[],qualifications:[],origin:{kind:'new-research',reference:'synthetic'}};const pkg={schemaVersion:2,id:'synthetic-dossier',jobId:job.id,entityId:'example',mapIds:job.mapIds,worker:{id:'worker',assignmentType:'comprehensive-entity-period'},productionFingerprint:job.productionFingerprint,chronology:{calendar:'proleptic-gregorian',yearConvention:'astronomical'},period:job.period,claims:[claim],sources:[],investigation:fields.map(category=>({category,status:category==='capital'?'supported':'unresolved',rationale:'Synthetic fixture, no historical assertion',consultedSourceIds:['s1'],gaps:category==='capital'?[]:['Missing test evidence']})),conflicts:[],provenance:{createdAt:'2026-10-01',method:'Synthetic tests only',preservedPackageHashes:[]}};return {directory,context,job,pkg,cleanup:()=>fs.rmSync(directory,{recursive:true,force:true})};}
const run=fn=>{const f=fixture();try{fn(f);}finally{f.cleanup();}};
function receipt(f){const v=validateDossier(f.pkg,f.job,f.context);assert.deepEqual(v.errors,[]);return acceptDossier(f.pkg,f.job,f.context,{reviewer:'independent',bodyReviewed:true,rationale:'Synthetic independent review',packageHash:digest(f.pkg),reviewedIssues:v.review,decisions:Object.fromEntries(f.pkg.claims.map(c=>[c.id,'accepted']))});}
test('Strict comprehensive schema; optional ancient fields explicit',()=>run(f=>{assert.equal(validateDossier(f.pkg,f.job,f.context).valid,true);f.pkg.unrecognized='unsafe';assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Fourteen category investigations required; not just easy facts',()=>run(f=>{f.pkg.investigation.pop();assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Chronology supports BCE, zero, uncertain endpoints; impossible dates rejected',()=>{assert.equal(dateBounds('-003999').year,-3999);assert.equal(dateBounds('0000-02-29').year,0);assert.throws(()=>dateBounds('1900-02-29'));assert.throws(()=>temporalBounds(interval('1910','1900')));});
test('Claims must remain inside assigned period and entity envelope',()=>run(f=>{f.pkg.claims[0].temporal=interval('1899','1909');assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('No source or identity orphan',()=>run(f=>{f.pkg.claims[0].sourceIds=['missing'];f.pkg.mapIds=['unknown'];assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Year source cannot support invented day at either endpoint',()=>run(f=>{f.pkg.claims[0].temporal.until='1909-12-31';assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Population remains observation, with methodology and units',()=>run(f=>{const c=f.pkg.claims[0];c.category='population-statistics';c.value=120;c.metric='census';c.unit='persons';c.qualifications=['Census counts same scope'];c.temporal={kind:'observation',observationDate:'1907',certainty:'exact'};c.evidence[0].temporal=structuredClone(c.temporal);assert.equal(validateDossier(f.pkg,f.job,f.context).valid,true);c.temporal.observationDate='1908';assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Statistics cannot silently acquire validity interval',()=>run(f=>{f.pkg.claims[0].category='population-statistics';assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Selected-year retrieval excludes 1907 observation in1908 unless explicit context',()=>run(f=>{const c={...f.pkg.claims[0],temporal:{kind:'observation',observationDate:'1907',certainty:'exact'}};assert.equal(selectForYear([c],1908).length,0);const r=selectForYear([c],1908,{nearbyObservations:true})[0];assert.equal(r.actualTemporal.observationDate,'1907');assert.equal(r.requestedYear,1908);assert.equal(r.contextRequired,true);}));
test('BCE selected-year retrieval has no AD fallback',()=>run(f=>{const c={...f.pkg.claims[0],temporal:interval('-003999','-003990')};assert.equal(selectForYear([c],-3995).length,1);assert.equal(selectForYear([c],1900).length,0);}));
test('Source lookup reuses registry and deterministically ranks exact leads',()=>run(f=>{const i=sourceIndex(f.context,[{id:'old',entityId:'example',period:f.job.period,claims:f.pkg.claims}]);assert.equal(lookupSources(i,'archive')[0].source.id,'s1');assert.equal(i.preserved.length,1);}));
test('Bulk provider records remain candidates and unmapped records remain review',()=>run(f=>{const row={sourceIdentifier:'row1',entityId:'unknown',category:'capital',value:'candidate seat',temporal:interval(),scope:f.pkg.claims[0].scope,sourceIds:['s1'],qualifications:[]},provider={id:'dataset',url:'https://example.org/data',license:'CC0',retrievedAt:'2026-10-01'};const a=ingestCandidates([row],provider,f.context);assert.equal(a[0].productionTruth,false);assert.equal(a[0].mappingStatus,'historical-review');assert.throws(()=>ingestCandidates([row,row],provider,f.context));assert.throws(()=>ingestCandidates([row],{...provider,license:null},f.context));}));
test('Modern nationality or polygon succession cannot be accepted',()=>run(f=>{f.pkg.claims[0].risks=['geometry-succession','modern-nationality'];assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Important Figures must fit lifespan and explain actual association',()=>run(f=>{const c=f.pkg.claims[0];c.category='important-figures';c.figure={personId:'person-test',name:'Synthetic person',categories:['scientist'],lifespan:{from:'1850',until:'1905'},relationship:'Worked in example territory',activity:'Research',contribution:'Synthetic result'};assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);c.temporal=interval('1900','1904');assert.equal(validateDossier(f.pkg,f.job,f.context).valid,true);}));
test('Conflicting government forms route to review, cannot be waved through',()=>run(f=>{const a=f.pkg.claims[0];a.category='political-institutional';a.metric='government';f.pkg.claims.push({...structuredClone(a),id:'claim-2',value:'Contradictory form'});const v=validateDossier(f.pkg,f.job,f.context);assert.equal(v.valid,true);assert.ok(v.review.length);assert.throws(()=>receipt(f));}));
test('Duplicate meaningful claims cannot inflate throughput',()=>run(f=>{f.pkg.claims.push({...structuredClone(f.pkg.claims[0]),id:'duplicate'});assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Uncertainty and scope mismatch stay held; no cosmetic completeness',()=>run(f=>{f.pkg.claims[0].scope.relationship='different';const v=validateDossier(f.pkg,f.job,f.context);assert.equal(v.status,'historical-review');assert.throws(()=>receipt(f));}));
test('Density only derives compatible dated scope and units',()=>run(f=>{const base=f.pkg.claims[0],t={kind:'observation',observationDate:'1907',certainty:'exact'};f.pkg.claims=[['pop','population-statistics',100,'persons'],['area','area-statistics',10,'km2'],['density','density',10,'persons/km2']].map(([id,category,value,unit])=>({...structuredClone(base),id,category,value,unit,metric:'synthetic methodology',qualifications:['Synthetic comparable counts'],temporal:t,evidence:[{...base.evidence[0],temporal:t}]}));f.pkg.claims[2].derivation={populationClaimId:'pop',areaClaimId:'area',formula:'population / area'};assert.equal(validateDossier(f.pkg,f.job,f.context).valid,true);f.pkg.claims[1].scope.id='other-area';assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Research validation and acceptance cannot mutate production',()=>run(f=>{const before=fingerprint(f.directory);receipt(f);assert.equal(fingerprint(f.directory),before);}));
test('Serial integration uses exact receipt, atomic object and preserved legacy data',()=>run(f=>{const r=receipt(f),legacy=fs.readFileSync(path.join(f.directory,'data/historical-entities.json'),'utf8');assert.equal(integrateDossier(f.pkg,f.job,f.context,r).applied,false);const a=integrateDossier(f.pkg,f.job,f.context,r,{apply:true});assert.equal(a.acceptedClaims,1);assert.equal(JSON.parse(fs.readFileSync(path.join(f.directory,'data/comprehensive-dossiers.json'))).packages.length,1);assert.equal(fs.readFileSync(path.join(f.directory,'data/historical-entities.json'),'utf8'),legacy);assert.throws(()=>integrateDossier(f.pkg,f.job,f.context,r,{apply:true}));}));
test('Existing integration lock prevents parallel writes',()=>run(f=>{const r=receipt(f);fs.mkdirSync(path.join(f.directory,'research'),{recursive:true});fs.writeFileSync(path.join(f.directory,'research/.integration-state.lock'),'busy');assert.throws(()=>integrateDossier(f.pkg,f.job,f.context,r,{apply:true}));}));
test('Prepared journal recovery never overwrites external edits',()=>run(f=>{const p=path.join(f.directory,'research/comprehensive/integration-journal.json');saveJSON(p,{status:'prepared',before:null,after:'{}\n'});saveJSON(path.join(f.directory,'data/comprehensive-dossiers.json'),{external:true});assert.throws(()=>recoverDossierIntegration(f.directory));}));
test('Interrupted pre-write operation is recoverable without a half integration',()=>run(f=>{saveJSON(path.join(f.directory,'research/comprehensive/integration-journal.json'),{status:'prepared',before:null,after:'{}\n'});assert.equal(recoverDossierIntegration(f.directory),'not-applied');}));
import {initializeDossierQueue,transitionDossierQueue} from '../scripts/research-comprehensive-queue.mjs';
test('Recoverable comprehensive jobs prevent duplicate ownership and concurrent excess',()=>run(f=>{const file=path.join(f.directory,'queue.json');let q=initializeDossierQueue(file,[f.job,{...f.job,id:'second',period:{from:'1910',until:'1919'}}],{concurrency:1});q=transitionDossierQueue(q,'claim',{jobId:f.job.id,workerId:'worker'},f.context);assert.throws(()=>transitionDossierQueue(q,'claim',{jobId:'second',workerId:'other'},f.context));q=transitionDossierQueue(q,'recover',{jobId:f.job.id,actor:{role:'coordinator',id:'c'},interrupted:true,reason:'Recorded crash'},f.context);assert.equal(q.jobs[0].status,'queued');}));
test('Full package review distinguishes accepted and held claims without dropping evidence',()=>run(f=>{const file=path.join(f.directory,'queue.json');let q=initializeDossierQueue(file,[f.job]);const a={role:'coordinator',id:'c'};q=transitionDossierQueue(q,'claim',{jobId:f.job.id,workerId:'worker'},f.context);q=transitionDossierQueue(q,'submit',{jobId:f.job.id,workerId:'worker',package:f.pkg},f.context);q=transitionDossierQueue(q,'validate',{jobId:f.job.id,actor:a},f.context);q=transitionDossierQueue(q,'review',{jobId:f.job.id,actor:a,review:receipt(f).review},f.context);assert.equal(q.jobs[0].status,'accepted');assert.equal(q.jobs[0].acceptance.acceptedClaimIds.length,1);assert.throws(()=>acceptDossier(f.pkg,f.job,f.context,{...q.jobs[0].acceptance.review,reviewer:'worker'}));}));

test('Entity existence envelope is checked in actual registry structure',()=>run(f=>{delete f.context.db.entities[0].validFrom;delete f.context.db.entities[0].validUntil;f.context.db.entities[0].existence={validFrom:'1902',validUntil:'1908'};assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Conflicting sourced legacy office records stay held',()=>run(f=>{f.context.db.entities[0].capitals=[{value:'Different seat',validFrom:'1900',validUntil:'1909'}];const v=validateDossier(f.pkg,f.job,f.context);assert.ok(v.review.some(x=>x.startsWith('Conflicting legacy record')));assert.throws(()=>receipt(f));}));
test('Equivalent entity periods cannot be assigned twice under different IDs',()=>run(f=>{assert.throws(()=>initializeDossierQueue(path.join(f.directory,'q.json'),[f.job,{...f.job,id:'other-id'}]));}));
import {summarizePilot} from '../scripts/research-comprehensive-report.mjs';
import {preservedCandidateBundle} from '../scripts/research-comprehensive-candidates.mjs';
import {prepareReviewedIntegration,reuseCatalogue,integrateReviewedFiles} from '../scripts/research-scale.mjs';
test('Reviewed scale integration reuses exact evidence without widening decisions',()=>run(f=>{const before=digest(f.pkg),originalReview=receipt(f).review;const p=prepareReviewedIntegration(f.pkg,f.job,originalReview,f.context);assert.deepEqual(p.receipt.acceptedClaimIds,['claim-1']);assert.equal(digest(f.pkg),before);assert.equal(reuseCatalogue(f.context).lookupOrder[0],'production facts');assert.throws(()=>prepareReviewedIntegration({...f.pkg,id:'tampered'},f.job,originalReview,f.context));f.context.db.entities[0].capitals=[{...f.pkg.claims[0],validFrom:'1900',validUntil:'1909'}];const skipped=prepareReviewedIntegration(f.pkg,f.job,originalReview,f.context);assert.equal(skipped.receipt.acceptedClaimIds.length,0);assert.equal(Object.keys(skipped.skipped).length,1);}));
test('Scale integration recovers durable production write before ledger interruption',()=>run(f=>{saveJSON(path.join(f.directory,'development/coverage/manifest.json'),{});saveJSON(path.join(f.directory,'development/coverage/research-plan.json'),{});const p=path.join(f.directory,'package.json'),j=path.join(f.directory,'job.json'),r=path.join(f.directory,'review.json');saveJSON(p,f.pkg);saveJSON(j,f.job);saveJSON(r,receipt(f).review);assert.equal(integrateReviewedFiles(p,j,r,f.directory).integrated,1);const ledger=path.join(f.directory,'research/scale-01/integration-ledger.json');fs.unlinkSync(ledger);assert.equal(integrateReviewedFiles(p,j,r,f.directory).recovered,true);assert.equal(integrateReviewedFiles(p,j,r,f.directory).alreadyIntegrated,true);}));
test('Reporting distinguishes accepted new research from actual production integration',()=>run(f=>{const before=fingerprint(f.directory),r=summarizePilot([f.pkg],[{validation:validateDossier(f.pkg,f.job,f.context),receipt:receipt(f)}],f.context);assert.equal(r.totals.acceptedNew,1);assert.equal(r.production.newClaimsIntegrated,0);assert.equal(r.browserChecksPerformed,0);assert.equal(fingerprint(f.directory),before);assert.deepEqual(r,summarizePilot([f.pkg],[{validation:validateDossier(f.pkg,f.job,f.context),receipt:receipt(f)}],f.context));}));
test('Preserved bulk adapter excludes integrated work and retains candidate identifiers',()=>run(f=>{const c=f.pkg.claims[0],old={id:'old-package',entityId:'example',claims:[{...c,geographicScope:c.scope,cautions:[]}]};const q={jobs:[{status:'integrated',entityId:'other'}]},before=digest(old);const bundle=preservedCandidateBundle(q,[old]);assert.equal(bundle.records[0].sourceIdentifier,'old-package/claim-1');assert.equal(ingestCandidates(bundle.records,bundle.provider,f.context)[0].productionTruth,false);assert.equal(preservedCandidateBundle({jobs:[{status:'integrated',entityId:'example'}]},[old]).records.length,0);assert.equal(digest(old),before);}));

test('Scoped conflicts hold affected claims without blocking unrelated safe evidence',()=>run(f=>{const a=f.pkg.claims[0];f.pkg.claims.push({...structuredClone(a),id:'affected',category:'overview',value:'Contested contextual summary'});f.pkg.conflicts=[{description:'Two sources disagree',claimIds:['affected']}];const v=validateDossier(f.pkg,f.job,f.context);assert.equal(v.valid,true);const review={reviewer:'other',bodyReviewed:true,rationale:'Reviewed exact scoped conflict',packageHash:digest(f.pkg),reviewedIssues:v.review,decisions:{'claim-1':'accepted',affected:'held'}};assert.deepEqual(acceptDossier(f.pkg,f.job,f.context,review).acceptedClaimIds,['claim-1']);assert.throws(()=>acceptDossier(f.pkg,f.job,f.context,{...review,decisions:{'claim-1':'accepted',affected:'accepted'}}));f.pkg.conflicts[0].claimIds=['missing'];assert.equal(validateDossier(f.pkg,f.job,f.context).valid,false);}));
test('Previously integrated rich source records cannot be overwritten or aliased',()=>run(f=>{const s={id:'rich-source',title:'Archive record',institution:'Archive',url:'https://archive.example.org/rich',accessed:'2026-10-01',usage:'Synthetic evidence',kind:'institutional-historical'};saveJSON(path.join(f.directory,'data/comprehensive-dossiers.json'),{schemaVersion:2,packages:[{sources:[s],claims:[]}]});f.job.productionFingerprint=f.pkg.productionFingerprint=fingerprint(f.directory);f.pkg.sources=[s];assert.equal(validateDossier(f.pkg,f.job,f.context).valid,true);f.pkg.sources=[{...s,title:'Unsafe rewritten title'}];assert.ok(validateDossier(f.pkg,f.job,f.context).errors.some(e=>e.startsWith('No source overwrite')));f.pkg.sources=[{...s,id:'alias'}];assert.ok(validateDossier(f.pkg,f.job,f.context).errors.some(e=>e.startsWith('Reuse existing source ID')));assert.ok(lookupSources(sourceIndex(f.context),'rich')[0]);}));
