import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {digest,saveJSON,productionFiles} from '../scripts/research-common.mjs';
import {fields,generateDossierJob,validateDossier,acceptDossier,integrateDossier,fingerprint} from '../scripts/research-comprehensive.mjs';
import {mappingContent,validateMapping,assessCompatibility,rankMappingReviews} from '../scripts/research-crosswalk.mjs';
const base=()=>({id:'test-mapping',atlasEntityId:'historic',external:{dataset:'synthetic',id:'unit-1',name:'Historical statistical name'},class:'B',period:{from:'1900-01-01',until:'1910-01-01'},fields:['leadership'],territorial:{classification:'NEAR-EQUIVALENT',sourceScope:'Synthetic national statistical unit',atlasScope:'Historical entity scope',differences:'Documented naming difference only',materialDifference:false},rationale:'Synthetic documented historical continuity, never a production fact',evidence:[{sourceId:'s1',locator:'Synthetic historical identity record'}],worker:'mapper',continuityEstablished:true,competingEntity:false});
function reviewed(m){m.review={reviewer:'independent',decision:'accepted',contentHash:digest(mappingContent(m))};return m;}
const claim=(category='leadership')=>({entityId:'historic',category,temporal:{kind:'interval',from:'1901-01-01',until:'1902-01-01'},scope:{description:'Synthetic scope'},qualifications:[]});
test('documented A exact historical match may map automatically',()=>{const m=base();m.class='A';m.territorial.classification='EXACT';assert.deepEqual(validateMapping(m),[]);assert.equal(assessCompatibility(m,claim()).accepted,true);});
test('B naming/regime differences require independent bound review',()=>{assert.equal(assessCompatibility(base(),claim()).accepted,false);assert.equal(assessCompatibility(reviewed(base()),claim()).accepted,true);});
test('B cannot use name similarity with unclear continuity or competing entity',()=>{for(const change of [{continuityEstablished:false},{competingEntity:true}])assert.equal(assessCompatibility(reviewed({...base(),...change}),claim()).accepted,false);});
test('certificate tampering and self-review fail closed',()=>{let m=reviewed(base());m.rationale+='changed';assert.ok(validateMapping(m).length);m=reviewed(base());m.review.reviewer='mapper';assert.ok(validateMapping(m).length);});
test('C permits only explicitly qualified statistical observations',()=>{const m=base();m.class='C';m.fields=['population-statistics'];m.territorial.classification='QUALIFIED-COMPATIBLE';reviewed(m);const c={...claim('population-statistics'),temporal:{kind:'observation',observationDate:'1905'},qualifications:['Original scope: '+m.territorial.sourceScope]};assert.equal(assessCompatibility(m,c).accepted,true);assert.equal(assessCompatibility(m,{...c,qualifications:[]}).accepted,false);assert.equal(assessCompatibility(m,claim()).accepted,false);});
test('C never grants leader, capital, currency, flag or sovereignty permission',()=>{for(const f of ['leadership','capital','currency','historical-flag','relationships','identity','political-institutional']){const m=base();m.class='C';m.fields=[f];reviewed(m);assert.ok(validateMapping(m).length);}});
test('C density additionally requires explicit mutually compatible inputs',()=>{let m=base();m.class='C';m.fields=['density'];reviewed(m);const c={...claim('density'),temporal:{kind:'observation',observationDate:'1905'},qualifications:[m.territorial.sourceScope]};assert.equal(assessCompatibility(m,c).accepted,false);m.mutualScopeEvidence='Synthetic explicit same input scope';reviewed(m);assert.equal(assessCompatibility(m,c).accepted,true);});
test('material mismatch and D never flow automatically',()=>{let m=reviewed(base());m.class='D';assert.equal(assessCompatibility(m,claim()).accepted,false);m=base();m.territorial.materialDifference=true;assert.ok(validateMapping(reviewed(m)).length);});
test('mapping intervals prevent snapshot and observation leakage',()=>{const m=reviewed(base());assert.equal(assessCompatibility(m,claim(),{requestedYear:1911}).accepted,false);assert.equal(assessCompatibility(m,{...claim(),temporal:{kind:'interval',from:'1899-01-01',until:'1901-01-01'}}).accepted,false);});
test('time-varying mappings remain independent, not a lifetime external-ID assumption',()=>{let a=base(),b=base();a.period={from:'1800-01-01',until:'1867-01-01'};b.period={from:'1867-01-01',until:'1918-01-01'};b.external.id='unit-2';reviewed(a);reviewed(b);const c={...claim(),temporal:{kind:'interval',from:'1900-01-01',until:'1901-01-01'}};assert.equal(assessCompatibility(a,c).accepted,false);assert.equal(assessCompatibility(b,c).accepted,true);});
test('ranking favours downstream supported slots per mapping review effort',()=>assert.deepEqual(rankMappingReviews([{id:'one',expectedNewSlots:1,reviewEffort:1},{id:'bulk',expectedNewSlots:20,reviewEffort:2}]).map(x=>x.id),['bulk','one']));
test('proxy cannot be relabelled A/exact',()=>{let m=base();m.class='A';assert.ok(validateMapping(m).length);});
test('qualified C observation passes controlled intake without pre-integration mutation',()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-crosswalk-'));
 try{
  for(const p of productionFiles){fs.mkdirSync(path.dirname(path.join(directory,p)),{recursive:true});fs.writeFileSync(path.join(directory,p),p.endsWith('.json')?'{}':'// synthetic');}
  const db={entities:[{id:'historic',validFrom:'1800',validUntil:'1960',flags:[]}],mappings:[{mapId:'historic-map',entityId:'historic'}]},registry={sources:[{id:'s1',title:'Synthetic source',institution:'Synthetic institute',url:'https://example.org/synthetic'}]};
  saveJSON(path.join(directory,'data/historical-entities.json'),db);saveJSON(path.join(directory,'data/historical-sources.json'),registry);
  const context={directory,db,registry},job=generateDossierJob('historic',{from:'1900',until:'1909'},context),m=base();m.class='C';m.fields=['population-statistics'];m.territorial.classification='QUALIFIED-COMPATIBLE';reviewed(m);
  const temporal={kind:'observation',observationDate:'1905',certainty:'exact'},c={id:'synthetic-c',entityId:'historic',category:'population-statistics',value:1000,unit:'persons',metric:'Synthetic source observation',temporal,compatibility:m,scope:{id:'statistical-proxy',description:m.territorial.sourceScope,relationship:'compatible'},sourceIds:['s1'],evidence:[{sourceId:'s1',locator:'Synthetic table',note:'Synthetic only, no production fact',precision:'year',temporal,interpretation:'direct'}],status:'supported',risks:[],qualifications:[m.territorial.sourceScope],origin:{kind:'bulk-candidate',reference:'synthetic'}};
  const pkg={schemaVersion:2,id:'synthetic-c-pkg',jobId:job.id,entityId:'historic',mapIds:job.mapIds,worker:{id:'mapper',assignmentType:'comprehensive-entity-period'},productionFingerprint:job.productionFingerprint,chronology:{calendar:'proleptic-gregorian',yearConvention:'astronomical'},period:job.period,claims:[c],sources:[],investigation:fields.map(category=>({category,status:'partial',rationale:'Synthetic test scope',consultedSourceIds:['s1'],gaps:['Synthetic test']})),conflicts:[],provenance:{createdAt:'2026-10-03',method:'Synthetic test only',preservedPackageHashes:[]}};
  const before=fingerprint(directory),v=validateDossier(pkg,job,context);assert.equal(v.valid,true,JSON.stringify(v.errors));assert.ok(!v.review.some(r=>r.includes('geographic comparability')));
  const r={reviewer:'independent',bodyReviewed:true,rationale:'Synthetic source and mapping reviewed',packageHash:digest(pkg),reviewedIssues:v.review,decisions:{'synthetic-c':'accepted'}},receipt=acceptDossier(pkg,job,context,r);
  assert.equal(integrateDossier(pkg,job,context,receipt).applied,false);assert.equal(fingerprint(directory),before);
  const broken=structuredClone(pkg);broken.claims[0].compatibility.fields=['capital'];assert.equal(validateDossier(broken,job,context).valid,false);
  broken.claims[0].compatibility=structuredClone(m);broken.claims[0].compatibility.review.contentHash='0'.repeat(64);assert.equal(validateDossier(broken,job,context).valid,false);
 }finally{assert.equal(path.dirname(directory),os.tmpdir());assert.ok(path.basename(directory).startsWith('atlas-crosswalk-'));fs.rmSync(directory,{recursive:true,force:true});}
});
