import test from 'node:test';
import assert from 'node:assert/strict';
import {auditApplicability,regionalAudit,applicabilityPolicy} from '../scripts/research-applicability.mjs';
import {digest,productionFingerprint,readContext,readJSON} from '../scripts/research-common.mjs';
function matrix(){return{productionFingerprint:'synthetic',rows:[{entityId:'synthetic',name:'Synthetic polity',snapshotYear:1900,mapIds:['raw'],categories:Object.fromEntries(Object.keys(applicabilityPolicy).map(c=>[c,{status:'missing',records:[],issues:[]}]))}],unresolvedRawIdentities:[],errors:[]};}
function resolution(status){const r={id:'synthetic-resolution',entityId:'synthetic',category:'density',period:{from:'1899-01-01',until:'1901-01-01'},status,rationale:'Synthetic evidence only',evidenceNote:'Synthetic document',scope:'Synthetic territory',sourceIds:['s'],worker:'worker'};r.review={reviewer:'independent',decision:'accepted',contentHash:digest(r)};return r;}
const context={db:{entities:[{id:'synthetic'}]},registry:{sources:[{id:'s',title:'Synthetic source',institution:'Synthetic archive',url:'https://example.org/test'}]}};
test('all15 categories audited; empty conditional/enrichment/derived fields never become N/A',()=>{const r=auditApplicability(matrix());assert.equal(r.totals.total,15);assert.equal(r.totals.applicableDenominator,15);assert.equal(r.totals.legitimateNonApplicable,0);assert.equal(r.totals.rawUnresolved,15);assert.equal(Object.keys(r.byCategory).length,15);});
test('partial and held do not count as coverage or resolution',()=>{const m=matrix();m.rows[0].categories.capital.status='partial';m.rows[0].categories.leadership.status='held';const r=auditApplicability(m);assert.equal(r.totals.resolvedSlots,0);assert.equal(r.core.genuinelyMissingCoreSlots,2);assert.equal(r.core.otherUnresolvedCoreSlots,2);});
test('proven N/A changes only applicable denominator and resolution; raw comparison survives',()=>{const m=matrix(),r=resolution('not-applicable');m.rows[0].categories.density={status:r.status,resolutionId:r.id,records:[],issues:[]};const a=auditApplicability(m,{context,resolutions:[r]});assert.equal(a.totals.total,15);assert.equal(a.totals.applicableDenominator,14);assert.equal(a.totals.resolvedSlots,1);assert.equal(a.totals.rawSupported,0);});
test('uncertain/unavailable need independent evidence and do not manufacture facts',()=>{for(const status of ['uncertain','known-unavailable']){const m=matrix(),r=resolution(status);m.rows[0].categories.density={status,resolutionId:r.id,records:[],issues:[]};assert.throws(()=>auditApplicability(m),/evidence ledger/);const a=auditApplicability(m,{context,resolutions:[r]});assert.equal(a.totals.applicableDenominator,15);assert.equal(a.totals.rawSupported,0);assert.equal(a.totals.resolvedSlots,1);}});
test('transition-year or unrelated resolution cannot remove a whole snapshot',()=>{const m=matrix(),r=resolution('not-applicable');r.period.from='1900-06-01';r.review.contentHash=digest(Object.fromEntries(Object.entries(r).filter(([k])=>k!=='review')));m.rows[0].categories.density={status:r.status,resolutionId:r.id,records:[],issues:[]};assert.throws(()=>auditApplicability(m,{context,resolutions:[r]}),/whole-snapshot/);});
test('missing data with a recorded consultation is not labelled unresearched',()=>{const p={id:'attempt',entityId:'synthetic',period:{from:'1899-01-01',until:'1901-01-01'},investigation:[{category:'capital',status:'unresolved',consultedSourceIds:['s']}]},r=auditApplicability(matrix(),{rich:{packages:[p]}});assert.equal(r.totals.missingWithRecordedInvestigation,1);assert.equal(r.totals.missingWithoutRecordedInvestigation,14);assert.equal(r.totals.resolvedSlots,0);});
test('MajorEvents/Figures stay enrichment, never missing core quotas',()=>{const m=matrix();for(const c of ['identity','political-institutional','leadership','capital'])m.rows[0].categories[c].status='supported';const r=auditApplicability(m);assert.equal(r.core.rawUnresolved,0);assert.equal(r.enrichment['important-figures'].rawUnresolved,1);assert.equal(r.enrichment['events-context'].rawUnresolved,1);});
test('regional rank excludes held/partial from straightforward missing core and detects overlap',()=>{const r=auditApplicability(matrix()),defs=[{batch:'02',title:'B',rawMapIdentities:['raw']},{batch:'01',title:'A',rawMapIdentities:['raw']}],a=regionalAudit(r,defs);assert.deepEqual(a.batches.map(b=>b.batch),['01','02']);assert.equal(a.overlappingDossiers.length,1);assert.deepEqual(a,regionalAudit(r,defs));});
test('real audit is deterministic and preserves every production byte',()=>{const before=productionFingerprint(),m=readJSON('research/completion-01/reports/completion.json'),options={rich:readJSON('data/comprehensive-dossiers.json'),context:readContext()},a=auditApplicability(m,options);assert.equal(a.totals.total,15840);assert.equal(a.totals.rawSupported,7257);assert.deepEqual(a,auditApplicability(m,options));assert.equal(before,productionFingerprint());});
