import fs from 'node:fs';
import {readContext,readJSON,digest,saveJSON} from '../../../scripts/research-common.mjs';
const dir='research/regional-15/kingdoms-liberia-guinea',ctx=readContext();
const known=[...ctx.registry.sources,...readJSON('data/comprehensive-dossiers.json').packages.flatMap(p=>p.sources)],sources=[];
function source(id,title,institution,url){const s=known.find(s=>s.url===url)||{id,title,institution,url,accessed:'2026-10-02',kind:'historical-institutional-evidence',usage:'Attributed factual paraphrases only; no original images or full copyrighted text redistributed.'};if(!sources.some(x=>x.id===s.id))sources.push(s);return s.id;}
const asante=source('b15-asante-state-core','The precolonial period: Asante','Library of Congress, Federal Research Division; HTML transcription','https://countrystudies.us/ghana/5.htm');
const british=source('r15-ghana-british-contact','Early European contact and the slave trade','Library of Congress, Federal Research Division; HTML transcription','https://countrystudies.us/ghana/7.htm');
const colonial=source('b15-gold-coast-colonial-core','The colonial era: British rule of the Gold Coast','Library of Congress, Federal Research Division; HTML transcription','https://countrystudies.us/ghana/8.htm');
const mensa=source('r15-mensa-bonsu-wilks','Mensa Bonsu, by Ivor Wilks','Encyclopaedia Africana Dictionary of African Biography / Encyclopaedia Africana Project','https://encyclopaediaafricana.com/mensa-bonsu/');
const sokoto=source('b16-sokoto-history','Usman dan Fodio and the Sokoto Caliphate','Library of Congress, Federal Research Division; HTML transcription','https://countrystudies.us/nigeria/9.htm');
const manuscript=source('r15-dan-fodio-manuscript','The Authoritative Source for Religious Scholars: catalogue record','Library of Congress / Mamma Haidara Commemorative Library','https://www.loc.gov/item/2021667264/');
const liberia=source('r15-liberia-founding-history','Founding of Liberia, 1847','United States Department of State, Office of the Historian','https://history.state.gov/milestones/1830-1860/liberia');
const frus=source('r15-liberia-frus-1930-335','Foreign Relations of the United States, 1930, Volume III, document 335','United States Department of State, Office of the Historian','https://history.state.gov/historicaldocuments/frus1930v03/d335');
const guinea=source('r15-cgd-bissau-agency-history','Filiais e agências do BNU — Agência do BNU em Bissau, Nuno Fernandes Carvalho, October 2015','Caixa Geral de Depósitos, Património Histórico','https://www.cgd.pt/institucional/patrimonio-historico-cgd/patrimonio-em-destaque/pages/agencia-bnu-em-bissau.aspx');
const claims=[];
function add(id,e,category,value,t,sid,locator,note,extra={}){const precision=(t.from||t.date||t.observationDate).length===4&&(t.until||'').length<=4?'year':(t.date||t.from).length===7?'month':'day';const c={id:'r15-root-'+id,entityId:e,category,value,temporal:{...t,certainty:'exact'},scope:{id:e+'-r15-'+category+'-'+id,description:'Explicit historical institution, office, affiliation or event of the named entity; not an inference about polygon sovereignty or statistical territory.',relationship:'same'},sourceIds:[sid],evidence:[{sourceId:sid,locator,note,precision,temporal:{...t,certainty:'exact'},interpretation:'direct'}],status:'supported',risks:[],qualifications:['Year-precision interval cutoffs are bounded research coverage, not newly asserted historical transition dates. Coarse boundary years remain partial under the existing scanner.'],origin:{kind:'new-research',reference:sid},...extra};claims.push(c);return c;}
const interval=(from,until)=>({kind:'interval',from,until}),event=date=>({kind:'event',date});
add('liberia-us-relations','liberia-presidential-constitutional-core','relationships','Diplomatic relations with the United States',interval('1878','1960'),liberia,'Founding of Liberia: final paragraph','The official history dates diplomatic relations to 1862 and states that strong ties continued into the 1990s; this record is restricted to the atlas framework.',{relatedEntityIds:['united-states'],qualifications:['Diplomatic relationship, not United States sovereignty over Liberia.','No assertion of identical diplomatic staffing, financial support or agreement throughout the interval.','Coarse research endpoint years remain partial; earlier or later events are not back-projected.']});
add('liberia-commission-report','liberia-presidential-constitutional-core','events-context','An international commission submitted its report on slavery and forced labour to the Liberian government.',event('1930-09-08'),frus,'Document 335, paragraphs 1–2','The contemporary memorandum explicitly dates submission to 8 September 1930.',{qualifications:['The commission included American, League of Nations-nominated and Liberian members. Findings are attributed to the commission; submission is not evidence that the abuses immediately ceased.']});
add('liberia-reform-acceptance','liberia-presidential-constitutional-core','events-context','The Liberian president notified the United States that the government accepted the international commission’s recommendations.',event('1930-09-30'),frus,'Document 335, paragraph beginning On September 30','The memorandum records the notification on 30 September and distinguishes promises from implemented reforms.',{qualifications:['The same memorandum reports that definite implementation plans had not yet been received. Acceptance must not be represented as completed abolition or implementation.']});
add('asante-early-capital','asante-early-nineteenth-confederacy-core','capital','Kumasi',interval('1800','1816'),asante,'Asante section: founding under Osei Tutu and capital Kumasi','The country study identifies Kumasi as the capital of the Asante confederacy; the companion colonial history traces the royal capital through the nineteenth century.',{role:'Royal capital'});
add('asante-late-capital','asante-late-nineteenth-royal-core','capital','Kumasi',interval('1878','1881'),mensa,'Mensa Bonsu: reconstruction; overthrow and return to the capital','The biography places the ruler and royal capital at Kumase throughout his reign. Historical spelling Kumase is retained in the locator; existing atlas spelling is Kumasi.',{role:'Royal capital'});
add('asante-mensa-bonsu','asante-late-nineteenth-royal-core','leadership','Mensa Bonsu',interval('1878','1881'),mensa,'Opening paragraph; destoolment on 8 March 1883','Ivor Wilks dates the reign to 1874–1883. The claim covers only the existing 1878–1880 atlas framework, without inventing an accession day.',{role:'Asantehene'});
add('asante-domankama','asante-late-nineteenth-royal-core','events-context','Members of the Domankama movement attempted to assassinate Mensa Bonsu; he ordered a purge of the movement.',event('1880'),mensa,'Paragraph beginning A more serious threat','The biography explicitly places the attempted assassination early in 1880; month/day are not supplied.',{qualifications:['Actual event year retained. No modern nationality or inferred successor-state relationship.']});
add('asante-1814-invasion','asante-early-nineteenth-confederacy-core','events-context','Asante forces invaded the coast in 1814 amid conflict over European trading access.',event('1814'),british,'Paragraph describing the Asante invasions of 1807, 1811 and 1814','The country study identifies the dated invasion; the 1815 snapshot may display this as explicitly dated prior-year context.',{qualifications:['1814 event, not an event asserted to have occurred in 1815. Existing five-year contextual window applies; no future event leaks into 1800.']});
add('asante-1900-rebellion','asante-1900-resident-framework-core','events-context','Asante rebelled against British control in 1900.',event('1900'),british,'Closing paragraph: 1896 expedition, protectorate, 1900 rebellion','The source distinguishes the 1900 rebellion from defeat in 1901 and annexation in 1902.',{qualifications:['Defeat in 1901 and annexation in 1902 are later events and are not represented as the 1900 framework.']});
add('asante-resident-seat','asante-1900-resident-framework-core','capital','Kumasi',interval('1900','1901'),colonial,'Resident commissioner paragraph','The country study explicitly identifies Kumasi as the centre from which Asante states were administered after the ruler and council were exiled.',{role:'Colonial administrative centre',qualifications:['Administrative centre under the resident arrangement; not an assertion of an independent royal government in 1900.','Year-level editorial bounds remain partial rather than fabricated full-year precision.']});
add('sokoto-late-capitals','sokoto-late-nineteenth-caliphate-core','capital','Sokoto; Gwandu for the western emirates',interval('1877','1901'),sokoto,'Twin capital at Gwandu; eastern and western emirates; capital district Sokoto','The country study describes the principal caliph at Sokoto and the western administrative capital at Gwandu. This conservative late-century interval precedes British conquest and does not substitute modern Nigerian capitals.',{role:'Principal and western administrative capitals',qualifications:['Sokoto retained primacy; Gwandu administered the western division. The centres are not flattened into identical roles.','No territorial geometry or statistical scope is inferred.']});
const figure=add('dan-fodio-1815','sokoto-late-nineteenth-caliphate-core','important-figures','Usman dan Fodio — Islamic scholar and reformer associated with the founding of the Sokoto caliphate',interval('1811','1816'),sokoto,'Radical mallams; jihad beginning in Gobir in 1804; broad religious and political impact','The country study establishes his religious reform movement and historical influence, independently of routine officeholding. The Library of Congress identifies him as the author of a surviving religious manuscript and dates his lifespan.',{figure:{personId:'usman-dan-fodio',name:'Usman dan Fodio',categories:['religious reform','intellectual history'],lifespan:{from:'1754',until:'1817'},relationship:'Scholar and reformer whose movement founded the Sokoto caliphate; not a back-projected modern Nigerian nationality.',activity:'Living founder and religious intellectual relevant to the caliphate in 1815; no assertion of a particular newly published work in that year.',contribution:'Islamic reformist scholarship and a movement with major political and religious consequences across the savanna and Sahel.'},qualifications:['His significance rests on religious scholarship, reform and documented broad influence, not merely officeholding.','The manuscript catalogue does not establish a precise composition date; no work is asserted to have appeared by 1815 solely from its catalogue date range.','No disputed date of transfer of administrative power to Muhammad Bello is resolved here.']});
figure.sourceIds.push(manuscript);figure.evidence.push({sourceId:manuscript,locator:'Title, Names, Summary and Rights & Access metadata',note:'Catalogue identifies Usuman dan Fodio (1754–1817) as author of a work concerning the authority of Islamic scholars. The broad catalogue publication range is not a dated publication event.',precision:'year',temporal:interval('1754','1817'),interpretation:'direct'});
add('guinea-bolama-capital','portuguese-guinea-separate-colonial-core','capital','Bolama',interval('1880','1941'),guinea,'Pages 1–2 and 11: Bolama first capital; Bissau capital transfer in 1941','The archival account dates separation from Cape Verde to 18 March 1879 and identifies Bolama as the first capital until the 1941 transfer. Only the existing colony framework is covered.',{role:'Colonial capital',qualifications:['Not the modern Guinea-Bissau capital projected backwards. Capital transition year 1941 is retained at year precision; 1880 remains a partial editorial boundary under scanner policy.']});
add('guinea-1913-campaigns','portuguese-guinea-separate-colonial-core','events-context','Portuguese colonial military campaigns led by João Teixeira Pinto began in March 1913 and continued into July 1915.',event('1913-03'),guinea,'Page 2: campaigns from March 1913 to July 1915','The archival history gives the campaign interval; the event record stores its actual starting month and explicitly preserves the subsequent duration.',{qualifications:['Selected 1914 snapshot receives dated 1913 context under existing rules; the start is not relabelled as 1914.','Military campaigns against local communities do not establish that the whole mapped colony had uniform effective sovereignty.']});
saveJSON(dir+'/cohort.json',{id:'regional15-kingdoms-liberia-portuguese-guinea',worker:'regional15-coordinator-research',sources,claims});
saveJSON(dir+'/held.json',[
 {entityIds:['kong-early-nineteenth-state-core','kong-late-nineteenth-state-core'],categories:['capital','leadership','currency','population-statistics','important-figures','events-context'],reason:'Existing Getty institutional identity evidence does not supply safely dated requested-year facts for these categories. Source packet remains bounded; no modern Côte d’Ivoire substitution.'},
 {entityIds:['portuguese-guinea-cape-verde-core'],category:'capital',reason:'Praia is identified as the Cape Verde governor’s seat, but the reviewed packet does not establish its applicability throughout every early atlas year or equate it with a local Guinea capital.'},
 {entityIds:['portuguese-guinea-separate-colonial-core','portuguese-guinea-1960-overseas-core'],categories:['currency','economy'],reason:'Archive mentions escudo amounts and later banknotes but does not establish a complete dated currency regime. Qualitative banking context is not a numeric economy observation; no schema workaround.'},
 {entityIds:['sokoto-late-nineteenth-caliphate-core'],category:'leadership',reason:'Accounts distinguish succession on death in 1817 from earlier administrative responsibilities of Muhammad Bello; no disputed office interval forced through.'},
 {entityIds:['asante-early-nineteenth-confederacy-core'],category:'leadership',reason:'No sufficiently bounded accession/office evidence established in the limited source packet. Older reign-table exceptions deferred.'}
]);
console.log(JSON.stringify({claims:claims.length,sources:sources.length}));
