import fs from 'node:fs';
import {readContext,digest} from '../../../scripts/research-common.mjs';
const dir='research/regional-01/nordic';fs.mkdirSync(dir,{recursive:true});
const known=[...readContext().registry.sources,...JSON.parse(fs.readFileSync('data/comprehensive-dossiers.json')).packages.flatMap(p=>p.sources)];
const sources=[];function source(id,title,institution,url,note){const old=known.find(s=>s.url===url);if(old){sources.push(old);return old.id;}sources.push({id,title,institution,url,accessed:'2026-10-02',kind:'institutional-history',usage:'Individual factual paraphrases only; no images or full copyrighted source copied.'});return id;}
const dk=source('r01-nordic-danish-coins','Historical coins','Danmarks Nationalbank','https://www.nationalbanken.dk/en/what-we-do/notes-and-coins/historical-coins');
const no=source('r01-nordic-norges-history','History of Norges Bank','Norges Bank','https://www.norges-bank.no/en/topics/about/History/history-of-norges-bank/');
const se=source('r01-nordic-riksdag-history','From things and assemblies to the Riksdag of today','Sveriges riksdag','https://www.riksdagen.se/en/how-the-riksdag-works/the-history-of-the-riksdag/from-things-and-assemblies-to-the-riksdag-of-today/');
const ice=source('r01-nordic-althingi-history','Althingi: Parliament of Iceland, 2018','Althingi','https://www.althingi.is/pdf/Althingi2018_enska.pdf');
const bohr=source('r01-nordic-bohr','Niels Bohr: Biographical','Nobel Foundation / Nobel Lectures, Physics 1922–1941, Elsevier 1965','https://www.nobelprize.org/prizes/physics/1922/bohr/biographical/');
const und=source('r01-nordic-undset','Sigrid Undset: Biographical','Nobel Foundation / Nobel Lectures, Literature 1901–1967, Elsevier 1969','https://www.nobelprize.org/prizes/literature/1928/undset/biographical/');
const selma=source('r01-nordic-lagerlof','Selma Lagerlöf: Ledamotsregistret','Svenska Akademien','https://www.svenskaakademien.se/svenska-akademien/ledamotsregister/selma-lagerl%C3%B6f');
const aalto=source('r01-nordic-aalto','Alvar Aalto’s life','Alvar Aalto Foundation','https://www.alvaraalto.fi/en/alvar-aalto-foundation/alvar-aaltos-life/');
const claims=[];const interval=(from,until)=>({kind:'interval',from,until,certainty:'exact'});
function add(entityId,category,value,temporal,sid,note,extra={}){const id='r01-nordic-'+digest({entityId,category,value,temporal}).slice(0,20);claims.push({id,entityId,category,value,temporal,scope:{id:entityId+'-nordic-'+category,description:'Named historical polity institutions or explicitly associated activity; no geometry-inferred sovereignty or statistical scope.',relationship:'same'},sourceIds:[sid],evidence:[{sourceId:sid,locator:note, note:'Original institutional source supports this bounded fact. Dates preserve source precision; interval restricted to the atlas window.',precision:temporal.date?.length>4?'day':'year',temporal,interpretation:'direct'}],status:'supported',risks:[],qualifications:[],origin:{kind:'new-research',reference:sid},...extra});}
add('denmark-post-kiel','currency','Rigsbankdaler',interval('1815','1815'),dk,'Historical coin series: 1813 reform introduces rigsbankdaler; currency still named rigsbankdaler when Rigsbank became Nationalbank in 1818. Bounded 1815 observation avoids later rename ambiguity.');
add('sweden-norway-union','currency','Swedish krona and Norwegian krone — separate national units in the Scandinavian Monetary Union',interval('1876','1904'),no,'1875 section: Norwegian krone divided into 100 øre; other member coins legal tender on same basis as domestic coins; monetary union functions until 1914. Distinct national currencies within political union, not one fictional union-issued currency.',{qualifications:['Swedish and Norwegian national monetary units retained; no assertion of one union central bank or currency issuer.']});
add('sweden-kingdom','political-institutional','The 1809 Instrument of Government remained the constitutional framework, with fundamental amendments, until its replacement in 1974.',interval('1919','1960'),se,'History section 1809: Instrument introduced separation of powers; with fundamental changes it was not replaced until 1974.',{qualifications:['Constitutional continuity does not imply unchanged royal powers, franchise, parliamentary practice or constitutional text across this interval.']});
function event(e,value,date,sid,note){add(e,'events-context',value,{kind:'event',date,certainty:'exact'},sid,note);}
event('norway-constitutional-kingdom','Norges Bank suspended gold redemption on 19 March 1920 amid inflation and a crisis of confidence in the krone.','1920-03-19',no,'1920 section specifies suspension on 19 March and economic circumstances.');
event('norway-constitutional-kingdom','A currency reform was implemented from 8 to 22 September 1945 to withdraw excessive notes and limit inflation.','1945-09',no,'1940–45 section specifies reform 8–22 September 1945. Event uses month precision, not an invented single-day date.');
event('iceland-sovereign','Iceland established its Supreme Court in 1920.','1920',ice,'Page 8: sovereignty in 1918 and foundation of Supreme Court in 1920 brought judicial, executive and legislative powers into Icelandic hands.');
event('iceland-sovereign','Althingi marked its millennium with a ceremonial meeting at Thingvellir in 1930.','1930',ice,'Page 24: exceptional ceremonial parliamentary meetings at Thingvellir include 1930, millennium of Althingi.');
function figure(e,sid,person,name,from,until,life,categories,relationship,activity,contribution,note){add(e,'important-figures',name+' — '+activity,interval(from,until),sid,note,{scope:{id:e+'-'+person+'-institutional-activity',description:relationship,relationship:'same'},figure:{personId:person,name,categories,lifespan:{from:life[0],until:life[1]},relationship,activity,contribution},qualifications:['Territorial association rests on sourced institutional activity or residence, not birthplace or modern nationality. Earlier works are explicit context, not re-dated to the selected snapshot.']});}
figure('denmark-post-kiel',bohr,'niels-bohr','Niels Bohr','1917','1938',['1885-10-07','1962-11-18'],['scientist','physicist'],'Professor at Copenhagen University from 1916; head of its Institute for Theoretical Physics from 1920.','Copenhagen-based theoretical physicist','Atomic structure and quantum-theory research.','Nobel biography: Copenhagen professorship 1916, institute head 1920 until death 1962; atom model developed in 1913. Manchester appointment 1914–1916 excluded.');
figure('denmark-post-kiel',bohr,'niels-bohr','Niels Bohr','1960','1960',['1885-10-07','1962-11-18'],['scientist','physicist'],'Head of Copenhagen University’s Institute for Theoretical Physics until death in 1962; institutional association rather than uninterrupted physical residence.','Theoretical physicist heading the Copenhagen institute','Atomic structure and quantum-theory research.','Nobel biography: institute leadership since 1920 until death 1962; claim bounded to 1960, no wartime residence asserted.');
figure('norway-constitutional-kingdom',und,'sigrid-undset','Sigrid Undset','1921','1939',['1882','1949'],['writer','literary'],'Resident writer in Lillehammer from 1919 until wartime exile; 1940–1945 excluded.','Lillehammer-based novelist','Historical novels of medieval Scandinavian life and later contemporary fiction.','Nobel autobiography: since 1919 lived in Lillehammer; biography lists novels 1929,1930,1932,1936,1939 and wartime emigration. Award significance 1928 contextual only.');
figure('sweden-kingdom',selma,'selma-lagerlof','Selma Lagerlöf','1909','1939',['1858-11-20','1940-03-16'],['writer','literary'],'Resident at Mårbacka from 1909 until death; elected Swedish Academy 1914.','Mårbacka-based novelist','Gösta Berlings saga, Nils Holgersson and novels rooted in Swedish settings.','Academy register: resident Mårbacka from 1909 until death; Academy election 28 May 1914; dated publications 1912,1914,1925,1930,1932. No claim of Academy membership before election.');
figure('finland-independent',aalto,'alvar-aalto','Alvar Aalto','1937','1939',['1898','1976'],['architect','designer'],'Architect working from his Helsinki house-office completed in 1936; earlier Turku activity and later American activity remain distinct.','Helsinki-associated modernist architect and furniture designer','Modernist architecture, including Paimio Sanatorium and collaboration with Aino Aalto and Otto Korhonen.','Foundation biography: Helsinki home finished autumn 1936; lived there rest of life; furniture collaboration and work in Finland, travel abroad 1938–39 acknowledged.',);
figure('finland-independent',aalto,'alvar-aalto','Alvar Aalto','1950','1960',['1898','1976'],['architect','designer'],'Helsinki home and renewed Finnish public-building commissions following American work; institutional/project association, not uninterrupted residence.','Architect of Finnish public buildings','Säynätsalo Town Hall, Rautatalo and Finnish educational buildings developed during the 1950s.','Foundation biography: return to Finland after American work, domestic competition wins 1948–1951 and public buildings constructed in 1950s; Helsinki home lifelong.');
const cohort={id:'regional01-nordic-institutions-cultural-activity',worker:'regional-nordic-research-worker',sources,claims};fs.writeFileSync(dir+'/cohort.json',JSON.stringify(cohort,null,2)+'\n');console.log({claims:claims.length,sources:sources.length});
