import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const out=path.dirname(fileURLToPath(import.meta.url));
const old=[...JSON.parse(fs.readFileSync('data/historical-sources.json')).sources,...JSON.parse(fs.readFileSync('data/comprehensive-dossiers.json')).packages.flatMap(p=>p.sources)];
const sources=[],claims=[];
const norm=u=>u.replace(/\/$/,'');
function source(id,title,institution,url,kind='institutional-history'){
  const s=old.find(s=>norm(s.url||'')===norm(url))||{id,title,institution,url,accessed:'2026-10-03',kind,usage:'Factual paraphrases and precise original-source locators only; no source images or complete copyrighted texts redistributed.'};
  if(!sources.some(x=>x.id===s.id))sources.push(s);return s.id;
}
const money=source('r09-brazil-bcb-standards','Síntese dos Padrões Monetários Brasileiros','Banco Central do Brasil, Museu de Valores','https://www.bcb.gov.br/content/acessoinformacao/museudocs/pub/SintesePadroesMonetariosBrasileiros.pdf','official-monetary-history');
const rio=source('r09-brazil-bn-capital','1763 — transferência da capital do Vice-Reino do Brasil para o Rio de Janeiro','Fundação Biblioteca Nacional, BNDigital; Luiz Ramiro Junior','https://bndigital.bn.gov.br/artigos/bicentenario-da-independencia-1763-transferencia-da-capital-do-vice-reino-do-brasil-para-o-rio-de-janeiro/');
const judicial=source('r09-brazil-funag-viceroys','Notas para uma história do Judiciário no Brasil — Carlos Fernando Mathias','Fundação Alexandre de Gusmão, Ministry of Foreign Affairs','https://funag.gov.br/loja/download/535-notas_para_uma_historia_do_judiciario_no_brasil.pdf','official-published-scholarly-history');
const machado=source('r09-brazil-abl-machado','Machado de Assis — biography','Academia Brasileira de Letras','https://www.academia.org.br/academicos/machado-de-assis/biografia','institutional-biography');
const bandeira=source('r09-brazil-abl-bandeira','Manuel Bandeira — biography','Academia Brasileira de Letras','https://www.academia.org.br/academicos/manuel-bandeira/biografia','institutional-biography');
const books=source('r09-brazil-abl-bandeira-bibliography','Manuel Bandeira — bibliography','Academia Brasileira de Letras','https://www.academia.org.br/academicos/manuel-bandeira/bibliografia','institutional-bibliography');
const neutrality=source('r09-brazil-neutrality-1914','Decreto11.038,4August1914 — Publicação Original','Câmara dos Deputados, legislative archive','https://www2.camara.leg.br/legin/fed/decret/1910-1919/decreto-11038-4-agosto-1914-575462-publicacaooriginal-98655-pe.html','primary-legal-document');
const university=source('r09-brazil-ufrj-history','História — Uma breve história da UFRJ','Universidade Federal do Rio de Janeiro; Antonio José Barbosa de Oliveira','https://ufrj.br/acesso-a-informacao/institucional/historia/');
const attack=source('r09-brazil-presidency-communique-1938','Diário Oficial do Estado de Santa Catarina,no1203,11May1938','Arquivo Público do Estado de Santa Catarina; contemporary Presidency Secretariat communiqué','https://acervo.arquivopublico.sc.gov.br/uploads/r/arquivo-publico-do-estado-de-santa-catarina-apesc/1/6/c/16cedd9f28b2d7306ece1b508956eeadcb892fcf4271fb85ac98ff400ceaebe3/e0db491d-1cf7-4415-a9b9-2782667a6b8d-40810-DOE_1203_11_05_1938_08F.pdf','primary-official-publication');
const brasilia=source('r09-brazil-brasilia-installation-programme','Programa das solenidades de instalação do governo federal em Brasília,21April1960','Presidência da República; Câmara dos Deputados digital library catalogue','https://bd.camara.leg.br/bd/items/f9139e8d-f90e-4bc5-933c-231901445e1a','official-archival-record');
const brasiliaHistory=source('r09-brazil-brasilia-government-history','Brasília — city history and inauguration','Brazilian Federal Government, G20 host-city history','https://www.gov.br/g20/pt-br/sobre-o-g20/cidades-sede/brasilia-df');
const I=(from,until)=>({kind:'interval',from,until,certainty:'exact'}),E=date=>({kind:'event',date,certainty:'exact'});
function add(id,entityId,category,value,temporal,refs,locator,note,extra={}){
 const precision=[temporal.from,temporal.until,temporal.date].some(d=>/^\d{4}-\d{2}-\d{2}$/.test(d||''))?'day':'year';
 claims.push({id:'r09-brazil-'+id,entityId,category,value,temporal,scope:{id:entityId+'-'+id,description:'Named historical Brazilian framework and institutional/person association; no modern-border statistical fallback or geometry inference.',relationship:'same'},sourceIds:refs,evidence:refs.map(sourceId=>({sourceId,locator,note,precision,temporal,interpretation:'direct'})),status:'supported',risks:[],qualifications:['Intervals are bounded research subsets. Entity-window day cutoffs do not date the introduction or abolition of a historical fact. Source year precision is retained for historical changes known only by year.'],origin:{kind:'new-research',reference:'Regional09 Brazilian institutional source packet; coordinator review required',sourceIdentifier:id},...extra});
}
const colonial='brazil-portuguese-colonial-framework',court='brazil-royal-court-framework',united='brazil-united-kingdom-1815-framework',empire='brazil-pedro-ii-imperial-framework',early='brazil-early-federal-republic-framework',estado='brazil-estado-novo-framework',post='brazil-1946-federal-framework';
add('colonial-rio',colonial,'capital','Rio de Janeiro',I('1800','1806'),[rio],'Historical narrative paragraphs1,3–5','National Library documents1763 transfer, royal governmental seat and continuing capitality; bounded pre-court framework only.',{role:'Capital'});
add('colonial-reis',colonial,'currency','Réis (mil-réis monetary unit)',I('1800','1806'),[money],'Single-page table,Réis row:period,unit and legal chronology','BCB dates this standard from early colonization to30October1942;1645 official naming is expressly documented. Not the post1994real.');
add('resende-viceroy',colonial,'leadership','José Luís de Castro,2nd Count of Resende',I('1800','1801-10-14'),[judicial],'Printed p79,chapterIX,José Luiz de Castro term9May1790–14October1801','Curated start covers1800 within explicitly dated tenure. Source distinguishes the governorship/viceroy title from Spanish-style vice-kingdom institutions.',{role:'Governor and Viceroy of the State of Brazil'});
add('court-rio',court,'capital','Rio de Janeiro',I('1809','1815-12-16'),[rio],'Historical narrative:capital as vice-regal residence and seat of Portuguese empire','Clipped to existing court framework.16December cutoff belongs to registered framework transition; not a capital move.',{role:'Seat of the Portuguese court'});
add('court-reis',court,'currency','Réis (mil-réis monetary unit)',I('1809','1815-12-16'),[money],'Single-page table,Réis row','Continuous monetary standard; clipped court framework,not an inferred modern country identity.');
add('united-rio',united,'capital','Rio de Janeiro',I('1815-12-16','1816-01-01'),[rio],'Historical narrative:Rio as seat of Portuguese empire','Curated post16December framework subset; no claim that capital relocation occurred on this date.',{role:'Court and governmental seat'});
add('united-reis',united,'currency','Réis (mil-réis monetary unit)',I('1815-12-16','1816-01-01'),[money],'Single-page table,Réis row','Stable monetary standard across the existing December framework change; research cutoff not currency-change date.');
add('estado-reis',estado,'currency','Réis (mil-réis monetary unit)',I('1938','1941'),[money],'Single-page table,Réis row','Conservative complete years before1942 transition. Existing republican/imperial réis claims are not replaced.');
add('estado-cruzeiro',estado,'currency','Cruzeiro (Cr$)',I('1943','1944'),[money],'Single-page table,firstCruzeiro row:1November1942–1December1964','Interior complete years after1942 reform and before1945government transition. No leap over unexplained31October1942 gap in monetary table.');
add('postwar-cruzeiro',post,'currency','Cruzeiro (Cr$)',I('1947','1960'),[money],'Single-page table,firstCruzeiro row','BCB dates firstcruzeiro to1November1942–1December1964; researchsubset follows1947–1960constitutional framework.');
add('brasilia-capital',post,'capital','Brasília',I('1960-04-21','1961-01-01'),[brasilia,brasiliaHistory],'Archival record date/title/Resumo; federal host-city history historical inauguration paragraph','Contemporary installation programme and official historical account support21April1960 governmental installation. End is curated framework cutoff; priorRio period is not overwritten.',{role:'Federal capital',qualifications:['Within-year capital transition retained. Brasíliadoes not become capital retrospectively for all1960. Catalogue body was read; underlying programmePDF was not retrieved.']});
function figure(id,entity,name,life,temporal,refs,locator,note,contribution){add(id,entity,'important-figures',name+' — poet and literary writer',temporal,refs,locator,note,{figure:{personId:id,name,categories:['literary'],lifespan:life,relationship:'Documented literary publication and professional activity within this Brazilian political framework, not nationality inferred from birthplace.',activity:'Literary writing and criticism in Brazil during the relevance interval.',contribution},qualifications:['Works named in contribution predate the earliest relevant snapshot. Later honours are not back-projected; no automatic conversion from officeholder to important figure.']});}
figure('machado-imperial',empire,'Machado de Assis',{from:'1839-06-21',until:'1908-09-29'},I('1877','1888'),[machado],'Biography paragraphs on1872–1876novels,continuednewspaper work and1880publication','ABL documents local writing and ministry employment,independent literary significance. Later1881novel form is not asserted as already published in1878.','Ressurreição(1872),A mão e a luva(1874) andHelena(1876),with literary journalism.');
figure('bandeira-early',early,'Manuel Bandeira',{from:'1886-04-19',until:'1968-10-13'},I('1920','1929'),[bandeira,books],'Biography returnfromSwitzerland,1917/1919publications and1927–1929Brazilianactivity; bibliographyCarnaval','Relevance begins after documented1919publication; his1913–1914Swissstay is not treated as Brazilianresidence.','A cinza das horas(1917) andCarnaval(1919),including experiments inpoetic rhythm.');
figure('bandeira-estado',estado,'Manuel Bandeira',{from:'1886-04-19',until:'1968-10-13'},I('1938','1944'),[bandeira,books],'Biography literary/criticalactivities; bibliographyLibertinagem1930/Estrela da Manhã1936','Existing literary activity and pre1938books ground selected-year relevance; no1938teachingappointment is projected to1January.','Libertinagem(1930),Estrela da Manhã(1936) andcritical writing.');
figure('bandeira-1960',post,'Manuel Bandeira',{from:'1886-04-19',until:'1968-10-13'},I('1959','1960'),[bandeira,books],'Biography1954memoir/1955newspaperchronicles; bibliography1958collectedwork','Continued late-careerBrazilian literary work,not merely birthplace or later posthumous reception.','Itinerário de Pasárgada(1954),literary criticism andcollectedPoesia e prosa(1958).');
add('bras-cubas-serialization',empire,'events-context','Machado de Assis serialized Memórias póstumas de Brás Cubas in Revista Brasileira',E('1880'),[machado],'Biography:serialization15March–15December1880,bookedition1881','Major literary development distinguished from laterbookpublication; yearprecision retained.');
add('neutrality-1914',early,'events-context','Brazil ordered neutrality in the war of Germany against France and Russia',E('1914-08-04'),[neutrality],'Original decree11.038,heading,operativeparagraph,signature/date; DOU5August1914p9046','Specific initialFirstWorldWar neutrality decree; does not claim neutralitycontinuedthrough1917.');
add('university-1920',early,'events-context','Federal creation of the University of Rio de Janeiro',E('1920-09-07'),[university],'History paragraph:decree14.343,7September1920,andthreeconstituentschools','University account distinguishes formal institutional creation from actual integration of teaching/research. Not yetnamedUFRJ.');
add('integralist-attack',estado,'events-context','An Integralist attack on Guanabara Palace was repelled,according to the presidency’s contemporary communiqué',E('1938-05-11'),[attack],'DiárioOficialno1203,11May1938,frontpageCommunicado da Secretaria da Presidência','Primary communiqué identifies attack and arrest; surrounding regime propaganda and claims of unanimous national support are not adopted.',{qualifications:['Contemporary government account is explicitly identified; no inferred casualty count or adoption of propagandistic political judgments.']});
add('brasilia-installation',post,'events-context','Installation of the federal government in Brasília',E('1960-04-21'),[brasilia,brasiliaHistory],'Catalogue title/date/Resumo ofPresidencyprogramme; historicalinaugurationparagraph','National capital transfer/inauguration,date retained,not genericfuturecontext.');
const cohort={id:'regional09-brazil-institutional-cohort',worker:'regional09-brazil-source-worker',sources,claims};
fs.writeFileSync(path.join(out,'cohort.json'),JSON.stringify(cohort,null,2)+'\n','utf8');
console.log(JSON.stringify({claims:claims.length,sources:sources.length,adjacent1815Claims:claims.filter(c=>[court,united].includes(c.entityId)).length}));
