import fs from 'node:fs';
const base='research/regional-09/resume-02/colombia/';
const sources=[
 ['r09r02-colombia-economic-history','La economía en el primer siglo republicano: los avatares del comercio exterior','https://enciclopedia.banrepcultural.org/La_econom%C3%ADa_en_el_primer_siglo_republicano:_los_avatares_del_comercio_exterior'],
 ['r09r02-colombia-war-history','La guerra de los mil días','https://enciclopedia.banrepcultural.org/La_guerra_de_los_mil_d%C3%ADas'],
 ['r09r02-colombia-presidents','Presidentes de Colombia - Listado','https://enciclopedia.banrepcultural.org/index.php/Presidentes_colombianos_(1810_-_actualidad)']
].map(([id,title,url])=>({id,title,url,institution:'Banco de la República, Banrepcultural encyclopedia',accessed:'2026-10-03',kind:'historical-institutional-evidence',usage:'Original institutional body read through web tool; concise factual paraphrase with named section and retained line locator. No biography campaign or copyrighted reproduction.'}));
const claims=[];
const interval=(from,until)=>({kind:'interval',from,until,certainty:'exact'});
function add(key,entityId,category,value,temporal,sourceIds,locator,note,qualifications,extra={}){
 claims.push({id:'r09r02-colombia-'+key,entityId,category,value,temporal,scope:{id:entityId+'-r09r02-'+category,description:category==='economy'?'Coffee-export receipts attributed by the institutional historian to historical Colombia in 1880; product-specific foreign-trade flow, not GDP or modern-border total.':'Named historical constitutional government and source-dated wartime action; no assertion of uniform territorial control or modern nationality.',relationship:'same'},sourceIds,evidence:sourceIds.map(sourceId=>({sourceId,locator,note,precision:(temporal.date||temporal.observationDate||temporal.from).length===10?'day':'year',temporal,interpretation:'direct'})),status:'supported',risks:[],qualifications,origin:{kind:'new-research',reference:sourceIds.join(';')},...extra});
}
const [economy,war,presidents]=sources.map(s=>s.id);
add('coffee-receipts1880','colombia-united-states-framework','economy',1.9,{kind:'observation',observationDate:'1880',certainty:'exact'},[economy],'Coffee chronology, paragraph beginning Aunque los ingresos en dólares; rendered lines 94–99, especially 98','Coffee export receipts: 1880, 1.9 million dollars.',['Annual historian-reported product receipts; original dollar unit and year retained. No inflation adjustment, interpolation or territorial aggregation.','Not GDP, government revenue, all exports, output tonnage or a claim that coffee dominated every regional economy.'],{metric:'Coffee export receipts',unit:'million dollars'});
add('palonegro1900','colombia-thousand-days-framework','events-context','Government forces defeated the liberal regular army at Palonegro; the war subsequently relied more heavily on guerrillas.',{kind:'event',date:'1900-05-26',certainty:'exact'},[war],'De sangre y llanto un río; rendered lines 34 and 39; La guerra Continúa, line 46','Palonegro lasted 11–26 May 1900 and ended in liberal defeat.',['Date is the battle conclusion, not a claim that the entire war ended. Casualty estimates omitted.']);
add('coup1900','colombia-thousand-days-framework','events-context','Conservative conspirators overthrew Sanclemente and installed Vice-President José Manuel Marroquín.',{kind:'event',date:'1900-07-31',certainty:'exact'},[war],'El golpe de Marroquín y esperanzas de paz; rendered lines 42–43','The coup took place on 31 July 1900.',['Dated change in executive authority; no assertion that peace followed or that the constitutional framework changed.']);
add('sanclemente-office','colombia-thousand-days-framework','leadership','Manuel Antonio Sanclemente',interval('1899-01-01','1900-07-30'),[war,presidents],'War: Antecedentes inmediatos, line 30; presidents: Sanclemente and Marroquín entries, lines 1008–1029','Sanclemente assumed personally on 3 November 1898; Marroquín replaced him on 31 July 1900.',['Research coverage starts at the existing entity envelope in 1899. Nominal presidency began 7 August 1898; acting Marroquín served until 3 November.','End excludes the transition day assigned to Marroquín; source transition is 31 July 1900, not a sourced separate 30 July departure.'],{role:'President'});
add('marroquin-office','colombia-thousand-days-framework','leadership','José Manuel Marroquín',interval('1900-07-31','1902-12-31'),[presidents],'José Manuel Marroquín entry and Período; rendered lines 1018–1029','Second presidency: 31 July 1900–7 August 1904.',['Coverage ends within the existing wartime entity envelope; actual presidency continued to 7 August 1904.','Wartime executive office is distinguished from effective territorial control.'],{role:'President'});
fs.writeFileSync(base+'cohort.json',JSON.stringify({id:'regional09-resume02-colombia-institutional-chronologies',worker:'regional09-resume02-colombia',sources,claims},null,2)+'\n');
fs.writeFileSync(base+'held.json',JSON.stringify([
 {category:'economy',reason:'1875–1878 export shares are multi-year aggregates, not annual 1878 observations. Qualitative 1878–1882 boom and 1898–1910 depression cannot satisfy numeric economy schema.'},
 {category:'important-figures',reason:'Shared war and presidents bodies do not establish dated non-office intellectual/social contribution plus lifespan. No leader-to-figure transfer.'},
 {categories:['capital','relationships'],reason:'Selected bodies do not establish historically bounded capital role or continuously dated foreign relationship. National Front body mixes 1958–1962 policies including later Alliance for Progress; no 1960 projection.'},
 {category:'leadership',entityId:'colombia-united-states-framework',reason:'Existing partial office evidence preserved; additional federal leadership research omitted in this tranche.'},
 {categories:['currency','population-statistics','area-statistics','density','historical-flag'],reason:'Explicit exclusions and prior held packets preserved.'}
],null,2)+'\n');
