import fs from 'node:fs';
import path from 'node:path';
import {readContext,digest} from '../../../scripts/research-common.mjs';
import {fields,generateDossierJob,validateDossier} from '../../../scripts/research-comprehensive.mjs';
import {reuseCatalogue} from '../../../scripts/research-scale.mjs';
const context=readContext(),catalogue=reuseCatalogue(context),base=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const interval=(from,until)=>({kind:'interval',from,until,certainty:'exact'}),event=date=>({kind:'event',date,certainty:'exact'});
const proposed=[];
function source(id,title,institution,url,kind='academic historical encyclopedia'){const existing=catalogue.sources.find(s=>s.url===url);if(existing)return existing.id;proposed.push({id,title,institution,url,kind,accessed:'2026-10-02',usage:'Independently paraphrased historical facts; no source text or images republished.'});return id;}
const hr=source('scale-tdv-halil-rifat','Halil Rifat Paşa — Atilla Çetin (1997)','TDV İslâm Araştırmaları Merkezi','https://islamansiklopedisi.org.tr/halil-rifat-pasa');
const sp=source('scale-tdv-said-pasa','Said Paşa, Küçük — Zekeriya Kurşun (2008)','TDV İslâm Araştırmaları Merkezi','https://islamansiklopedisi.org.tr/said-pasa-kucuk');
const law1871=source('scale-brazil-law-2040','Law 2,040, 28 September 1871 (Free Womb Law)','Presidência da República / Casa Civil','https://www.planalto.gov.br/ccivil_03/leis/lim/lim2040.htm','primary historical legislation');
const law1888=source('scale-brazil-law-3353','Law 3,353, 13 May 1888 (abolition of slavery)','Presidência da República / Casa Civil','https://www.planalto.gov.br/ccivil_03/leis/lim/lim3353.htm','primary historical legislation');
const crisis=source('scale-loc-siam-1893','Thailand: The Crisis of 1893','U.S. Library of Congress, Country Studies','https://countrystudies.us/thailand/17.htm','official historical country study');
const notes=source('scale-bot-banknotes-evolution','Thai Banknotes Evolution','Bank of Thailand','https://www.bot.or.th/en/our-roles/banknotes/History-and-Series-of-Banknote-And-Commemorative/banknote-evolution.html','official monetary history');
const notes1=source('scale-bot-series1','Series 1 historical banknotes','Bank of Thailand','https://www.bot.or.th/en/our-roles/banknotes/History-and-Series-of-Banknote-And-Commemorative/banknotes-series/banknote-series1.html','official monetary history');
const notes2=source('scale-bot-series2','Series 2 historical banknotes','Bank of Thailand','https://www.bot.or.th/en/our-roles/banknotes/History-and-Series-of-Banknote-And-Commemorative/banknotes-series/banknote-series2.html','official monetary history');
function start(entityId,from,until){const job=generateDossierJob(entityId,{from,until},context);return{schemaVersion:2,id:'scale-dossier-'+entityId,jobId:job.id,entityId,mapIds:job.mapIds,worker:{id:'scale-flags-versatile-worker',assignmentType:'comprehensive-entity-period'},productionFingerprint:job.productionFingerprint,chronology:{calendar:'proleptic-gregorian',yearConvention:'astronomical'},period:job.period,claims:[],sources:[],investigation:[],conflicts:[],provenance:{createdAt:'2026-10-02',method:'Catalogue-first existing snapshot gap research; source-body reading with bounded complementary facts, without production edits. Original source routes and historical cautions are recorded in the accompanying evidence ledger.',preservedPackageHashes:[]},_job:job};}
function claim(p,key,category,value,t,sourceId,locator,note,{scope=category,role,qualifications=[],precision,evidenceTemporal}={}){const c={id:'scale-'+p.entityId+'-'+key,category,value,entityId:p.entityId,temporal:t,scope:{id:p.entityId+'-'+scope,description:'Historical '+scope+' of this existing entity; not a claim about uniform territorial control or polygon-wide statistical geography.',relationship:'same'},sourceIds:[sourceId],evidence:[{sourceId,locator,note,precision:precision||((t.date||t.from).length>7?'day':'year'),temporal:evidenceTemporal||t,interpretation:'direct'}],status:'supported',risks:[],qualifications,origin:{kind:'new-research',reference:(proposed.find(s=>s.id===sourceId)||catalogue.sources.find(s=>s.id===sourceId)).url+'#'+key}};if(role)c.role=role;p.claims.push(c);return c;}
const brazil=start('brazil-pedro-ii-imperial-framework','1870','1888'),bt=interval('1870','1888');
const bc=(k,v,loc,note)=>claim(brazil,k,'political-institutional',v,bt,'b09-brazil-1824',loc,note,{scope:k,qualifications:['Constitutional provision, not proof of universal practical implementation. Provincial councils and original electoral qualifications are excluded because later reforms changed them.']});
bc('four-powers','The constitution distinguished legislative, moderating, executive and judicial powers.','Article 10','Four constitutional powers.');
bc('legislature','The General Assembly comprised a Chamber of Deputies and Senate; legislation required imperial sanction.','Articles 13–14','Bicameral assembly and sanction.');
bc('senate','Senators held life appointments; the emperor selected senators from provincial electoral triple lists.','Articles 40, 43','Lifetime Senate and selection.');
bc('moderating-power','The emperor exclusively held the moderating power, including appointment and dismissal of ministers and dissolution of the Chamber of Deputies with a replacement to be convened.','Articles 98, 101 V–VI','Moderating power and safeguards.');
bc('executive','The emperor exercised executive power through ministers of state.','Article 102','Executive authority via ministers.');
bc('provincial-administration','Each province had a president appointed and removable by the emperor.','Articles 165–166','Provincial presidents.');
bc('religion','Roman Catholicism was the state religion; other religions were allowed private or domestic worship without an exterior temple form.','Article 5','Religious establishment and limits.');
claim(brazil,'free-womb-law','events-context','The Free Womb Law declared children born to enslaved women after enactment free, while permitting compulsory service under specified conditions. It did not abolish slavery. ',event('1871-09-28'),law1871,'Article 1 and §1','Legal freedom subject to compulsory-service provisions.',{qualifications:['Do not equate the legal free condition with immediate release from coercive labour.']});
claim(brazil,'abolition','events-context','Law 3,353 abolished slavery throughout Brazil with effect from its enactment.',event('1888-05-13'),law1888,'Article 1 and enactment','Abolition takes effect on the law date.');
const ottoman=start('ottoman-abdulhamid-adjourned-framework','1879','1907');
for(const [key,from,until,role] of [['said-first','1879-10-18','1880-06-09','Başvekil (head of government)'],['said-second','1880-09-12','1882-05-02','Başvekil (head of government)'],['said-third','1882-07-12','1882-12-01','Head of government (sadâret)'],['said-fifth','1895-06-08','1895-10-01','Grand vizier'],['said-sixth','1901-11-18','1903-01-14','Grand vizier']])claim(ottoman,key,'leadership','Mehmed Said Paşa (Küçük Said Paşa)',interval(from,until),sp,'Biographical body: successive appointments and dismissals','Separate dated term; intervening appointments remain gaps.',{role,precision:'day',scope:'head-of-government',qualifications:['This records the office, not independent political control from the sultan. End date is exclusive.']});
claim(ottoman,'halil-rifat','leadership','Halil Rifat Paşa',interval('1895-11-07','1901-11-09'),hr,'Appointment 7 November 1895; death 9 November 1901','Dated tenure ends at death.',{role:'Grand vizier',precision:'day',scope:'head-of-government',qualifications:['An undated acting arrangement during his final illness is not assigned an invented boundary. End date is exclusive.']});
claim(ottoman,'public-debt','events-context','The Muharram Decree agreement granted European creditors an administration collecting designated Ottoman revenues.',event('1881-12-20'),'c01-ottoman-abdulhamid-ii','Paragraph on 20 December 1881 / Muharrem Kararnamesi','Dated fiscal agreement; not a sovereignty transfer.',{precision:'day'});
claim(ottoman,'agricultural-bank','events-context','The agricultural credit institutions were renamed Ziraat Bankası.',event('1888-08-15'),'c01-ottoman-abdulhamid-ii','Paragraph on Menâfi Sandıkları and Ziraat Bankası','Explicit bank naming date.',{precision:'day'});
const siam=start('b13-siam-absolute','1900','1931');
claim(siam,'bangkok','capital','Bangkok',interval('1900','1931'),'b13-siam-chakkri-history','Rama I transfer of court to Bangkok; historical capital','Bangkok capital continuity.',{qualifications:['Historical institutional seat; not equivalence between modern Bangkok geography and a historical map polygon.'],evidenceTemporal:interval('1800','1931')});
claim(siam,'vajiravudh','leadership','Vajiravudh (Rama VI)',interval('1911','1924'),crisis,'Paragraph identifying Vajiravudh (Rama VI, 1910–25)','Interior complete years exclude accession and death transitions.',{role:'King of Siam',scope:'head-of-state',evidenceTemporal:interval('1910','1925')});
claim(siam,'slavery','events-context','Gradual abolition of slavery culminated in its disappearance in 1905.',event('1905'),'c01-loc-chulalongkorn','Chulalongkorn reforms, paragraph on slavery','Year precision only.');
claim(siam,'siem-reap-battambang','events-context','Siam surrendered Battambang and Siem Reap to French-administered Cambodia.',event('1907'),crisis,'Paragraph on territorial concessions in 1907','Diplomatic event, no geometry-inferred succession.');
claim(siam,'malay-states','events-context','Siam relinquished claims to Kelantan, Trengganu, Kedah and Perlis to Britain in exchange for jurisdiction over British subjects and a railway loan.',event('1909'),crisis,'Paragraph beginning Two years later after 1907','Treaty context; no mapped succession inferred.');
claim(siam,'peace-conference','events-context','Siam participated in the Versailles peace conference.',event('1919'),crisis,'Concluding paragraph','Selected-year diplomatic participation.');
claim(siam,'notes-act','events-context','The Siamese Currency Notes Act was promulgated by royal command.',event('1902-06-24'),notes,'1902 Banknotes section','Explicit act date.',{precision:'day'});
claim(siam,'public-banknotes','events-context','The government banknote department began issuing and exchanging banknotes to the public.',event('1902-09-23'),notes,'1902 Banknotes section','Explicit first public service date.',{precision:'day',qualifications:['Official BOT date is retained; conflicting unsourced web dates are not substituted.']});
claim(siam,'first-notes','currency','Baht-denominated government banknotes (Series 1)',interval('1903','1924'),notes1,'Series 1 description: denominations; Rama V to Rama VI','Official denomination and reign-period description.',{qualifications:['Baht denomination of government notes; does not claim uniform exclusive circulation or a fixed exchange parity. Entire interior years avoid the 1902 introduction and 1925 series transition.']});
// Currency continuity beyond the first series is not inferred from the later series being used at some time in Rama VII’s reign.
for(const p of [brazil,ottoman,siam]){
 const used=[...new Set(p.claims.flatMap(c=>c.sourceIds))];p.sources=proposed.filter(s=>used.includes(s.id));
 const e=context.db.entities.find(e=>e.id===p.entityId);
 p.investigation=fields.map(category=>({category,status:'partial',rationale:p.claims.some(c=>c.category===category)?'Bounded sourced additions; no claim that this category is exhaustive.':category==='identity'?'Existing Phase 2 entity and map association retained; no new identity inference.':category==='historical-flag'?'No independently reviewed licensed imperial/period asset acquired; existing unrelated flag periods are not projected.':category.includes('statistics')||category==='density'||category==='economy'?'No compatible observed statistic and geography established in these consulted sources; no interpolation or fabricated estimate.':category==='important-figures'?'No additional person with independently dated territorial activity researched; rulers are not duplicated merely to inflate figure coverage.':'Existing sourced metadata retained where present; otherwise explicit gap awaiting dedicated evidence.',consultedSourceIds:category==='identity'?e.names[0].sourceIds||[]:[...new Set(p.claims.filter(c=>c.category===category).flatMap(c=>c.sourceIds))],gaps:['Further bounded research remains; no global completeness claim.']}));
 const job=p._job;delete p._job;for(const dir of ['jobs','packages','evidence'])fs.mkdirSync(path.join(base,dir),{recursive:true});
 const write=(dir,id,v)=>fs.writeFileSync(path.join(base,dir,id+'.json'),JSON.stringify(v,null,2)+'\n');write('jobs',p.id,job);write('packages',p.id,p);
 const result=validateDossier(p,job,context);write('evidence',p.id,{schemaVersion:1,packageHash:digest(p),validation:result,bodyReview:{method:'Complete factual article sections read via web tool on 2026-10-02; no copyrighted full text redistributed. Source body URLs and clause locators retained in claims.',sourceRoutes:used.map(id=>(p.sources.find(s=>s.id===id)||catalogue.sources.find(s=>s.id===id)).url)},held:p===siam?['KPI English biography gives erroneous 1925 coronation and 1934 abdication dates: no precise Prajadhipok reign claim admitted.','Series 2 appears during Rama VII reign but page gives no exact end: no projected 1926–1931 series continuity.']:p===brazil?['Sinimbu archival body security challenge: search snippet is not accepted evidence.','Original provincial councils/electoral qualifications excluded because later reforms changed them.']:['Fourth Said term not assigned an exact start from a relative forty-eight-hour statement.','No invented boundary for Abdurrahman acting grand vizier during Halil Rifat illness.']});
 console.log(JSON.stringify({id:p.id,claims:p.claims.length,packageHash:digest(p),valid:result.valid,errors:result.errors,review:result.review}));
}
