import {readContext,readJSON,saveJSON,digest} from '../../../scripts/research-common.mjs';
import {fields,generateDossierJob,validateDossier,sourceIndex,temporalBounds} from '../../../scripts/research-comprehensive.mjs';
import {reuseCatalogue} from '../../../scripts/research-scale.mjs';
export const assignments=[['united-states','1901','1912'],['united-kingdom','1838','1855'],['france-political-frameworks','1875','1890'],['germany-imperial-framework','1872','1890'],['italy-liberal-monarchy-framework','1872','1900'],['japan-meiji-framework','1891','1911'],['spain-political-frameworks','1877','1900'],['qajar-preconstitutional-framework','1849','1895']];
export const interval=(from,until)=>({kind:'interval',from,until,certainty:'exact'}),event=date=>({kind:'event',date,certainty:'exact'}),observation=observationDate=>({kind:'observation',observationDate,certainty:'exact'});
export function create(sequence){
 const [id,from,until]=assignments[sequence-1],context=readContext(),job=generateDossierJob(id,{from,until},context),existing=reuseCatalogue(context).sources;
 const pkg={schemaVersion:2,id:'scale01-design-'+id,jobId:job.id,entityId:id,mapIds:job.mapIds,worker:{id:'campaign-design',assignmentType:'comprehensive-entity-period'},productionFingerprint:job.productionFingerprint,chronology:{calendar:'proleptic-gregorian',yearConvention:'astronomical'},period:job.period,claims:[],sources:[],investigation:[],conflicts:[],provenance:{createdAt:'2026-10-02',method:'One coherent deep entity/period pass; production registry, preserved accepted evidence and comprehensive pilot sources searched before external institutional research.',preservedPackageHashes:[]}},notes=[];
 const source=(key,title,institution,url,usage,kind='institutional-historical')=>{const old=existing.find(s=>s.id===key||s.url===url);if(old)return old.id;if(!pkg.sources.some(s=>s.id===key))pkg.sources.push({id:key,title,institution,url,accessed:'2026-10-02',usage,kind});return key;};
 const claim=(key,category,value,temporal,sid,locator,note,extra={})=>{const dates=temporal.kind==='interval'?[temporal.from,temporal.until]:[temporal.date||temporal.observationDate],precision=dates.some(d=>d.length===10)?'day':dates.some(d=>d.length===7)?'month':'year';const c={id:'s01-'+id+'-'+key,category,value,entityId:id,temporal,scope:{id:id+'-institutional',description:'Historical entity institutions and associated dated activity, not inferred polygon control.',relationship:'same'},sourceIds:[sid],evidence:[{sourceId:sid,locator,note,precision,temporal:structuredClone(temporal),interpretation:'direct'}],status:'supported',risks:[],qualifications:[],origin:{kind:'new-research',reference:sid},...extra};pkg.claims.push(c);return c;};
 const e=context.db.entities.find(e=>e.id===id);
 for(const [field,category]of [['names','identity'],['capitals','capital'],['currencies','currency'],['leaders','leadership']])for(const [i,f]of(e[field]||[]).entries()){
  if(!f.sourceIds?.length||!f.validFrom)continue;const bounds=temporalBounds(interval(f.validFrom,f.validUntil||'1961-01-01')),wanted=temporalBounds(interval(from,until));if(bounds.lo>=wanted.hi||bounds.hi<=wanted.lo)continue;const a=bounds.lo<wanted.lo?from:f.validFrom,b=bounds.hi>wanted.hi?until:f.validUntil||until;
  claim('reuse-'+field+'-'+i,category,f.value,interval(a,b),f.sourceIds[0],'Existing production sourced record: '+field+'['+i+']',f.note||'Existing dated sourced record, clipped to bounded campaign interval.',{sourceIds:f.sourceIds,origin:{kind:'production-reuse',reference:'data/historical-entities.json#'+id+'/'+field+'/'+i},qualifications:['Existing sourced fact reused, excluded from new-information throughput.'],...(f.role?{role:f.role}:{})});
 }
 const body=(sid,locator,note)=>notes.push({sourceId:sid,locator,note,bodyReviewed:true});
 const finish=(gaps={})=>{for(const category of fields){const cs=pkg.claims.filter(c=>c.category===category),sids=[...new Set(cs.flatMap(c=>c.sourceIds))];pkg.investigation.push({category,status:cs.length?(gaps[category]||cs.some(c=>c.status!=='supported')?'partial':'supported'):'unresolved',rationale:cs.length?'Bounded dated evidence and existing facts examined together; independently reviewed before serial integration.':'Applicable category considered against core sources and reuse index; no unsupported fallback.',consultedSourceIds:sids.length?sids:[...new Set(pkg.claims.flatMap(c=>c.sourceIds))].slice(0,3),gaps:gaps[category]||(!cs.length?[category==='historical-flag'?'Parallel flag worker handles licensed historical design; no guessed asset.':category==='density'?'No compatible same-observation population/area pair.':category==='relationships'?'No sovereignty, succession or dependency inferred from geometry.':'No sufficiently precise bounded evidence accepted in this pass.']:[])});}saveJSON('research/scale-01/jobs/'+id+'.json',job);saveJSON('research/scale-01/packages/'+id+'.json',pkg);const v=validateDossier(pkg,job,context);saveJSON('research/scale-01/evidence/'+id+'.json',{packageHash:digest(pkg),sourceBodyNotes:notes,categoryInvestigation:pkg.investigation,worker:'campaign-design',researchPasses:1});saveJSON('research/scale-01/evidence/'+id+'-validation.json',v);console.log(JSON.stringify({id,claims:pkg.claims.length,new:pkg.claims.filter(c=>c.origin.kind==='new-research').length,valid:v.valid,errors:v.errors,review:v.review}));};
 return{pkg,job,context,source,claim,body,finish};
}
