import{create,interval,event}from'./design-build.mjs';
const{source,claim,body,finish}=create(5);
const stat=source('b04-statuto','Statuto Albertino','Presidency of the Italian Republic','https://www.quirinale.it/allegati_statici/costituzione/Statutoalbertino.pdf','Primary constitutional text read; formal arrangements distinguished from electoral law/practice.','primary-document');
for(const[key,loc,value]of[
 ['religion','Articles1–2','The Statuto designated Catholicism the state religion and tolerated other existing cults according to law; hereditary monarchy followed Salic succession.'],
 ['executive','Articles3–10','Legislation required king and both chambers; the king held executive and military authority, appointed officials and sanctioned laws. Financial or territorial treaty changes required chamber assent.'],
 ['civil-rights','Articles24–32','The Statuto protected personal liberty, home and property and allowed press and peaceful assembly subject to statutory and police restrictions. These formal rights did not imply universal suffrage.'],
 ['chambers','Articles33–42','Senators were royally appointed for life from designated categories; deputies were elected under electoral law for five-year terms and represented the nation.'],
 ['ministerial','Articles65–67','The king appointed and dismissed ministers. Ministers were responsible, and government acts required a ministerial signature.'],
 ['judicial','Articles68–73','Justice was administered in the king’s name; qualified judges gained security after three years, extraordinary tribunals were prohibited and judicial hearings were public according to law.']])claim(key,'political-institutional',value,interval('1872','1900'),stat,loc,'Formal Statuto provisions throughout bounded liberal monarchy period; later fascist practice excluded.',{metric:key});
const bank=source('s01-bankitaly-history','Storia della Banca d’Italia','Banca d’Italia','https://www.bancaditalia.it/chi-siamo/storia/index.html','Full historical body read; foundation and subsequent monopoly carefully separated.');
claim('bank-founded','events-context','Banca d’Italia was established in1893 during a reorganisation of note-issuing institutions.',event('1893'),bank,'Openinghistoryparagraph','Its sole note-issue monopoly began1926, outside this period, and is not back-projected.');
claim('note-issuance','political-institutional','Banca d’Italia was a note-issuing institution, but did not yet hold the sole national banknote-issue monopoly later granted in1926.',interval('1894','1900'),bank,'Openinghistoryparagraph','Conservative years after foundation; expressly avoids projecting modern central-bank powers backwards.',{metric:'note-issue-institutions'});
body(stat,'Primary PDF pp1–7 Articles1–83','Text read across full constitutional institutional chapters; no reproduction of whole document.');body(bank,'Fullhistorybodyparagraphs1893–1999','Bounded1893institutional facts only;1926contrast explicitly future.');
finish({leadership:['Existing royal dates reused; ministerial sequence still needs separately dated sources.'],'important-figures':['No source-body-supported cultural biography accepted in this pass.'],'population-statistics':['No comparable dated census and territory-scope evidence accepted.']});
