import fs from 'node:fs';
import {readContext,digest} from '../../../scripts/research-common.mjs';
import {fields,generateDossierJob,validateDossier} from '../../../scripts/research-comprehensive.mjs';
export const context=readContext();
export const I=(from,until)=>({kind:'interval',from,until,certainty:'exact'}),E=date=>({kind:'event',date,certainty:'exact'}),O=observationDate=>({kind:'observation',observationDate,certainty:'exact'});
export function create(entityId,from,until){
 const job=generateDossierJob(entityId,{from,until},context),entity=context.db.entities.find(e=>e.id===entityId);
 const pkg={schemaVersion:2,id:'scale01-'+entityId,jobId:job.id,entityId,mapIds:job.mapIds,worker:{id:'campaign-selection',assignmentType:'comprehensive-entity-period'},productionFingerprint:job.productionFingerprint,chronology:{calendar:'proleptic-gregorian',yearConvention:'astronomical'},period:job.period,claims:[],sources:[],investigation:[],conflicts:[],provenance:{createdAt:'2026-10-02',method:'Computational production/preserved-source lookup and bounded full-body research; all applicable categories investigated; no automatic acceptance.',preservedPackageHashes:[]}};
 const notes=[];
 const source=(id,title,institution,url,note,kind='institutional-historical')=>{let rich=fs.existsSync('data/comprehensive-dossiers.json')?JSON.parse(fs.readFileSync('data/comprehensive-dossiers.json')).packages.flatMap(p=>p.sources):[];let found=[...context.registry.sources,...rich].find(s=>s.id===id||s.url===url);if(found)return found.id;if(!pkg.sources.some(s=>s.id===id))pkg.sources.push({id,title,institution,url,accessed:'2026-10-02',usage:note,kind});return id;};
 const claim=(key,category,value,t,ids,locator,note,extra={})=>{ids=Array.isArray(ids)?ids:[ids];let date=t.from||t.date||t.observationDate,precision=date.length===10||t.until?.length===10?'day':date.length===7||t.until?.length===7?'month':'year';let c={id:'s01-'+entityId+'-'+key,entityId,category,value,temporal:t,scope:{id:entityId+'-institutional',description:'Historical institutions and entity-associated activity; no inference of uniform polygon control.',relationship:'same'},sourceIds:ids,evidence:ids.map(sourceId=>({sourceId,locator,note,precision,temporal:structuredClone(t),interpretation:'direct'})),status:'supported',risks:[],qualifications:[],origin:{kind:'new-research',reference:ids[0]},...extra};pkg.claims.push(c);return c;};
 const clip=old=>{let a=old.validFrom||from,b=old.validUntil||until;if(a<from)a=from;if(b>until)b=until;return a<b?I(a,b):null;};
 const reuse=(field,category)=>{for(let [n,old]of(entity[field]||[]).entries()){let t=clip(old);if(!t||!old.sourceIds?.length)continue;claim('reuse-'+field+'-'+n,category,old.value,t,old.sourceIds,'Existing sourced production record',old.note||'Bounded reuse of independently sourced production record.',{origin:{kind:'production-reuse',reference:'data/historical-entities.json#'+entityId+'/'+field+'/'+n},...(old.role?{role:old.role}:{}),metric:old.label||field+'-'+n,qualifications:['Existing production evidence; excluded from new-information throughput.']});}};
 const save=(gaps={})=>{pkg.investigation=fields.map(category=>{let cs=pkg.claims.filter(c=>c.category===category),sources=[...new Set(cs.flatMap(c=>c.sourceIds))];if(!sources.length)sources=[...new Set(pkg.claims.flatMap(c=>c.sourceIds))].slice(0,3);return{category,status:cs.length?'partial':'unresolved',rationale:'Production claims and registered/preserved sources searched first; complete relevant source bodies reviewed. Supported claims are individually dated; coverage gaps remain explicit.',consultedSourceIds:sources,gaps:gaps[category]||[cs.length?'Other intervals/details not exhausted by these bounded claims; no continuous completeness asserted.':'No defensible dated claim with compatible entity/scope established in reviewed bodies; no fallback or inference.']};});for(let d of ['jobs','packages','evidence'])fs.mkdirSync('research/scale-01/'+d,{recursive:true});fs.writeFileSync('research/scale-01/jobs/'+entityId+'.json',JSON.stringify(job,null,2)+'\n');fs.writeFileSync('research/scale-01/packages/'+entityId+'.json',JSON.stringify(pkg,null,2)+'\n');fs.writeFileSync('research/scale-01/evidence/'+entityId+'.json',JSON.stringify({entityId,packageHash:digest(pkg),sourceBodyNotes:notes,categoryInvestigation:pkg.investigation,productionEdited:false},null,2)+'\n');let v=validateDossier(pkg,job,context);console.log(JSON.stringify({entityId,claims:pkg.claims.length,new:pkg.claims.filter(c=>c.origin.kind==='new-research').length,valid:v.valid,errors:v.errors,review:v.review}));return v;};return{pkg,entity,job,source,claim,reuse,save,notes};
}
