import fs from 'node:fs';
const base='research/regional-17/belgian-system/';
const sources=[
 {id:'r17-belgian-system-aacb-money',title:'Rwanda monetary history — A brief survey',institution:'Association of African Central Banks',url:'https://www.aacb.org/fr/book/export/html/374',accessed:'2026-10-03',kind:'historical-institutional-evidence',usage:'Original monetary chronology read in full, sections 1–7; only source-supported legal-unit coverage and actual dated institutional changes used.'},
 {id:'r17-belgian-system-archives-guide',title:'Guide des sources de l’histoire de la colonisation — dossier de presse',institution:'Archives de l’État en Belgique and Musée royal de l’Afrique centrale',url:'https://www.arch.be/docs/presse/Archives-de-l-Etat_Guide-Congo_Dossier-presse.pdf',accessed:'2026-10-03',kind:'historical-institutional-evidence',usage:'Original historical chronology read, PDF page 13 (printed page 12); official capital transfer distinguished from physical governmental relocation.'}
];
const [money,archive]=sources.map(s=>s.id),claims=[];
const interval=(from,until)=>({kind:'interval',from,until,certainty:'exact'});
function add(key,entityId,category,value,temporal,sourceId,locator,note,qualifications=[],extra={}){
 claims.push({id:'r17-belgian-system-'+key,entityId,category,value,temporal,scope:{id:entityId+'-r17-'+category,description:'Named historical administration and legally sourced monetary system or governmental role; royal courts, residents and central colonial government remain distinct. No modern-border or nationality inference.',relationship:'same'},sourceIds:[sourceId],evidence:[{sourceId,locator,note,precision:(temporal.date||temporal.from).length===10?'day':'year',temporal,interpretation:'direct'}],status:'supported',risks:[],qualifications,origin:{kind:'new-research',reference:sourceId},...extra});
}
const congo='b17-belgian-congo-colonial',ruanda='b17-rwanda-belgian-mandate',urundi='b17-burundi-belgian-mandate',rt='b17-rwanda-un-trust',bt='b17-burundi-un-trust';
const currencyQual=['Research bounds lie within the existing entity envelope and the source legal regime; they are not asserted adoption or office dates.','Unit distinguished from issuer, gold parity and physical replacement. No exclusive circulation, constant convertibility or modern currency inference.'];
add('congo-franc',congo,'currency','Congolese franc',interval('1914','1938'),money,'Sections 2–4; original rendered lines 11–21','Franc issues and the subsequent legal regime are explicit.',currencyQual);
for(const [key,eid]of [['ruanda',ruanda],['urundi',urundi]])add(key+'-franc',eid,'currency','Congolese franc',interval('1928','1945'),money,'Sections 3–4; original rendered lines 15–21','Issuing extension and wartime franc regime explicitly include Ruanda-Urundi.',currencyQual);
for(const [key,eid]of [['ruanda',rt],['urundi',bt]]){
 add(key+'-trust-old-franc',eid,'currency','Congolese franc',interval('1960-01-01','1960-09-21'),money,'Section 6; original rendered lines 28–32','Old notes lose legal status from 22 September.',[...currencyQual,'End excludes the explicitly sourced withdrawal date; source does not imply an earlier end at Congolese independence.']);
 add(key+'-trust-new-franc',eid,'currency','Rwanda and Burundi franc',interval('1960-09-22','1960-12-31'),money,'Section 6; original rendered lines 29–32','New franc legally created and old notes withdrawn.',[...currencyQual,'Conservative coverage begins at the sourced note transition; not asserted to be the initial legal creation date.']);
 add(key+'-trust-note-transition',eid,'events-context','Old central-bank notes ceased legal tender status.',{kind:'event',date:'1960-09-22',certainty:'exact'},money,'Section 6; original rendered line 30','Effective withdrawal date retained.',['Dated legal status change; not instantaneous destruction or replacement of every note.']);
}
add('congo-boma-capital',congo,'capital','Boma',interval('1914','1922'),archive,'Le Congo belge; PDF page 13, printed page 12; original rendered lines 195–198','Official transfer from Boma dated 1923; effective relocation dated 1929.',['Official capital role only; conservative coverage before the source transfer year. Year precision retained.','No Congo governmental capital assigned to either royal court or Ruanda-Urundi.']);
add('congo-capital-decision',congo,'events-context','Official capital transferred from Boma to Léopoldville.',{kind:'event',date:'1923',certainty:'exact'},archive,'Le Congo belge; PDF page 13, printed page 12; rendered line 197','Decision year retained.',['Official designation distinguished from later physical relocation.']);
add('congo-capital-effective',congo,'events-context','Transfer to Léopoldville became effective.',{kind:'event',date:'1929',certainty:'exact'},archive,'Le Congo belge; PDF page 13, printed page 12; rendered line 197','Effective year retained.',['No invented month or day.']);
for(const [key,eid]of [['ruanda',ruanda],['urundi',urundi]])add(key+'-zone-return',eid,'events-context','Monetary agreement moved Ruanda-Urundi into the Belgian monetary zone.',{kind:'event',date:'1944-10-15',certainty:'exact'},money,'Section 4; original rendered line 21','Agreement date retained.',['Dated monetary-zone action only; no diplomatic-persistence interval inferred.']);
fs.writeFileSync(base+'cohort.json',JSON.stringify({id:'regional17-belgian-system-monetary-capital-chronologies',worker:'regional17-belgian-system-worker',sources,claims},null,2)+'\n');
fs.writeFileSync(base+'held.json',JSON.stringify([
 {categories:['leadership','important-figures'],reason:'Selected system chronologies do not provide complete office tables or lifespan with dated cultural contribution. No separate person-by-person chase or ruler-to-figure transfer.'},
 {category:'currency',scope:'German and precolonial royal systems, 1900; mandate years 1926–1927',reason:'Earlier monetary heterogeneity and 1927 formal extension prevent blanket earlier unit continuity. Bank issuing authority alone is not proof of exclusive circulation.'},
 {category:'capital',scope:'Ruanda/Urundi courts and administration',reason:'No historically bounded court/resident/admin capital roles established. Bank head office is not political capital; no Boma or Leopoldville geometry fallback.'},
 {category:'relationships',reason:'Dated monetary agreements are events; continuing alliance or diplomatic-persistence intervals not established. Existing supported Belgian administrative relationship remains untouched.'},
 {categories:['economy','population-statistics','area-statistics','density','historical-flag'],reason:'No adequate exact observation with represented historical statistical scope, or dated flag evidence, in chosen institutional chronologies.'},
 {source:'https://www.bcc.cd/la-banque/histoire/historique-de-la-banque-centrale',reason:'BCC history read but not used: Leopoldville-as-EIC-capital statement conflicts with detailed archival capital chronology.'},
 {source:'https://www.brb.bi/en/node/9/revisions/9/view',reason:'Original body inaccessible; search extract not relied on. Additional archive URL also inaccessible; source chase stopped.'}
],null,2)+'\n');
console.log(JSON.stringify({claims:claims.length,sources:sources.length,entities:new Set(claims.map(c=>c.entityId)).size}));
