import fs from 'node:fs';
import {readContext} from '../../../scripts/research-common.mjs';
const base='research/regional-09/resume-02/guianas';fs.mkdirSync(base,{recursive:true});
const known=[...readContext().registry.sources,...JSON.parse(fs.readFileSync('data/comprehensive-dossiers.json')).packages.flatMap(p=>p.sources)];
const source=(id,url,title,institution)=>known.find(s=>s.url===url)||{id,url,title,institution,kind:'institutional-history',accessed:'2026-10-03',usage:'Original historical body read, individual dated events only; no modern fallback, full source reproduction or inferred political continuity.'};
const a=source('r09r2-guiana-reforms','https://countrystudies.us/guyana/9.htm','Guyana: A Country Study — Political and Social Awakenings','U.S. Library of Congress, 1992');
const b=source('r09r2-guiana-war-reform','https://countrystudies.us/guyana/10.htm','Guyana: A Country Study — Political and Social Changes in the 1900s','U.S. Library of Congress, 1992');
const c=source('r09r2-french-guiana-archives','https://archives-nationales-outre-mer.culture.gouv.fr/faire-une-recherche/guyane','Guyane: archival and administrative historical guide','Archives nationales d’outre-mer');
const claims=[];
function event(id,entityId,value,date,s,locator,qualification=[]){const temporal={kind:'event',date,certainty:'exact'};claims.push({id:'r09r2-guianas-'+id,entityId,category:'events-context',value,temporal,scope:{id:entityId+'-institutional-history',description:'Named historical colonial jurisdiction; no geometry-derived sovereignty or modern-border statistic.',relationship:'same'},sourceIds:[s.id],evidence:[{sourceId:s.id,locator,note:'Original historical body independently readable. Actual event year preserved without invented month/day. No event assigned to a different administration.',precision:'year',temporal,interpretation:'direct'}],status:'supported',risks:[],qualifications:qualification,origin:{kind:'new-research',reference:s.id}});}
event('secret-ballot','british-guiana-court-policy-framework','British Guiana introduced the secret ballot.','1897',a,'Political and Social Awakenings, paragraph on 1897 and 1909 electoral reforms.');
event('electorate','british-guiana-court-policy-framework','An electoral reform expanded British Guiana’s restricted electorate.','1909',a,'Political and Social Awakenings, paragraph on 1897 and 1909 electoral reforms.',['This was an expansion of a restricted franchise, not universal suffrage.']);
event('elected-majority','british-guiana-crown-colony-framework','Reforms made elected members a majority on British Guiana’s Legislative Council.','1943',b,'Final wartime reform paragraphs: Gordon Lethem reduced property qualifications and made elective members a majority in 1943.');
event('brazil-concession','french-guiana-colonial-framework','The territory between the Oyapock and Amazon was conceded to Brazil.','1900',c,'Opening historical overview dates the territorial concession to Brazil in 1900.',['ANOM’s historical account supplies the concession and date; this does not establish prior effective control or infer a boundary from map geometry.']);
fs.writeFileSync(base+'/cohort.json',JSON.stringify({id:'regional09-resume02-guianas-dated-reforms',worker:'regional09-resume02-root-guianas-researcher',sources:[a,b,c],claims},null,2)+'\n');
fs.writeFileSync(base+'/held.json',JSON.stringify([{issue:'Capital continuity',reason:'Original official art catalogue inaccessible; earlier capital founding does not alone establish uninterrupted later applicability.'},{issue:'Moyne Commission date and BGLU foundation chronology',reason:'Country-study dating appears inconsistent with official chronology. Neither claim imported; no individual exception research.'},{issue:'1957 election and constitutional suspension',reason:'Actual events precede the current 1958 researched framework envelope. No dates or entity IDs rewritten to force acceptance.'}],null,2)+'\n');
