import fs from 'node:fs';
const root='research/regional-01/lowcountries/';
const sources=[
 {id:'r01-amsterdam-capital-history',title:'Amsterdam wordt hoofdstad van Nederland',institution:'Gemeente Amsterdam',url:'https://www.amsterdam.nl/nieuws/achtergrond/amsterdam-hoofdstad/',accessed:'2026-10-02',kind:'official-municipal-history'},
 {id:'r01-nbb-franc-history',title:'A brief history of the Belgian franc',institution:'National Bank of Belgium',url:'https://www.nbb.be/en/banknotes-and-coins/history-euro-and-belgian-franc/brief-history-belgian-franc',accessed:'2026-10-02',kind:'official-central-bank-history'},
 {id:'r01-luxembourg-bleu-history',title:'Top 5: agreements that have shaped Luxembourg’s history',institution:'Government of Luxembourg',url:'https://luxembourg.public.lu/en/society-and-culture/history/top-5-agreements-luxembourg-history.html',accessed:'2026-10-02',kind:'official-government-history'},
 {id:'r01-benelux-treaty-history',title:'History of the Benelux',institution:'Secretariat-General of the Benelux Union',url:'https://www.benelux.int/en/information-for-citizens/benelux-union/about-us/history/',accessed:'2026-10-02',kind:'official-institutional-history'},
 {id:'r01-luxembourg-personal-union',title:'The history of the Nassau dynasty',institution:'Cour grand-ducale',url:'https://monarchie.lu/en/luxembourg-monarchy/history-nassau-dynasty',accessed:'2026-10-02',kind:'official-monarchical-history'},
 {id:'r01-lorentz-biography',title:'Hendrik A. Lorentz – Biographical; Nobel Lectures, Physics 1901–1921, Elsevier, 1967',institution:'Nobel Foundation / Nobel Prize Outreach',url:'https://www.nobelprize.org/prizes/physics/1902/lorentz/biographical/',accessed:'2026-10-02',kind:'institutional-biographical-reference'},
 {id:'r01-zeeman-biography',title:'Pieter Zeeman – Biographical; Nobel Lectures, Physics 1901–1921, Elsevier, 1967',institution:'Nobel Foundation / Nobel Prize Outreach',url:'https://www.nobelprize.org/prizes/physics/1902/zeeman/biographical/',accessed:'2026-10-02',kind:'institutional-biographical-reference'},
 {id:'r01-spitteler-biography',title:'Carl Spitteler – Facts',institution:'Nobel Foundation / Nobel Prize Outreach',url:'https://www.nobelprize.org/prizes/literature/1919/spitteler/facts/',accessed:'2026-10-02',kind:'institutional-biographical-reference'}
];
const claims=[];
const interval=(from,until)=>({kind:'interval',from,until,certainty:'exact'});
function add(entityId,category,key,value,temporal,sourceId,locator,note,extra={}) {
 const c={id:'r01-lowcountries-'+key,entityId,category,value,temporal,scope:{id:entityId+'-'+key,description:'Named historical state or institutional/person association; no statistical or polygon-wide inference.',relationship:'same'},sourceIds:[sourceId],evidence:[{sourceId,locator,note,precision:'year',temporal,interpretation:'direct'}],status:'supported',risks:[],qualifications:['Year precision retained. Bounded research interval is not an assertion that the historical institution or person began or ended at its research cutoff.'],origin:{kind:'new-research',reference:'Regional Batch 01 original institutional source review',sourceIdentifier:key},...extra}; claims.push(c);return c;
}
// Ceremonial capital is distinct from the seat of government; exile chronology is held.
for(const [from,until,key] of [['1831','1939','amsterdam-prewar'],['1946','1960','amsterdam-postwar']])add('netherlands-kingdom','capital',key,'Amsterdam',interval(from,until),sources[0].id,'Napoleon / Feestelijke intocht / Grondwet van 1983','Municipal account establishes the capital in 1808 and distinguishes The Hague as governmental city. Capital status was written into the constitution only in 1983. Curated monarchy subset excludes 1940–1945 exile and occupation. No claim that Parliament sat in Amsterdam.',{role:'Historical capital'});
// Monetary union is a real inter-state relationship, not a constitutional regime.
for(const entityId of ['belgium-kingdom','swiss-federal-state'])add(entityId,'relationships',entityId+'-latin-monetary-union','Member of the Latin Monetary Union, whose participating states coordinated gold and silver coin standards.',interval('1866','1924'),sources[1].id,'Latin Monetary Union (1865–1926)','NBB explicitly identifies Belgium, Switzerland, France, Italy and Greece as participants. Conservative interior excludes founding and dissolution years; neither banknote union nor political federation is asserted.',{relatedEntityIds:[entityId==='belgium-kingdom'?'swiss-federal-state':'belgium-kingdom','france-political-frameworks']});
for(const entityId of ['belgium-kingdom','luxembourg-grand-duchy'])add(entityId,'relationships',entityId+'-bleu','Linked to the other state through the Belgium–Luxembourg Economic Union (BLEU).',interval('1923','1960'),sources[2].id,'The treaty of the Belgo-Luxembourg Economic Union – 1921','Official history identifies the treaty and continuing economic and monetary ties. The conservative 1923 start avoids treating signature in 1921 as commencement in that year; no sovereign merger is implied.',{relatedEntityIds:[entityId==='belgium-kingdom'?'luxembourg-grand-duchy':'belgium-kingdom']});
for(const entityId of ['belgium-kingdom','luxembourg-grand-duchy','netherlands-kingdom']){
 add(entityId,'relationships',entityId+'-benelux-customs-agreement','Party to the 1944 Benelux Customs Agreement with the other two Benelux states; implementation of the customs union followed in 1948.',interval('1944','1947'),sources[3].id,'Timeline entries 1944 and 1948','Signed agreement is distinguished from customs union implementation. No functioning customs union is projected into 1945.',{relatedEntityIds:['belgium-kingdom','luxembourg-grand-duchy','netherlands-kingdom'].filter(x=>x!==entityId)});
 add(entityId,'events-context',entityId+'-benelux-1960','The Benelux Economic Union treaty was implemented in 1960.',{kind:'event',date:'1960',certainty:'exact'},sources[3].id,'Timeline entry 1960','Year-only event date; does not pretend implementation was already complete on January 1 or before the event within 1960.');
}
add('netherlands-kingdom','relationships','netherlands-luxembourg-personal-union','The Dutch sovereign also held the title of Grand Duke of Luxembourg in a personal union.',interval('1816','1889'),sources[4].id,'Opening account of personal union, 1815–1890','The two titles were united from 1815 until the divergent successions of 1890. Conservative interior avoids transition years. Neither territorial union nor a single constitutional state is inferred.',{relatedEntityIds:['luxembourg-grand-duchy']});
function figure(key,entityId,name,from,until,birth,death,category,relationship,activity,contribution,sourceId,locator,note){add(entityId,'important-figures',key,name+' — '+activity,interval(from,until),sourceId,locator,note,{figure:{personId:key,name,categories:[category],lifespan:{from:birth,until:death},relationship,activity,contribution},qualifications:['Relevance follows documented work/residence, not birthplace or projected nationality. Later awards are significance corroboration, not claims that an award had occurred in an earlier snapshot. Conservative interior omits arrival/departure years.']});}
figure('hendrik-antoon-lorentz','netherlands-kingdom','Hendrik Antoon Lorentz','1879','1927','1853-07-18','1928-02-04','scientific','Theoretical physics and teaching at Leiden; scientific work at Haarlem from 1912.','Physicist working and teaching in the Netherlands.','Research on optics and electricity; the light-refraction work of 1878 already predates this relevance interval.',sources[5].id,'Leiden appointment 1878; Haarlem and continuing Leiden lectures from 1912; death 1928','Institutional biography documents local appointments and ongoing work. The 1904 transformation and later distinctions are not projected into 1880 or 1900.');
figure('pieter-zeeman','netherlands-kingdom','Pieter Zeeman','1898','1934','1865-05-25','1943-10-09','scientific','University of Amsterdam teaching and experimental physics.','Experimental physicist based at the University of Amsterdam.','Magnetic splitting of spectral lines discovered in 1896.',sources[6].id,'Amsterdam appointment 1897, retirement 1935; magnetic splitting 1896','Biography supplies both dated work and local institutional connection. Interior interval avoids uncertain appointment and retirement days. No citizenship or birthplace inference.');
figure('carl-spitteler','swiss-federal-state','Carl Spitteler','1893','1923','1845-04-24','1924-12-29','literary','Writer resident in Lucerne from 1892.','Poet and writer working in Lucerne.','Prometheus und Epimetheus, published in 1881, predates the relevance interval.',sources[7].id,'Life: Lucerne residence 1892; Work: first poetry collection 1881; death 1924','Nobel institutional facts distinguish Swiss residence from earlier work in Russia. No later Olympian Spring composition or prize projected into 1900.');
fs.writeFileSync(root+'cohort.json',JSON.stringify({id:'regional01-lowcountries-institutional-history',worker:'regional-lowcountries-worker',sources,claims},null,2)+'\n');
fs.writeFileSync(root+'review-notes.json',JSON.stringify({status:'submitted-for-independent-review',productionEdited:false,holds:[{case:'Batavian Republic 1800 capital',reason:'Municipal source dates Amsterdam capital to 1808; broad government pamphlet gives French era 1795–1813. Do not extend backward through conflicting chronology.'},{case:'Netherlands 1945 capital/constitutional framework',reason:'London exile and liberated Amsterdam applicability need transition review; preserved existing records.'},{case:'Luxembourg 1815',reason:'Within-year creation and unsettled constitutional/territorial applicability left unresolved.'},{case:'Switzerland neutrality',reason:'Already-supported status is not relabelled as a relationship for metric gain.'},{case:'Economy text',reason:'Current integrator requires numeric observations, not monetary-history interval prose; no schema workaround.'},{case:'Population, density, flags and held leadership',reason:'No compatible new statistical/flag/office evidence obtained within source effort.'}],categoryScope:'All cluster needs inspected; useful original histories harvested in capitals, treaty relationships, selected-year event and institutionally dated figures. Other categories stay unresolved.',limitations:'Nobel institutional sources yield science and literature only; diversity is not fabricated. No portraits. No full source pages mirrored; concise evidence locators and direct URLs retained.'},null,2)+'\n');
console.log(JSON.stringify({claims:claims.length,sources:sources.length}));
