import fs from 'node:fs';import crypto from 'node:crypto';
const out='research/five-category-01/east-asia';fs.mkdirSync(out+'/assets',{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));const registry=read('data/historical-entities.json');const audit=read('research/flagship-01/audit.json');
const old=[...read('data/historical-sources.json').sources,...read('data/comprehensive-dossiers.json').packages.flatMap(p=>p.sources||[])];const sources=[],claims=[],reviews=[];
function source(id,url,title,institution,locator,summary){const s=old.find(s=>s.url===url)||{id,url,title,institution,accessed:'2026-10-03',kind:'institutional-history',usage:'Selected factual paraphrases and dated original-source locators; no images or full copyrighted text redistributed.'};if(!sources.some(x=>x.id===s.id))sources.push(s);reviews.push({sourceId:s.id,url,bodyReviewed:true,reusedExactSourceObject:old.some(o=>o.id===s.id),locator,summary});return s.id;}
const jq=source('fc01-palace-jiaqing','https://www.dpm.org.cn/court/lineage/226238.html?hl=%E7%9A%87%E5%AE%AB','Jiaqing Emperor','Palace Museum, Beijing','Heading1796–1820 and biography paragraphs1–2; web172–185','Titular accession1796; personal government after Qianlong death1799;1800/1815 safely inside tenure. Lunar accession/death not converted.');
const cap=source('fc01-unesco-imperial-palaces','https://whc.unesco.org/en/list/439/','Imperial Palaces of the Ming and Qing Dynasties in Beijing and Shenyang','UNESCO World Heritage Centre','Description paragraphs1–2; Brief synthesis; web4–5,47–49','Qing moved capital to Beijing; Forbidden City seat of supreme power through1911; Shenyang became secondary/auxiliary seat. Bounded early nineteenth-century capital only.');
const edo=source('fc01-boj-edo-units','https://www.imes.boj.or.jp/cm/english/?appsule=11','Currency Museum: Edo-period currency units','Bank of Japan, Institute for Monetary and Economic Studies','FAQ What were the currency units used during the Edo Period(1603–1867)?; web97–103','Gold ryo/bu/shu, silver monme by weight, copper mon/kanmon; actual exchanges used market rates. Not a single unchanged rate or exclusive coin type.');
const pop=source('japan-census','https://www.stat.go.jp/english/data/nenkan/pdf/yhyou02.pdf','Population and Households','Statistics Bureau of Japan','Table2.1A PDF0:1900/1914 rows and population-definition heading; Table2.1B PDF1:1938 row; Table2.3 PDF4:1920/1945 Japan total and observation definitions; PDF19:1945Okinawa exclusion note','Dates and thousands conversion retained.1900/1914 estimates are Japanese nationals in Japan proper;1920de facto prefectural census;1938October population estimate;1945November survey excludes Okinawa. None is total imperial possessions.');
const flag=source('japan-flag-history','https://web-japan.org/factsheet/en/pdf/11NFlagAnthem.pdf','National Flag and Anthem','Ministry of Foreign Affairs of Japan, Web Japan','PDF1/printed2:1870commercial-vessel proclamation and1872government-building use; web83–93','Restoration-era Hinomaru relationship; no1999national-flag law projected backward; source uses lunar1870date.');
const assetSource=old.find(s=>s.id==='jp-1870');sources.push(assetSource);reviews.push({sourceId:assetSource.id,url:assetSource.url,bodyReviewed:false,reusedAcceptedEvidence:true,locator:'Accepted local assets/flags/jp-1870.svg and source licence record',summary:'Exact unchanged212-byte accepted historical7:10offset-disc SVG copied into isolated candidate assets; Public domain,Kahusi.'});
const yen=source('fc01-boj-balance-history','https://www.imes.boj.or.jp/research/papers/english/24-E-07.pdf','Bank of Japan Balance Sheet in1882–1955: Reassembled Data and Their Developments','Bank of Japan, Institute for Monetary and Economic Studies','PDF30–31/printed28–29:September1945–1952; September1945andJanuary1946banknote amounts inyen','Institutional research records yen banknotes throughout late1945;February1946old-note conversion is later and outside selected interval. No exclusive circulation or unchanged value assertion.');
const rmb=source('c01-prc-rmb-historical-series','https://www.zlb.gov.cn/2014-01/10/c_125984388.htm','Renminbi historical series','Central Government Liaison Office in Macao; Xinhua','Second series issue date/redenomination and thirdseries entry; web63–72,86–88; territorial exclusions45','Second series1955–1962,1newyuan=10000oldyuan; existing1956–1959coverage left1960gap. Taiwan excluded; Tibet adopted July1957.');
const nt=source('fc01-taiwan-currency-mof','https://museum.mof.gov.tw/eng/singlehtml/009e91624d7848449733665a5bc46832?cntId=40b0615d3772461288a3145b9c474187','Bank of Taiwan issues New Taiwan Dollar specimen note','Ministry of Finance, Republic of China(Taiwan)','Historical narrative47,52,60,63,65','NTdollar introduced15June1949 and continuing through1961; used for Taiwan transactions.2000formalcurrency status not back-projected.1945Taiwanese-yen continuity is source-backed but entitymappingtransition held.');
const I=(from,until)=>({kind:'interval',from,until,certainty:'exact'});const O=d=>({kind:'observation',observationDate:d,certainty:'exact'});
function add(key,entityId,category,value,temporal,refs,locator,description,extra={}){claims.push({id:'fc01-eastasia-'+key,entityId,category,value,temporal,scope:{id:entityId+'-'+key,description,relationship:category==='population-statistics'?'partial':'same'},sourceIds:refs,evidence:refs.map(sourceId=>({sourceId,locator,note:description+' Calendar bounds are research clipping; no accession, currency reform or capital move dated to January1.',precision:temporal.kind==='observation'?'day':'year',temporal,interpretation:'contextual'})),status:'supported',risks:[],qualifications:[description,'Existing accepted facts preserved; no raw-polygon sovereignty, complete territorial control, or leader-to-Figures inference.'],origin:{kind:'new-research',reference:'Five-category01 East Asia bounded official/reference source packet',sourceIdentifier:key},...extra});}
add('qing-jiaqing','qing-imperial-framework','leadership','Jiaqing Emperor',I('1800-01-01','1816-01-01'),[jq],'Heading1796–1820; biography accession/personal-rule paragraphs','Imperial office only; selected1800and1815snapshots safely inside tenure; no Gregorian lunar-date conversion.',{role:'Emperor'});
add('qing-early-beijing','qing-imperial-framework','capital','Beijing',I('1800-01-01','1816-01-01'),[cap],'Description Qing capital relocation and Beijing palace imperial seat','Qing primary imperial capital, with Shenyang separately an auxiliary/secondary imperial seat; not exclusive imperial residence or uniform administration.',{role:'Primary imperial capital'});
add('tokugawa-units','japan-tokugawa-framework','currency','Gold ryō (bu, shu); silver monme by weight; copper mon (kanmon)',I('1800-01-01','1816-01-01'),[edo],'Edo-period currency units FAQ','Tokugawa tri-metallic monetary system; selected1800/1815calendar interiors of museum1603–1867period. Local notes and market exchange coexisted; no fixed exchange rate asserted.',{metric:'monetary-unit'});
const svg=fs.readFileSync('assets/flags/jp-1870.svg');fs.writeFileSync(out+'/assets/jp-1870.svg',svg);const hash=crypto.createHash('sha256').update(svg).digest('hex');
add('restoration-hinomaru','japan-restoration-framework','historical-flag','Historic Hinomaru (1870 merchant-flag design)',I('1878-01-01','1881-01-01'),[flag,assetSource.id],'Web Japan1870commercial-vessel and1872government-building usage; accepted historicalasset','Hinomaru associated with restoration-era government buildings and commercial vessels; unchanged historical7:10offset-disc design.1878/1880interior snapshot clipping,not1999statutorydesignation.',{asset:'./research/five-category-01/east-asia/assets/jp-1870.svg',flagType:'Historical governmental and commercial-vessel flag',alt:'Historic Hinomaru with offset red disc,7:10ratio',license:'Public domain',attribution:'Kahusi',assetSourceIds:[assetSource.id],assetSha256:hash});
for(const [year,total,date,type,scope,locator] of [[1900,43847000,'1900-01-01','estimate','Japanese nationals in Japan proper; excludes imperial colonies.','Table2.1A/PDF0/1900row; headingJanuary1Japanese population'],[1914,52039000,'1914-01-01','estimate','Japanese nationals in Japan proper; excludes imperial colonies.','Table2.1A/PDF0/1914row; headingJanuary1Japanese population'],[1920,55963000,'1920-10-01','census','De facto prefectural Japan census; excludes imperial colonies.','Table2.3/PDF4/Japan1920column and censusdefinition'],[1938,71013000,'1938-10-01','estimate','October1population estimate for Japan proper; excludes imperial colonial possessions.','Table2.1B/PDF1/1938row; October1population definitions'],[1945,71998000,'1945-11-01','survey','De facto November1population survey of Japan excluding Okinawa and former imperial colonial possessions.','Table2.3/PDF4/Japan1945column; date/type definition; PDF19Okinawa exclusion']])add('japan-pop-'+year,year===1945?'japan-initial-allied-occupation':'japan-meiji-framework','population-statistics',total,O(date),[pop],locator,scope+' Published in thousands; multiplied by1000and remains rounded,not exact headcount.',{metric:'Population',unit:'persons',observationType:type,statisticalComparability:'PARTIAL_HISTORICAL_SCOPE',qualifications:[scope,'Partial homeland statistical scope, not total mapped Empire/occupation territory. Sourceprintedthousands converted to persons without inventing precision. Exact observation date retained; no year interpolation.']});
add('japan-yen-before-surrender','japan-meiji-framework','currency','Yen',I('1945-01-01','1945-09-02'),[yen],'1882–1955yen banking series; late1945monetary narrative','Japan proper monetary/banknote unit; fills uncurated1945pre-surrenderresearchsubset. Not all imperial possessions, military currency, exchange-value continuity or sole circulating note.',{metric:'monetary-unit'});
add('japan-yen-occupation','japan-initial-allied-occupation','currency','Yen',I('1945-09-02','1946-01-01'),[yen],'PDF31/printed29:September1945toJanuary1946yen note series','Japan proper banknote monetary unit under earlyoccupation;1946noteconversion lies outside thiscalendarclip. No claim that every Allied-administered island used identical currency.',{metric:'monetary-unit'});
add('prc-rmb-1960','china-prc-framework','currency','Renminbi (yuan;1955denomination)',I('1960-01-01','1961-01-01'),[rmb],'Secondseries1955issue/1:10000redenomination and thirdseries1962','PRC issuing administration monetary unit; Taiwan excluded. Source notes Tibet circulation from15July1957; no polygon-wide or exclusive circulation assertion.',{metric:'monetary-unit'});
add('taiwan-ntd-1960','china-republic-nationalist-framework','currency','New Taiwan dollar',I('1960-01-01','1961-01-01'),[nt],'1949reform,continuingtransactions and1961issuingdelegation paragraphs','Taiwan-area transaction currency issued by Bank of Taiwan in1960; not a claim of uniform circulation across all ROCclaimedterritory.2000legalcurrency enactment not projected backward.',{metric:'monetary-unit'});
const actualSourceWindows=new Map([[jq,I('1796','1820')],[cap,I('1644','1911')],[edo,I('1603','1867')],[flag,I('1870','1999')],[assetSource.id,I('1870','1999')],[yen,I('1882','1955')],[rmb,I('1955','1962')],[nt,I('1949','1961')]]);
const precisionHeld=[];
const statisticalCandidates=[];
for(let i=claims.length-1;i>=0;i--){const c=claims[i];if(c.id.endsWith('japan-yen-before-surrender')){precisionHeld.push({id:c.id,reason:'Pre-surrender1945exactdayframework clipping exceeds year/month precision of monetary source; no precisionpromotion.'});claims.splice(i,1);continue;}
 if(c.category==='population-statistics'){delete c.observationType;delete c.statisticalComparability;statisticalCandidates.push(c);claims.splice(i,1);continue;}
 if(c.temporal.kind==='interval'){if(c.id.endsWith('japan-yen-occupation')){c.temporal=I('1945-10','1945-12');for(const e of c.evidence){e.precision='month';e.temporal=I('1945-09','1946-01');}}else{c.temporal=I(c.temporal.from.slice(0,4),String(Number(c.temporal.until.slice(0,4))-1));for(const e of c.evidence)e.temporal=actualSourceWindows.get(e.sourceId);}}
 if(c.category==='historical-flag'){c.flag={asset:'./assets/flags/jp-1870.svg',type:'state flag',alt:c.alt,license:c.license,attribution:c.attribution,assetSourceIds:c.assetSourceIds,sha256:c.assetSha256};for(const k of ['asset','flagType','alt','license','attribution','assetSourceIds','assetSha256'])delete c[k];}
}
const cats=['historical-flag','population-statistics','capital','leadership','currency'];const groups=audit.rankedWorkload.filter(g=>['china','japan'].includes(g.id));const held=[];
function applicable(c,o){if(c.entityId!==o.entityId)return false;if(c.temporal.kind==='observation')return Number(c.temporal.observationDate.slice(0,4))===o.snapshotYear;return Number(c.temporal.from.slice(0,4))<=o.snapshotYear&&Number(c.temporal.until.slice(0,4))>=o.snapshotYear;}
const assessment=groups.flatMap(g=>g.occurrences.map(o=>({group:g.id,id:o.id,mapId:o.mapId,snapshotYear:o.snapshotYear,entityId:o.entityId,categories:Object.fromEntries(cats.map(cat=>{const old=o.categories[cat];const additions=claims.filter(c=>c.category===cat&&applicable(c,o)).map(c=>c.id);let action=additions.length?'bounded-source-proposal':old?.records?.length?'preserve-accepted-evidence':'hold';if(action==='hold'||['held','partial'].includes(old?.status)){let reason=/composite|map-region/.test(o.entityId||'')?'Composite/republican mapcontext: no uniform leader,capital,currency,flag or population implied.':cat==='population-statistics'?'No date-matching territorially compatible statistical observation verified; no nearest-year or modern-border fallback.':cat==='historical-flag'?'Dated exactdesign/entity relationship and licensedasset not verified; no modernflag fallback.':o.id==='entity-taiwan@1945'?'Japanese/ROC1945administrative transition requires separate dated mapping; no whole-year entity invented.':'Missingcell requires dated source/office/seat/unit relationship; difficultcell deferred after bounded source review.';held.push({id:o.id,category:cat,statusBefore:old?.status||'missing',reason});}return [cat,{statusBefore:old?.status||'missing',acceptedRecords:old?.records?.length||0,action,claimIds:additions}];}))})));
function readable(obj){if(Array.isArray(obj))return obj.map(readable);if(obj&&typeof obj==='object')return Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,typeof v==='string'&&['value','note','summary','locator','reason','description','alt','flagType'].includes(k)?v.replace(/([A-Za-z])(\d)/g,'$1 $2').replace(/(\d)([A-Za-z])/g,'$1 $2'):readable(v)]));return obj;}
const write=(name,obj)=>fs.writeFileSync(out+'/'+name,JSON.stringify(readable(obj),null,2)+'\n');
write('held-population-candidates.json',{status:'territorial-comparability-not-certified',claims:statisticalCandidates,sources:[sources.find(s=>s.id===pop)],reason:'Official Japan-proper/prefectural totals differ materially from mapped imperial possessions. Exact observation dates and original geography retained for independent review; no production claim or classC approval.'});write('cohort.json',{id:'five-category01-east-asia',worker:'five-category01-east-asia',claims,sources});write('source-review.json',{status:'root-independent-review-required',sources:reviews,claims:claims.map(c=>({id:c.id,sourceIds:c.sourceIds,locator:c.evidence[0].locator,scope:c.scope,precision:c.evidence[0].precision})),asset:{path:out+'/assets/jp-1870.svg',sha256:hash,sourceId:assetSource.id,license:'Public domain',attribution:'Kahusi'},notes:['Originalpopulation source bodies and definitions reviewed; no inherited sourceyear promoted to whole-year estimate.','Qing1800/1815overlap dated researchsubset; China1914/1945andJapan1945mapping chronology preserved.','No redistribution of WorldStatesmen/COWsources; no new browser or production pipeline.']});write('held.json',{cells:held,precisionHeld,statisticalCandidateIds:statisticalCandidates.map(c=>c.id),failedBodies:['CBCPDF screenshot/bodytext unavailable; superseded with successfully read Ministry of Finance HTML.','Taipei cityhistory bodyfetch failed; capitalTaipei1960held.','FirstJiaqing canonicalURL timeout; successful queryURL bodyread replaces it.'],hardHolds:['Taiwan1945mappingtransition','AllcompositeChineseleadership/capital cells','Qingcurrency/flags/population without exactterritorial/design evidence','Tokugawaleadership andflags without datedsource body']});write('assessment.json',{groups:['china','japan'],occurrenceCount:assessment.length,categoryCount:5,cellsAssessed:assessment.length*5,newClaims:claims.length,newProposalCells:assessment.reduce((n,o)=>n+Object.values(o.categories).filter(c=>c.claimIds.length).length,0),assessment});write('registry-patch.json',{mode:'proposal-only',entities:[],mappings:[],note:'No identity/mapping changes. Existingproduction facts and within-year transitions retained.'});console.log({claims:claims.length,sources:sources.length,occurrences:assessment.length,cells:assessment.length*5,held:held.length});

