import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {csv,productionHashes} from './export-dossier-workload.mjs';
const root=process.cwd(),directory=root+'/exports/dossier-workload';
const data=JSON.parse(fs.readFileSync(directory+'/workload.json','utf8'));
function parse(text){const rows=[];let row=[],start=0,quoted=false;const field=end=>{let v=text.slice(start,end);if(v.startsWith('"')&&v.endsWith('"'))v=v.slice(1,-1).replaceAll('""','"');return v;};for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"')i++;else quoted=!quoted;}else if(c===','&&!quoted){row.push(field(i));start=i+1;}else if(c==='\n'&&!quoted){row.push(field(text[i-1]==='\r'?i-1:i));rows.push(row);row=[];start=i+1;}}assert.equal(quoted,false);return rows;}
test('CSV quoting round-trips Unicode, commas, quotes and multiline values',()=>{assert.deepEqual(parse(csv([{a:'Iran, Persia',b:'é "quoted"\nline'}],['a','b'])),[['a','b'],['Iran, Persia','é "quoted"\nline']]);});
test('Complete occurrence/category product, current snapshots and Religion',()=>{const ids=new Set(data.cells.map(c=>c.cell_id));assert.equal(ids.size,data.cells.length);assert.equal(data.cells.length,data.metadata.eligibleOccurrences*15);assert.equal(data.metadata.categories.includes('density'),false);assert.equal(data.metadata.categories.includes('religion'),true);assert.deepEqual(data.metadata.snapshots,[1800,1815,1878,1880,1900,1914,1920,1930,1938,1945,1960]);const groups=new Map();for(const c of data.cells){const g=groups.get(c.occurrence_id)||new Set();g.add(c.dossier_category);groups.set(c.occurrence_id,g);}assert.equal(groups.size,data.metadata.eligibleOccurrences);for(const g of groups.values())assert.equal(g.size,15);});
test('Master and missing CSV exactly match lossless JSON cells/statuses',()=>{for(const [file,expected] of [['MASTER.csv',data.cells],['MISSING-ONLY.csv',data.cells.filter(c=>['MISSING','PARTIAL'].includes(c.current_status))]]){const [header,...rows]=parse(fs.readFileSync(directory+'/'+file,'utf8'));assert.equal(rows.length,expected.length);for(let i=0;i<rows.length;i++){assert.equal(rows[i].length,header.length);assert.equal(rows[i][header.indexOf('cell_id')],expected[i].cell_id);assert.equal(rows[i][header.indexOf('current_status')],expected[i].current_status);assert.deepEqual(JSON.parse(rows[i][header.indexOf('current_evidence')]),expected[i].current_evidence);}}});
test('Source provenance and observation dates are preserved',()=>{for(const cell of data.cells){for(const id of cell.source_ids)assert.ok(data.sourceIndex[id]);assert.deepEqual(cell.observation_dates,cell.current_evidence.filter(r=>r.actualTemporal?.kind==='observation').map(r=>r.actualTemporal));assert.ok(['A','B','C'].includes(cell.research_priority));}});
test('Production and runtime byte hashes remain identical to export baseline',()=>assert.deepEqual(productionHashes(root),data.metadata.inputHashes));
