import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';
import{context,root}from'./phase2-pipeline.mjs';
import{createMetadataIndex,validInYear,intervalBounds,dateBounds,observationsForYear}from'../historical-metadata.js';
const out=path.join(root,'development','coverage');
const c=context(),{db,registry,manifest,plan}=c,index=createMetadataIndex(db,registry),rawIds=new Set(manifest.identities.map(r=>r.stableMapId)),entityIds=new Set(db.entities.map(e=>e.id)),sourceIds=new Set(registry.sources.map(s=>s.id));
const R={generatedAt:new Date().toISOString(),scope:{fromYear:1800,untilYear:1960,annualYears:161,expectedRawIdentities:880,expectedPoliticalDenominator:401},inputHashes:{},errors:[],warnings:[],duplicateIds:{},missingReferences:[],invalidDates:[],invalidIntervals:[],unboundedIntervals:[],orphanEntities:[],orphanSources:{productionUnused:[],entireAuditUnused:[]},sourceExactURLDuplicates:[],sourceURLVariantCandidates:[],overlappingMappings:[],frameworkOverlapCandidates:[],sharedNameEntityCandidates:[],annual:{pairs:0,singleEntity:0,identityTransitions:0,noEntity:0,noFallbackChecks:0,filteredFacts:0,observationChecks:0,timelineContextFacts:0},mappingBoundary:{records:0,positiveChecks:0,negativeChecks:0},classification:{},perBatch:[],qualifications:['Resolver audit covers all880 raw identities for every calendar year1800–1960, independent of snapshot presence.','Annual identityPeriods may contain multiple historically successive frameworks; intra-year transition is not a same-day incompatible overlap.','Population/economy are observationsForYear carry-forward values, not interval-filtered political facts. Events/predecessors/successors are historical timeline context. Their source dates remain checked without requiring event date to equal selected year.','Overlapping different political identities/framework facts and shared-name profiles are review candidates, not automatic errors or merge instructions. Simultaneous offices can coexist.','URL variants are provenance review candidates; redirects/content equivalence are not verified by this offline helper.','Existence envelopes may contain researched gaps; facts and mappings are checked independently. No geometry determines sovereignty or succession.']};
const err=(type,data)=>R.errors.push({type,...data});
for(const f of['data/historical-entities.json','data/historical-sources.json','development/coverage/manifest.json','development/coverage/research-plan.json','historical-metadata.js','data-pipeline.js','app.js','index.html','styles.css'])R.inputHashes[f]=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex');
function duplicate(values){const m=new Map;for(const id of values)m.set(id,(m.get(id)||0)+1);return[...m].filter(([,n])=>n>1).map(([id,count])=>({id,count}));}
for(const[k,values]of Object.entries({entities:db.entities.map(x=>x.id),sources:registry.sources.map(x=>x.id),rawIdentities:[...manifest.identities.map(x=>x.stableMapId)]})){R.duplicateIds[k]=duplicate(values);for(const x of R.duplicateIds[k])err('duplicate-id',{kind:k,...x});}
if(rawIds.size!==880)err('raw-denominator-drift',{actual:rawIds.size,expected:880});
const productionUsed=new Set,allUsed=new Set;
function dates(o,label){for(const k of['validFrom','validUntil','asOf','date'])if(o[k]){const d=o[k],a=String(d).split('-').map(Number),[y,m=1,day=1]=a,t=new Date(Date.UTC(y,m-1,day));if(!/^\d{4}(-\d{2})?(-\d{2})?$/.test(d)||m<1||m>12||day<1||t.getUTCFullYear()!==y||t.getUTCMonth()!==m-1||t.getUTCDate()!==day)R.invalidDates.push({label,field:k,value:d});}if(o.validFrom||o.validUntil){const[a,b]=intervalBounds(o);if(!(a<b))R.invalidIntervals.push({label,from:o.validFrom,until:o.validUntil});if(!o.validFrom||!o.validUntil)R.unboundedIntervals.push({label,from:o.validFrom||null,until:o.validUntil||null});}}
function walk(v,label,production=false){if(Array.isArray(v)){v.forEach((x,i)=>walk(x,label+'['+i+']',production));return;}if(!v||typeof v!=='object')return;dates(v,label);if(v.sourceIds){for(const id of v.sourceIds){allUsed.add(id);if(production)productionUsed.add(id);if(!sourceIds.has(id))R.missingReferences.push({kind:'source',label,id});}}if(v.mapIds)for(const id of v.mapIds)if(!rawIds.has(id))R.missingReferences.push({kind:'relationship-mapId',label,id});for(const[k,x]of Object.entries(v))if(k!=='sourceIds'&&k!=='mapIds')walk(x,label+'.'+k,production);}
walk(db,'database',true);walk(plan,'researchPlan'); R.developmentReportsRead=[]; for(const f of fs.readdirSync(path.join(root,'development/coverage')).filter(f=>/^research-batch-\d+\.json$/.test(f))){const fp=path.join(root,'development/coverage',f);walk(JSON.parse(fs.readFileSync(fp,'utf8').replace(/^\uFEFF/,'')),'batchReport:'+f);R.developmentReportsRead.push(f);}
for(const m of db.mappings){if(!rawIds.has(m.mapId))R.missingReferences.push({kind:'mapping-raw',id:m.mapId,entityId:m.entityId});if(!entityIds.has(m.entityId))R.missingReferences.push({kind:'mapping-entity',id:m.entityId,mapId:m.mapId});}
for(const x of R.missingReferences)err('missing-reference',x);for(const x of R.invalidDates)err('invalid-date',x);for(const x of R.invalidIntervals)err('invalid-interval',x);
R.orphanEntities=db.entities.filter(e=>!db.mappings.some(m=>m.entityId===e.id&&rawIds.has(m.mapId))).map(e=>e.id);
R.orphanSources.productionUnused=registry.sources.filter(s=>!productionUsed.has(s.id)).map(s=>({id:s.id,url:s.url,usedInDevelopment:allUsed.has(s.id)}));R.orphanSources.entireAuditUnused=registry.sources.filter(s=>!allUsed.has(s.id)).map(s=>({id:s.id,url:s.url}));
function groups(list,key){const m=new Map;for(const x of list){const k=key(x);if(!m.has(k))m.set(k,[]);m.get(k).push(x);}return[...m];}
for(const[url,list]of groups(registry.sources,s=>s.url))if(list.length>1)R.sourceExactURLDuplicates.push({url,sourceIds:list.map(s=>s.id)});
function variant(s){try{const u=new URL(s.url);u.hash='';u.hostname=u.hostname.replace(/^www\./,'');u.pathname=u.pathname.replace(/\/$/,'');for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/.test(k))u.searchParams.delete(k);u.searchParams.sort();return u.href;}catch{return s.url;}}
for(const[key,list]of groups(registry.sources,variant))if(list.length>1&&new Set(list.map(x=>x.url)).size>1)R.sourceURLVariantCandidates.push({normalizedCandidate:key,sources:list.map(s=>({id:s.id,url:s.url}))});
const mappingGroups=new Map(groups(db.mappings,m=>m.mapId));
for(const[raw,ms]of mappingGroups)for(let i=0;i<ms.length;i++)for(let j=i+1;j<ms.length;j++){const a=ms[i],b=ms[j],aa=intervalBounds(a),bb=intervalBounds(b),start=Math.max(aa[0],bb[0]),end=Math.min(aa[1],bb[1]);if(start<end)R.overlappingMappings.push({mapId:raw,entityIds:[a.entityId,b.entityId],sameEntity:a.entityId===b.entityId,from:Number.isFinite(start)?new Date(start).toISOString().slice(0,10):null,until:Number.isFinite(end)?new Date(end).toISOString().slice(0,10):null,classification:a.entityId===b.entityId?'redundancy-candidate':'historically-incompatible-or-concurrent-identity-review'});}
for(const e of db.entities)for(const f of['politicalStatus','governments']){const rs=e[f]||[];for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++){const a=rs[i],b=rs[j],aa=intervalBounds(a),bb=intervalBounds(b);if(a.value!==b.value&&Math.max(aa[0],bb[0])<Math.min(aa[1],bb[1]))R.frameworkOverlapCandidates.push({entityId:e.id,field:f,records:[a,b],qualification:'Different simultaneous institutions are not automatically incompatible.'});}}
const fields=['names','flags','politicalStatus','capitals','governments','leaders','currencies','relationships','descriptions','area'];
for(const raw of rawIds)for(let year=1800;year<=1960;year++){R.annual.pairs++;const matching=(mappingGroups.get(raw)||[]).filter(m=>validInYear(m,year)),expected=[...new Set(matching.filter(m=>entityIds.has(m.entityId)).map(m=>m.entityId))],result=index.resolve(raw,year),periods=result.entity?[result]:result.identityPeriods||[],actual=[...new Set(periods.map(p=>p.entity?.id).filter(Boolean))];if(JSON.stringify(expected.sort())!==JSON.stringify(actual.sort()))err('resolver-identity-mismatch',{mapId:raw,year,expected,actual});if(!matching.length){R.annual.noFallbackChecks++;if(result.entity||periods.length)err('unmapped-fallback',{mapId:raw,year});}if(result.entity)R.annual.singleEntity++;else if(periods.length)R.annual.identityTransitions++;else R.annual.noEntity++;
for(const q of periods){if(!q.entity){err('period-without-entity',{mapId:raw,year});continue;}if(q.entity.existence&&!validInYear(q.entity.existence,year))err('entity-existence-outside-year',{mapId:raw,entityId:q.entity.id,year});for(const field of fields)for(const fact of q[field]||[]){R.annual.filteredFacts++;if(!validInYear(fact,year))err('returned-fact-outside-year',{mapId:raw,entityId:q.entity.id,year,field,fact});}for(const field of['population','economy']){const expectedObs=observationsForYear(q.entity[field],year);if(JSON.stringify(q[field]||[])!==JSON.stringify(expectedObs))err('observation-selection',{mapId:raw,entityId:q.entity.id,year,field});R.annual.observationChecks+=(q[field]||[]).length;}R.annual.timelineContextFacts+=(q.events||[]).length+(q.predecessors||[]).length+(q.successors||[]).length;}}
for(const m of db.mappings){R.mappingBoundary.records++;const[a,b]=intervalBounds(m),first=Number.isFinite(a)?new Date(a).getUTCFullYear():1800,last=Number.isFinite(b)?new Date(b-1).getUTCFullYear():1960;for(const year of new Set([first,last]))if(year>=1800&&year<=1960){R.mappingBoundary.positiveChecks++;const r=index.resolve(m.mapId,year),ids=r.entity?[r.entity.id]:(r.identityPeriods||[]).map(x=>x.entity?.id);if(!validInYear(m,year)||!ids.includes(m.entityId))err('mapping-boundary-positive',{mapping:m,year});}for(const year of new Set([first-1,last+1]))if(year>=1800&&year<=1960){R.mappingBoundary.negativeChecks++;if(validInYear(m,year))err('mapping-boundary-negative',{mapping:m,year});}}
const eligible=manifest.identities.filter(r=>['political-polity','dependent-administration'].includes(r.classification?.classification)),available=r=>r.snapshotYears.some(y=>!!index.resolve(r.stableMapId,y).entity),transitionAvailable=r=>r.snapshotYears.some(y=>{const x=index.resolve(r.stableMapId,y);return x.entity||(x.identityPeriods||[]).length;});R.classification={denominator:eligible.length,expectedDenominator:401,rawTotal:rawIds.size,totals:manifest.classification.totals,singleEntityAvailability:eligible.filter(available).length,availabilityIncludingTransitions:eligible.filter(transitionAvailable).length,manifestPoliticalCoverage:manifest.classification.politicalCoverage,qualified:'Availability in at least one source-present snapshot; neither coverage across all years nor complete dossiers.'};if(eligible.length!==401)err('political-denominator-drift',{actual:eligible.length});
for(const b of manifest.phase2Batches){const pr=plan.batchReviews?.[b.id];R.perBatch.push({id:b.id,order:b.order,title:b.title,assignedRaw:b.mapIds.length,reviewedRaw:b.mapIds.filter(id=>!!plan.reviews[id]).length,prerequisites:b.classificationPrerequisites,manifestState:b.state,planReviewState:pr?.state||null,report:pr?.report||null,completed:!!pr&&b.mapIds.every(id=>plan.reviews[id])});}
const labels=[];for(const e of db.entities)for(const n of e.names||[]){const key=String(n.value).split(/[—–]/)[0].normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(in|around|circa)\s+\d{4}.*/,'').replace(/[^a-z0-9]+/g,' ').trim();if(key.length>3)labels.push({key,e});}
for(const[name,rows]of groups(labels,x=>x.key)){const es=[...new Map(rows.map(x=>[x.e.id,x.e])).values()];if(es.length<2)continue;const ids=es.map(e=>e.id),batches=[...new Set(manifest.phase2Batches.filter(b=>db.mappings.some(m=>ids.includes(m.entityId)&&b.mapIds.includes(m.mapId))).map(b=>b.id))];R.sharedNameEntityCandidates.push({name,entityIds:ids,batches,frameworks:es.map(e=>({id:e.id,politicalStatus:e.politicalStatus,governments:e.governments})),qualification:'Shared normalized name only. Different colonial/constitutional/occupation frameworks must remain distinct; source-supported same-framework periods may warrant guarded reconciliation.'});}
if(R.orphanSources.productionUnused.length)R.warnings.push({kind:'sources-not-referenced-by-production-facts',count:R.orphanSources.productionUnused.length});if(R.orphanSources.entireAuditUnused.length)R.warnings.push({kind:'sources-unused-in-production-and-review-reports',count:R.orphanSources.entireAuditUnused.length});for(const f of['sourceExactURLDuplicates','sourceURLVariantCandidates','orphanEntities','overlappingMappings','frameworkOverlapCandidates','sharedNameEntityCandidates'])if(R[f].length)R.warnings.push({kind:f,count:R[f].length});R.state=R.errors.length?'structural-failures-require-review':'structural-checks-passed-review-candidates-reported';
fs.writeFileSync(path.join(out,'final-global-audit.json'),JSON.stringify(R,null,2)+'\n');
const md=['# Phase 2 global structural and temporal audit', '',`Run time: ${R.generatedAt}. State: ${R.state}. Input hashes are in the JSON report.`, '',`Annual checks: ${R.annual.pairs} raw/year pairs; ${R.annual.filteredFacts} interval-filtered facts; ${R.annual.noFallbackChecks} unmapped no-fallback checks. Boundary checks: ${R.mappingBoundary.positiveChecks} positive and ${R.mappingBoundary.negativeChecks} negative.`, '',`Structural errors: ${R.errors.length}. This helper does not validate historical source truth, fetch source pages, alter production or make corrections.`, '', '## Qualified counts',JSON.stringify(R.classification,null,2),'','## Batch completion',...R.perBatch.map(b=>`- ${b.id}: ${b.completed?'reviewed':'pending/incomplete'}; ${b.reviewedRaw}/${b.assignedRaw} assigned raws reviewed; ${b.planReviewState||'no checkpoint'}.`),'','## Review candidates',...R.warnings.map(x=>`- ${x.kind}: ${x.count}.`),'',...R.qualifications.map(x=>'- '+x),'','Full references, URL variants, orphan sources, overlap records and shared-name candidates are in final-global-audit.json. Final totals must be rerun after Batch21 and any separately justified audit corrections.'];fs.writeFileSync(path.join(out,'final-global-audit.md'),md.join('\n')+'\n');console.log(JSON.stringify({state:R.state,pairs:R.annual.pairs,errors:R.errors.length,warnings:R.warnings,files:[path.join(out,'final-global-audit.json'),path.join(out,'final-global-audit.md')]}));if(R.errors.length)process.exitCode=1;
