import fs from 'node:fs';
import { createHash } from 'node:crypto';
const dir='research/dossier-recovery-01/india';
const catalogue=JSON.parse(fs.readFileSync('research/sources/catalogue.json')).sources;
const reuse=['raj-parliament','raj-capital','raj-legislature','wavell','c01-raj-kmc-capital-history'];
const sources=reuse.map(id=>catalogue.find(s=>s.id===id));
sources.push({id:'dr01-india-curzon-govuk',url:'https://www.gov.uk/government/history/past-foreign-secretaries/george-curzon',title:'George Nathaniel Curzon — historical biography',institution:'UK Government, Foreign and Commonwealth Office',accessed:'2026-10-03',usage:'Historical biography body identifies Curzon as Viceroy of India 1899 to1905. Selected1900 whole-year subset only; no exact appointment day inferred.'});
sources.push({id:'dr01-india-pib-central-framework',url:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=1489909&lang=2&reg=48',title:'President addresses special session of both Houses of the Bihar Legislature',institution:'Press Information Bureau, Government of India',accessed:'2026-10-03',usage:'Read speech paragraphs40–41: the federal part of1935Act never operated; central government remained broadly under1919framework. Does not certify every1935provision or all provinces operating under elected ministries in1945.'});
const scope='British Indian central institutional government for the represented subcontinental regions. British India in the narrow administrative sense comprises directly administered territories; princely states retained distinct administrations under imperial relationships. This dossier does not equate the source polygon with uniform sovereignty, direct administration, or one territorial legal unit.';
const clip='Exact January boundaries delimit a verified whole-year research subset; they are not an appointment, creation, dissolution or constitutional commencement date.';
const claims=[]; const addEntities=[]; const addMappings=[];
function claim(y,key,category,value,ids,locators,metric,role){const entityId=`british-indian-government-core-${y}`;const temporal={kind:'interval',from:`${y}-01-01`,until:`${y+1}-01-01`,certainty:'exact'};const c={id:`dr01-india-${y}-${key}`,entityId,category,value,temporal,scope:{id:`${entityId}-institutional`,description:scope,relationship:'same'},sourceIds:ids,evidence:ids.map((sourceId,i)=>({sourceId,locator:locators[i],note:clip,precision:'day',temporal,interpretation:'contextual'})),status:'supported',risks:[],qualifications:[scope,clip],origin:{kind:'new-research',reference:'Dossier recovery01 India; read institutional source bodies; independent coordinator review required',sourceIdentifier:locators.join('; ')}}; if(metric)c.metric=metric;if(role)c.role=role;claims.push(c);}
for(const y of [1900,1945]){
 const entityId=`british-indian-government-core-${y}`;
 const ids=['raj-parliament'];
 addEntities.push({id:entityId,names:[{value:'British Indian government — institutional context',kind:'primary',validFrom:`${y}-01-01`,validUntil:`${y+1}-01-01`,sourceIds:ids,confidence:'documented',note:scope}],existence:{validFrom:`${y}-01-01`,validUntil:`${y+1}-01-01`,sourceIds:ids,note:clip+' '+scope}});
 addMappings.push({mapId:'entity-india',entityId,validFrom:`${y}-01-01`,validUntil:`${y+1}-01-01`,sourceIds:ids,displayName:'India — British Indian institutional context',note:scope+' '+clip});
 claim(y,'status','political-institutional','British imperial administration',['raj-parliament'],['End of Company rule, body paragraphs on1858 Crown takeover, Secretary of State and appointed viceroy'],'state-type');
 claim(y,'government','political-institutional','Secretary of State for India and Crown-appointed Viceroy and Governor-General',['raj-parliament'],['End of Company rule: Secretary of State advised by council; Crown appointment of governor-general/viceroy and governors'],'government-system');
 if(y===1900){
  claim(y,'leader','leadership','George Nathaniel Curzon',['dr01-india-curzon-govuk'],['Opening biographical paragraph: Viceroy of India1899–1905; source year precision, selected1900 wholly inside tenure'],undefined,'Viceroy and Governor-General');
  claim(y,'capital','capital','Calcutta (central colonial administrative seat)',['c01-raj-kmc-capital-history','raj-capital'],['A Walk Down Memory Lane: Calcutta elevated as capital1773, nineteenth-century Governor-General chronology','Opening history paragraph:1911 decision to shift capital from Calcutta to Delhi']);
  claim(y,'overview','overview','In1900, British India was administered under Crown authority through the Secretary of State and the appointed viceroy, Curzon. Calcutta served as the central administrative capital. The institutional account must be distinguished from the separate administrations of princely states.',['raj-parliament','dr01-india-curzon-govuk','c01-raj-kmc-capital-history','raj-capital'],['End of Company rule','Opening biographical paragraph','Capital1773 and nineteenth-century history','1911 transfer from Calcutta']);
 }else{
  claim(y,'legislature','political-institutional','Central legislature: Governor-General, Council of State and Legislative Assembly',['raj-legislature','dr01-india-pib-central-framework'],['Council of States Debates collection description,1919Act bicameral centre and debates1921–1946','Speech paragraphs40–41: central1919framework persisted;1935federal scheme never came into operation'],'government-system');
  claim(y,'leader','leadership','Lord Wavell',['wavell'],['South Asia research guide, PDFpage13 (zero-index12), Liddell Hart entry: Viceroy and Governor-General1943–1947; selected1945 wholly inside tenure'],undefined,'Viceroy and Governor-General');
  claim(y,'capital','capital','New Delhi (central colonial administrative seat)',['raj-capital'],['History body: new capital opened February1931; day-level inauguration not adopted']);
  claim(y,'overview','overview','In1945, British Indian central administration remained under the Crown-appointed viceroy, Wavell, with its administrative seat in New Delhi. Its central legislature continued the1919Act framework; the federation contemplated by the1935Act had never operated. These institutions do not establish uniform direct rule over princely states.',['raj-parliament','wavell','raj-capital','raj-legislature','dr01-india-pib-central-framework'],['End of Company rule','Liddell Hart entry,1943–1947','February1931 new capital opening','Council of States Debates description','Paragraph40: central framework and unimplemented federation']);
 }
}
const write=(name,o)=>fs.writeFileSync(`${dir}/${name}`,JSON.stringify(o,null,2)+'\n');
write('cohort.json',{id:'dossier-recovery01-india',worker:'empty-india',claims,sources});
write('registry-patch.json',{id:'dossier-recovery01-india-registry',worker:'empty-india',before:{db:createHash('sha256').update(fs.readFileSync('data/historical-entities.json')).digest('hex'),sources:createHash('sha256').update(fs.readFileSync('data/historical-sources.json')).digest('hex')},addEntities,addMappings,sources,policy:'Proposal only.1900/1945 whole-year institutional cores. Existing Republic mapping remains1950+; no1938mapping proposed. No stats/enrichment or production mutation.'});
write('held.json',{id:'dossier-recovery01-india-holds',held:[{mapId:'entity-india',snapshotYear:1938,status:'held',reason:'Raw India1938 geometry is around56.06–56.41E,25.46–26.24N, in the Musandam region rather than the Indian subcontinent. Institutional BritishIndia facts cannot resolve this raw region identity.',rawProperties:{NAME:'India',ABBREVN:'India',SUBJECTO:'India',BORDERPRECISION:3,PARTOF:'India'},rawFile:'research/completion-02/area/cache/world_1938.geojson',action:'Do not map to BritishIndian institutional core or Republic ofIndia. Requires independent territorial/source-label investigation.'},{mapId:'entity-india',snapshotYears:[1900,1945],status:'held',reason:'Polygon-wide sovereignty, boundary equivalence, princely-state direct administration and dependencies remain unresolved. Institutional core proposals are explicitly qualified and carry no area/population.'}]});
write('source-review.json',{id:'dossier-recovery01-india-source-review',reviewer:'empty-india-extractor',independent:false,requiresIndependentReview:true,accessed:'2026-10-03',bodyReviews:[{sourceId:'raj-parliament',url:sources.find(s=>s.id==='raj-parliament').url,locator:'End of Company rule; web body lines175–178',findings:['1858Crown takeover ended Company administrative powers.','Secretary of State advised by council; Crown-appointed governor-general/viceroy.']},{sourceId:'dr01-india-curzon-govuk',url:sources.find(s=>s.id==='dr01-india-curzon-govuk').url,locator:'Opening body paragraph, line59',findings:['Curzon was viceroy1899–1905;1900is an interior complete year.']},{sourceId:'wavell',url:sources.find(s=>s.id==='wavell').url,locator:'PDFpage13 (zero-index12), Liddell Hart entry, lines941–943',findings:['Wavell Viceroy and Governor-General1943–1947;1945is interior complete year.']},{sourceId:'raj-legislature',url:sources.find(s=>s.id==='raj-legislature').url,locator:'Council of States Debates body paragraph, line65',findings:['1919Act established bicameral centre: Governor-General, Council of State and Legislative Assembly; collection covers1921–1946.']},{sourceId:'dr01-india-pib-central-framework',url:sources.find(s=>s.id==='dr01-india-pib-central-framework').url,locator:'Speech paragraphs40–41, lines83–87',findings:['Central government broadly retained1919constitution;1935federal part never operated.','No claim that all1935provisions operated in1935 or that every province had elected ministries in1945.']},{sourceId:'raj-capital',url:sources.find(s=>s.id==='raj-capital').url,locator:'History body lines176–182',findings:['1911decision transferred capital from Calcutta toDelhi; new capital opened February1931.','Calcutta1900 jointly bounded by1773KMCstatus and1911transfer; NewDelhi1945 is interior post-opening period.']},{sourceId:'c01-raj-kmc-capital-history',url:sources.find(s=>s.id==='c01-raj-kmc-capital-history').url,locator:'A Walk Down Memory Lane, lines24–30',findings:['Calcutta capital1773; nineteenth-century governors-general and city history.']}],reusedSourcesExact:reuse,failedBodies:[{sourceId:'c01-raj-kmc-capital-end',reason:'KMCstatistics page returned internal error; omitted from claims. KMCcapital-history and NDMCtransfer bodies used instead.'}],rawReview:{files:[1900,1938,1945].map(y=>`research/completion-02/area/cache/world_${y}.geojson`),method:'Parsed India feature properties and initial coordinates;1938Gulf peninsula anomaly stops mapping.1900and1945 contain subcontinental coordinates, insufficient to establish detailed boundary legality.'}});
