import fs from 'node:fs';
import {digest,readContext,saveJSON} from '../../../scripts/research-common.mjs';
import {generateDossierJob,validateDossier,fields} from '../../../scripts/research-comprehensive.mjs';
import {mappingContent} from '../../../scripts/research-crosswalk.mjs';
const base='research/crosswalk-01/capitals',review=JSON.parse(fs.readFileSync(base+'/mapping-review.json'));
const original=JSON.parse(fs.readFileSync(review.inputs.original.path)).entities;
const source=JSON.parse(fs.readFileSync('research/completion-03/capitals/intake/cohort.json')).sources[0];
const registrySources=JSON.parse(fs.readFileSync('data/historical-sources.json')).sources;
const baseline=JSON.parse(fs.readFileSync('research/crosswalk-01/baseline.json')).rows;
const windows={ 'greek-1864-crowned-framework':['1878-01-01','1909-01-01'],'greek-1927-republican-framework':['1928-01-01','1933-01-01'],'greek-1952-crowned-framework':['1953-01-01','1961-01-01'],'b13-siam-absolute':['1800-01-01','1881-01-01'],'b13-indonesia-guided':['1960-01-01','1961-01-01'],'lithuanian-no-seimas-framework':['1930-01-01','1931-01-01'],'china-prc-framework':['1960-01-01','1961-01-01']};
const mappings=[],claims=[];
for(const r of review.reviews)for(const f of r.frameworks){
 const [from,until]=windows[f.entityId],period={from,until},statement=original[r.subject].claims.P36.find(s=>s.id===r.selectedStatementId),capital=r.queryRows.find(x=>x.binding.capital.value.endsWith('/'+r.capitalEntity)).binding.capitalLabel.value;
 const ids=[source.id,...f.sourceEvidence.map(s=>s.id)],ev=[{sourceId:source.id,locator:`${review.inputs.original.path}: ${r.statementInventory.find(s=>s.selected).locator}; original statement ${statement.id}; https://www.wikidata.org/wiki/${r.subject}#${statement.id}`},...f.sourceEvidence.map(s=>({sourceId:s.id,locator:`${review.inputs.sources.path}: ${s.locator}; accepted usage: ${s.usage}`}))];
 const mapping={id:'crosswalk01-capital-'+f.entityId,atlasEntityId:f.entityId,external:{dataset:'Wikidata original qualified P36',id:r.subject,name:r.cachedLabel},class:r.classification,period,fields:['capital'],territorial:{classification:r.classification==='A'?'EXACT':'QUALIFIED-COMPATIBLE',sourceScope:'National capital relationship of '+r.cachedLabel,atlasScope:f.names[0].value,differences:'Capital property only; no assertion of polygon congruence, territorial control, exclusive constitutional seat, or whole-government equivalence.',materialDifference:false},continuityEstablished:true,competingEntity:false,rationale:r.semanticAndRoleCaveat,evidence:ev,worker:'/root/southamerica_chile_sources'};
 mappings.push(mapping);
 const temporal={kind:'interval',...period,certainty:'exact'};
 claims.push({id:'crosswalk01-capital-'+f.entityId,entityId:f.entityId,category:'capital',value:capital,temporal,scope:{id:f.entityId+'-crosswalk-capital',description:mapping.territorial.sourceScope+' within the existing sourced framework; generic capital, role unspecified.',relationship:'compatible'},sourceIds:ids,evidence:[{...ev[0],note:`Original rank ${statement.rank}; original qualifiers ${JSON.stringify(statement.qualifiers)}. ${r.semanticAndRoleCaveat} Research interval is strictly bounded subset, not inception or whole regime continuity.`,precision:'day',temporal,interpretation:'direct'},...ev.slice(1).map(e=>({...e,note:r.semanticAndRoleCaveat,precision:'day',temporal,interpretation:'direct'}))],status:'supported',risks:[],qualifications:[r.semanticAndRoleCaveat,'Original source qualifier precision preserved literally in evidence; exact research subset boundaries do not relabel source inception. No exclusive or constitutional role asserted.'],origin:{kind:'bulk-candidate',reference:'Cached source only; original '+statement.id+'; independently reviewed identity/property evidence, root mapping approval pending',sourceIdentifier:r.subject+':'+statement.id},compatibility:mapping});
}
const sources=[source,...registrySources.filter(s=>claims.some(c=>c.sourceIds.includes(s.id)))];
const cohort={id:'crosswalk01-field-specific-dated-capitals',worker:'/root/southamerica_chile_sources',sources,claims};
saveJSON(base+'/cohort.json',cohort);saveJSON(base+'/mappings.json',mappings);
const slots=baseline.filter(r=>claims.some(c=>c.entityId===r.entityId&&c.temporal.from<=r.snapshotYear+'-01-01'&&c.temporal.until>=String(r.snapshotYear+1)+'-01-01')&&r.categories.capital.status!=='supported').map(r=>({entityId:r.entityId,snapshotYear:r.snapshotYear,priorStatus:r.categories.capital.status}));
saveJSON(base+'/yield.json',{candidateClaims:claims.length,candidateSlots:slots.length,slots,cohortHash:digest(cohort),mappingContentHashes:mappings.map(m=>({id:m.id,hash:digest(mappingContent(m))})),status:'Candidate only; B mapping review and cohort certificate await independent root approval.'});
const context=readContext();
saveJSON(base+'/schema-preview.json',claims.map(c=>{const period={from:c.temporal.from,until:c.temporal.until},job=generateDossierJob(c.entityId,period,context),pkg={schemaVersion:2,id:cohort.id+'-'+c.entityId,jobId:job.id,entityId:c.entityId,mapIds:job.mapIds,worker:{id:cohort.worker,assignmentType:'comprehensive-entity-period'},productionFingerprint:job.productionFingerprint,chronology:{calendar:'proleptic-gregorian',yearConvention:'astronomical'},period,claims:[c],sources:[],investigation:fields.map(category=>({category,status:category==='capital'?'partial':'unresolved',rationale:'Bounded cached-source mapping intake.',consultedSourceIds:category==='capital'?c.sourceIds:[],gaps:['Independent root review pending.']})),conflicts:[],provenance:{createdAt:'2026-10-03',method:'Candidate only',preservedPackageHashes:[]}};return {entityId:c.entityId,...validateDossier(pkg,job,context)};}));
console.log(JSON.stringify({claims:claims.length,slots:slots.length,cohortHash:digest(cohort)}));
