import fs from 'node:fs';
import crypto from 'node:crypto';
import {readContext,dateRange,digest} from '../../../scripts/research-common.mjs';
import {completionMatrix} from '../../../scripts/research-completion.mjs';
const b='research/completion-01/currency',ctx=readContext(),matrix=completionMatrix(ctx),ledger=JSON.parse(fs.readFileSync(`${b}/retrieval-ledger.json`));
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const sources=ledger.filter(s=>s.status==='retrieved').map(s=>({...s,id:`completion-currency-${s.id}`,kind:'official-institutional-historical-source',title:{'hkma-history':'Money Past and Present: Monetary Systems in Hong Kong’s History','cbsl-anniversary':'60th Anniversary Commemorative Volume: Currency issue, printedp90','cbk-currency':'Currency History','cbk-newsletter':'Central Bank of Kenya Newsletter, issue2: Evolution of the Kenyan Currency','ghana-currency':'Evolution of Currency in Ghana','ghana-bank-history':'63 Years of Central Banking in Ghana','fiji-history':'A History of Fiji’s Currency'}[s.id],institution:s.id.startsWith('hkma')?'Hong Kong Monetary Authority':s.id.startsWith('cbsl')?'Central Bank of Sri Lanka':s.id.startsWith('cbk')?'Central Bank of Kenya':s.id.startsWith('ghana')?'Bank of Ghana':'Reserve Bank of Fiji'}));
sources.push({id:'completion-currency-fiji-bank-history',title:'Our History',institution:'Reserve Bank of Fiji',kind:'official-institutional-historical-source',url:'https://www.rbf.gov.fj/our-history/',cachePath:`${b}/cache/fiji-bank-history.html`,sha256:hash(`${b}/cache/fiji-bank-history.html`)});
const families=[
 {id:'ceylon-decimal-rupee',value:'Rupee (Ceylon decimal unit;100 cents)',sourceIds:['completion-currency-cbsl-anniversary'],sourceFrom:'1872-03-17',sourceUntil:'1950-08-28',locator:'printed90/PDFpage101: inherited currency system and17March1872 decimalcoinage',entityIds:['ceylon-legislative-council-framework','ceylon-state-council-framework'],scope:'Contemporary Ceylon island currency; no modernSriLanka naming back-projection.',evidenceNote:'Official historical volume states decimal Ceylon copper coinage introduced17March1872 at100cents perrupee;1950CBSL inherited the colonial currency system. Introduction is decimal coinage, not necessarily the firstrupee or solelegal-tender date.'},
 {id:'hong-kong-silver-dollar',value:'Silver dollar (Hong Kong monetary system)',sourceIds:['completion-currency-hkma-history'],sourceFrom:'1863',sourceUntil:'1935',locator:'PDFpage2/printed5 onlylegal-tender1863;PDFpage4/printed7 silverstandard1863–1935',entityIds:['hong-kong-historical-administration'],scope:'Local Hong Kong monetary-system silver dollars; not modernHKD retrospectively projected.',evidenceNote:'Silver dollar declared onlylegal tender1863;local version issued1866; silverstandarduntil1935. Name and standard are distinct from9November1935 localHongKongdollar declaration.'},
 {id:'hong-kong-local-dollar-before-occupation',value:'Hong Kong dollar',sourceIds:['completion-currency-hkma-history'],sourceFrom:'1935-11-09',sourceUntil:'1941-01-01',locator:'PDFpage4/printed7 sterlinglink1935–1972 narrative',entityIds:['hong-kong-historical-administration'],scope:'Preoccupation localHongKongunit. Researchbound deliberately ends before1941occupation; no uninterruptedWWIIcurrency assertion.',evidenceNote:'Government declared localmonetary unit9November1935. Actualsource broader1935–1972 monetaryregime does not independently investigate wartimeoccupation.1941cutoff is conservative researchbound, not currencytermination.'},
 {id:'hong-kong-local-dollar-postwar',value:'Hong Kong dollar',sourceIds:['completion-currency-hkma-history'],sourceFrom:'1946-01-01',sourceUntil:'1972',locator:'PDFpages4/6 sterlinglink1935–1972 and1949devaluation',entityIds:['hong-kong-historical-administration'],scope:'Postoccupation localHongKongunit; excludes all1945transitionyear until separate evidence.',evidenceNote:'Source describes continuing sterling-linkedlocalunit through1972, explicitly discusses1949devaluation.1946start is researched interior afteroccupation, not invented legalintroduction.'},
 {id:'east-african-shilling',value:'East African shilling',sourceIds:['completion-currency-cbk-newsletter','completion-currency-cbk-currency'],sourceFrom:'1923-06',sourceUntil:'1962',locator:'CBKNewsletter printed20/PDFpage20: January1922 introduction andJune1923 establishedofficialcurrency;CurrencyHistory EACB currenciesusedtoindependence',entityIds:['kenya-colony-protectorate-prewar-core','kenya-1945-colonial-core','kenya-1960-colonial-core','uganda-colonial-pre1952-core','uganda-1960-reformed-colonial-core'],scope:'Explicit historical Kenya and Uganda EACB territory. Tanganyika sourcecoverage preserved but no matchingexisting1920sframework found; no Tanzaniafallback.',evidenceNote:'Commonunit introducedJanuary1922 and establishedbyJune1923 in namedKenya/Uganda/Tanganyika;source describesEACBcirculationthroughindependence.1962cutoff conservative beforefirstindependence inthis account, not legalwithdrawal.'},
 {id:'fiji-pound-notes',value:'Pound (Fiji notes; shillings and pence)',sourceIds:['completion-currency-fiji-bank-history','completion-currency-fiji-history'],sourceFrom:'1914',sourceUntil:'1969',locator:'OurHistory: firstPoundnotes1914, coins1934, decimaldollars1969;HistoryofCurrency correspondingparagraphs',entityIds:['fiji-british-colonial-core'],scope:'ColonyofFiji domesticnotecurrency; no claim that1914isfirststerlinguse or1934firstpound.',evidenceNote:'RBFdistinguishes1914Poundnotes from1934coinage. Britishpound/shilling/pencesystem remaineduntil1969decimalization. Yearprecision introduction preserved; no firstday invented.'},
 {id:'west-african-pound',value:'West African pound (shillings and pence)',sourceIds:['completion-currency-ghana-currency','completion-currency-ghana-bank-history'],sourceFrom:'1912',sourceUntil:'1958-01-01',locator:'63Years/Introduction namesGoldCoast,Nigeria,SierraLeone,Gambia;Evolution/Introduction WACBpoundcirculateduntilJuly1958',entityIds:['gold-coast-pre1925-councils-core','gold-coast-1930-chiefly-framework-core','gold-coast-post1935-authorities-core','b16-gold-coast-1926','b16-gold-coast-1955','sierra-leone-colony-protectorate-core','gambia-colony-protectorate-core','gambia-1945-governor-core'],scope:'NamedGoldCoast/SierraLeone/Gambia historicalWACBterritories; excludesNigeriawithoutreviewedframeworkandLiberia.',evidenceNote:'TwoofficialBoGhistories establish1912board andnamedservicearea andWACBpoundsuntil1958.1912isboardformation, not a certified firstcurrencyissue; cross-territory continuity is a REVIEWproposal, not automaticproduction.',reviewIssues:['1912isboardformation ratherthan sourcedfirstunitissue.','GoldCoastunitname and othercolonies servicearea require independent cross-source temporal review.']},
 {id:'ghana-pound',value:'Ghana pound (shillings and pence)',sourceIds:['completion-currency-ghana-currency'],sourceFrom:'1958-07-14',sourceUntil:'1965-07-19',locator:'Evolution/FirstIssueofNationalCurrency andBirthofCedi',entityIds:['ghana-1960-monarchical-core','ghana-1960-republic-core'],scope:'HistoricalindependentGhana nationalunit; currencydate separate from1960stateframeworktransition.',evidenceNote:'Source states14July1958 issue and19July1965cedireplacement. No modernGHSISOcode or exchangerate asserted.'}
];
const claims=[];
for(const f of families)for(const entityId of f.entityIds){const e=ctx.db.entities.find(e=>e.id===entityId);if(!e?.existence)throw Error('Missingboundedframework '+entityId);
 const fromBound=d=>dateRange(d)[d.length===10?0:1];
 const start=Math.max(fromBound(f.sourceFrom),fromBound(e.existence.validFrom));const end=Math.min(dateRange(f.sourceUntil)[0],e.existence.validUntil?dateRange(e.existence.validUntil)[0]:Date.UTC(1961,0,1));
 if(start>=end)continue;const from=new Date(start).toISOString().slice(0,10),until=new Date(end).toISOString().slice(0,10);
 const slots=matrix.rows.filter(r=>r.entityId===entityId&&r.categories.currency.status==='missing'&&start<=Date.UTC(r.snapshotYear,0,1)&&end>=Date.UTC(r.snapshotYear+1,0,1)).map(r=>({entityId,snapshotYear:r.snapshotYear,category:'currency',status:'missing',mapIds:r.mapIds}));if(!slots.length)continue;
 claims.push({id:`completion-currency-${f.id}-${entityId}`,category:'currency',metric:'historical-monetary-unit',value:f.value,entityIdSuggested:entityId,validFrom:from,validUntil:until,sourceLegalOrHistoricalFrom:f.sourceFrom,sourceLegalOrHistoricalUntil:f.sourceUntil,sourceIds:f.sourceIds,sourceLocator:f.locator,evidenceNote:f.evidenceNote,scope:f.scope,scopeClassification:'HISTORICALLY_MATCHING_SCOPE_PROPOSAL',mappingEvidenceIds:e.existence.sourceIds,frameworkBoundary:e.existence,clippingPolicy:'Conservative researchedinterior of originalsourceprecision andexistingframework. Sourceyear/monthprecision never re-described as exactlegalintroduction;1961cutoff isatlasresearchbound.',prioritySlots:slots,reviewIssues:f.reviewIssues||[],status:'historical-review'});
}
const heldResearch=[{family:'Portugalreal',reason:'OfficialhistoryPDF403; sourceclaim fromsearchalone prohibited.',url:'https://www.bportugal.pt/sites/default/files/anexos/pdf-boletim/201010_boletim_notas_moedas.pdf'},{family:'Paraguaypeso/guarani',reason:'OfficiallawfullPDF accessiblethroughwebreader(pp7–9,21–25), but originalbytecache blocked403. No inventedbodyhash or acceptedclaim. Preserve1885law/1943transition nuance.',url:'https://www.bcp.gov.py/documents/20117/0/El%2Br%C3%A9gimen%2Bmonetario%2Borg%C3%A1nico%2Bdel%2BPy.pdf/9572f61a-8eda-0568-1d52-1af631134437?t=1747142407871'},{family:'HongKong1945',reason:'Occupation/returntransition needsactualcurrencylegal/contextsource; monetaryregimetimeline alone insufficient.'},{family:'TanganyikaEACB',reason:'Sourceexplicitlynames territory, but noexistingmatchingpost1923framework; no modernTanzaniafallback.'}];
const result={schemaVersion:1,sources,families,claims,heldResearch,baselineDigest:digest(matrix),sourceBindings:sources.map(s=>({path:s.cachePath,sha256:s.sha256})),metrics:{sourceBodies:sources.length,familiesInvestigated:8,candidateClaims:claims.length,missingSnapshotSlots:new Set(claims.flatMap(c=>c.prioritySlots.map(s=>s.entityId+':'+s.snapshotYear))).size,claimsWithInitialReviewIssues:claims.filter(c=>c.reviewIssues.length).length},productionEdited:false,retrievalCosts:{sandboxSocketBlockedAttempts:9,initialActualHTTPAttempts:9,additionalRBFHistoryHTTPAttempts:1,additionalBCPLawHTTPAttempts:1,HTTPFailures:3,sourceBodyRetries:0}};
fs.writeFileSync(`${b}/candidate-tranche.json`,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({digest:digest(result),metrics:result.metrics}));
