import fs from 'node:fs';
import crypto from 'node:crypto';
import {readJSON,saveJSON,digest} from '../../../scripts/research-common.mjs';
const base='research/regional-09/andean/';
const db=readJSON('data/historical-entities.json'),registry=readJSON('data/historical-sources.json');
const store=readJSON('data/comprehensive-dossiers.json');
const known=[...registry.sources,...store.packages.flatMap(p=>p.sources||[])];
const sources=[],claims=[];
function source(id,title,institution,url){const old=known.find(s=>s.url===url)||known.find(s=>s.id===id);const s=old||{id,title,institution,url,accessed:'2026-10-03',kind:'historical-institutional-evidence',usage:'Original historical body read; attributed concise factual paraphrases only. Rendered-source evidence retained privately; no image or manuscript reproduction imported.'};if(!sources.some(x=>x.id===s.id))sources.push(s);return s.id;}
const ch=source('r09-andean-chile-money','Narrativa Histórica — Museo Numismático','Banco Central de Chile','https://www.museobancocentral.cl/narrativa_historica.html');
const ce=source('r09-andean-chile-escudo','1945–1959: Establecimiento del escudo','Banco Central de Chile centenary history','https://centenario.bcentral.cl/1945-1959.html');
const ec=source('r09-andean-ecuador-sucre','Sucre: la construcción del héroe','Banco Central del Ecuador, Museo Numismático','https://museodelamoneda.bce.fin.ec/index.php/museo/historia/item/218-sucre-la-construcci%C3%B3n-del-h%C3%A9roe.html');
const bo=source('r09-andean-bolivia-unit1863','26 — Decimal monetary law','Banco Central de Bolivia virtual numismatic museum','https://www.bcb.gob.bo/?q=content/26');
const br=source('r09-andean-bolivia-unit1962','48 — Boliviano to peso boliviano','Banco Central de Bolivia virtual numismatic museum','https://www.bcb.gob.bo/?q=content/48');
const bh=source('r09-andean-bolivia-bank-history','El Banco Central de Bolivia — Más de100 años de historia','Banco Central de Bolivia','https://www.bcb.gob.bo/?q=node/436');
const ve=source('r09-andean-venezuela-money','Moneda, by Eduardo Arcila Farías and Mercedes Carlota Pardo','Fundación Empresas Polar, Diccionario de Historia de Venezuela','https://bibliofep.fundacionempresaspolar.org/dhv/entradas/m/moneda');
const vh=source('b09-venezuela-caudillos','The Century of Caudillismo','Library of Congress Federal Research Division, HTML transcription','https://countrystudies.us/venezuela/5.htm');
const vt=source('b09-venezuela-transition','The Transition to Democratic Rule','Library of Congress Federal Research Division, HTML transcription','https://countrystudies.us/venezuela/6.htm');
const co=source('r09-andean-colombia-decimal','Moneda de un centavo y cuarto, catalogue NMO4718','Banco de la República cultural collections','https://colecciones.banrepcultural.org/es/documento/nmo-monedas/63a069155d96b8790f344b0b');
const cp=source('r09-andean-colombia-paper','Papel moneda en Colombia','Banco de la República, Banrepcultural encyclopedia','https://enciclopedia.banrepcultural.org/index.php?title=Papel_moneda_en_Colombia');
const pm=source('r09-andean-peru-monetary-series','CD12050DA — Oferta monetaria estimada, Soles Plata (millones)','Banco Central de Reserva del Perú, BCRPData','https://estadisticas.bcrp.gob.pe/estadisticas/series/anuales/resultados/CD12050DA/html');
const pc=source('r09-andean-peru-colonial-economy','The Colonial Economy','Library of Congress Federal Research Division, HTML transcription','https://countrystudies.us/peru/7.htm');
const pi=source('b09-peru-independence','Independence Imposed from Without','Library of Congress Federal Research Division, HTML transcription','https://countrystudies.us/peru/11.htm');
const treaty=source('r09-andean-chile-bolivia-treaty1904','Tratado de Paz i Amistad Chile–Bolivia,20 October1904','Biblioteca del Congreso Nacional de Chile, Ley Chile','https://www.bcn.cl/leychile/Navegar?idNorma=400123&idVersion=1905-03-27');
const interval=(from,until)=>({kind:'interval',from,until,certainty:'exact'});
const event=date=>({kind:'event',date,certainty:'exact'});
function add(key,eid,category,value,temporal,sids,locator,note,extra={}){
 const e=db.entities.find(x=>x.id===eid);if(!e)throw Error(eid);
 sids=Array.isArray(sids)?sids:[sids];
 claims.push({id:'r09-andean-'+key,entityId:eid,category,value,temporal,scope:{id:eid+'-r09-'+category,description:category==='economy'?'Historical Peru monetary-system aggregate as defined by BCRP series CD12050DA; not GDP, census territory or a constant-boundary territorial total.':'Named historical polity, monetary institution or bilateral treaty only; no modern-border, nationality or successor-state inference.',relationship:'same'},sourceIds:sids,evidence:sids.map(sourceId=>({sourceId,locator,note,precision:(temporal.date||temporal.observationDate||temporal.from).length===10?'day':(temporal.date||temporal.observationDate||temporal.from).length===7?'month':'year',temporal,interpretation:'direct'})),status:'supported',risks:[],qualifications:temporal.kind==='interval'?['Bounds are conservative editorial research coverage inside the existing entity envelope, not invented historical adoption or transition dates. Year endpoints remain partial.','Monetary unit is distinguished from minting, metal standard, physical coin replacement and exclusive issuer. No claim of sole circulating currency.']:['Actual source date and precision retained, including preceding context; no snapshot retiming or future event projection.'],origin:{kind:'new-research',reference:sids.join(';')},...extra});
}
const currency=(key,e,unit,from,until,sid,loc,note,extra={})=>add(key,e,'currency',unit,interval(from,until),sid,loc,note,extra);
currency('chile-late-peso','chile-late-1833-framework','Peso','1872','1890',ch,'1851–1894 decimal/private-bank section;1878 inconvertibility;1895 peso-oro law','The museum identifies peso denominations before and after the1878 standard change; only unit, not unchanged convertibility.');
currency('chile-parliament-peso','chile-parliamentary-practice-framework','Peso','1892','1923',ch,'1895–1925 fiscal-emission section','The unit remains peso;1895 gold-conversion rule and later state issues are distinguished.');
currency('chile-1945-peso','chile-restored-presidential-framework','Peso','1944','1946',ch,'1925–1959 Central Bank emissions;1959 replacement paragraph','Conservative coverage around1945 before escudo reform; no unchanged metal standard implied.');
currency('chile-1960-escudo','chile-restored-presidential-framework','Escudo','1960','1960',ce,'1959 Banco Central: Establecimiento del escudo','The source explicitly says circulation began1960 and old pesos persisted until around1964.',{qualifications:['Year-level onset1960 remains partial. Old pesos co-circulated; no exclusive instantaneous physical replacement.','Conversion1 escudo=1000 old pesos is contextual, not a current exchange-rate observation.']});
currency('ecuador-liberal-sucre','ecuador-1906-liberal-framework','Sucre','1913','1924',ec,'Sucre construction: paragraph moneda de curso legal1884–2000','The museum explicitly supplies the legal-tender period; this is bounded historical framework coverage.');
currency('ecuador-postwar-sucre','ecuador-postwar-civilian-framework','Sucre','1949','1960',ec,'Sucre construction: paragraph moneda de curso legal1884–2000','The museum explicitly supplies the legal-tender period; not dollarization back-projected.');
for(const [key,e,f,u]of [['bolivia-late-boliviano','bolivia-late-1880-constitutional-framework','1881','1921'],['bolivia-1945-boliviano','bolivia-1944-social-framework','1945','1945'],['bolivia-1960-boliviano','bolivia-post-revolution-framework','1957','1960']])currency(key,e,'Boliviano',f,u,[bo,br],'Museum26 law1863; Museum48 renaming decree13July1962','Original decimal boliviano and subsequent renaming establish bounded unit continuity; no1987 boliviano substituted.');
currency('venezuela-1878-venezolano','venezuela-guzman-framework','Venezolano','1872','1878',ve,'Siglo XIX:11May1871 unit; mandatory account conversion1January1872;31March1879 bolivar decree','The account unit was venezolano before the later bolivar; concurrent familiar peso accounting is not erased.');
for(const [key,e,f,u]of [['venezuela-1880-bolivar','venezuela-guzman-framework','1880','1887'],['venezuela-castro-bolivar','venezuela-castro-framework','1900','1907'],['venezuela-gomez-bolivar','venezuela-gomez-framework','1909','1921'],['venezuela-lopez-bolivar','venezuela-lopez-framework','1937','1940'],['venezuela-betancourt-bolivar','venezuela-betancourt-1959-framework','1960','1960']])currency(key,e,'Bolívar',f,u,ve,'31March1879 unit decree; Siglo XX gold-standard and1937–1960 parities','The named unit persists across changes in metal backing and issuance; no later redenomination applied.');
// FederalColombia legal unit interval retained in held.json: minted-object evidence is insufficient chronology.
add('chile-1878-inconvertibility','chile-late-1833-framework','events-context','Chile decreed the inconvertibility of banknotes into gold in1878.',event('1878'),ch,'Fiscal-emission paragraph: copper-price reduction1878','Original event year retained; reversal1895 is later.');
add('chile-1959-escudo-law','chile-restored-presidential-framework','events-context','Chile established the escudo as a new monetary unit in1959; circulation began in1960.',event('1959'),ce,'1959 Banco Central: Establecimiento del escudo','Legislation1959 and circulation1960 are separate dates.');
add('bolivia-1913-emission-law','bolivia-late-1880-constitutional-framework','events-context','Congress sanctioned legislation granting the Banco de la Nación Boliviana exclusive monetary emission on22December1913; the bank history identifies it as the law of1January1914.',event('1913-12-22'),bh,'Orígenes1911–1914, second paragraph','Legislative sanction is the recorded event, not an invented implementation day.');
add('bolivia-1928-bank-law','bolivia-late-1880-constitutional-framework','events-context','A law created the Banco Central de la Nación Boliviana on20July1928.',event('1928-07-20'),bh,'Consolidación institucional1928–1929, first paragraph','Legal creation is distinguished from renaming and operations.');
add('bolivia-1929-bank-operations','bolivia-late-1880-constitutional-framework','events-context','The Banco Central de Bolivia began activities on1July1929 after adoption of that name earlier in1929.',event('1929-07-01'),bh,'Consolidación institucional1928–1929, second paragraph','Actual operations date, not law-creation date.');
add('bolivia-1945-bank-departments','bolivia-1944-social-framework','events-context','In1945 the central bank was organized into Monetary and Banking Departments, respectively central-banking and commercial/industrial functions.',event('1945'),bh,'Hitos principales:1945','The year heading binds this internal organizational event.');
add('colombia-1880-bank-proposal','colombia-united-states-framework','events-context','A proposal to create a Banco Nacional was presented inMarch1880.',event('1880-03'),cp,'El Banco Nacional, opening paragraph','Proposal date only; not a claim that operation began that month.');
add('colombia-1959-note-printer','colombia-national-front-framework','events-context','The Banco de la República banknote printing works began with a one-peso note printed on12October1959.',event('1959-10-12'),cp,'Billete de1peso paragraph','Printed denomination and event date explicitly supplied.');
add('venezuela-1928-student-revolt','venezuela-gomez-framework','events-context','Student antigovernment speeches and arrests triggered protests inFebruary1928.',event('1928-02'),vh,'Student movement paragraph: revolt began inFebruary','Month binds initiating speeches/arrests; later palace action is not assigned an invented day.');
add('venezuela-1937-unions-ban','venezuela-lopez-framework','events-context','The López regime outlawed emerging labour unions in1937, alleging illegal political activity.',event('1937'),vt,'Paragraph beginning The regime justified','Source allegation attributed; no blanket judgement of illegality.');
for(const [key,e,y,v]of [['peru-money1878','peru-restored-1860-prewar-framework','1878',12.3],['peru-money1880','peru-pierola-wartime-framework','1880',18.2],['peru-money1900','peru-later-1860-framework','1900',78.5],['peru-money1914','peru-later-1860-framework','1914',180.3]])add(key,e,'economy',v,{kind:'observation',observationDate:y,certainty:'exact'},pm,'BCRPData CD12050DA, literal annual row'+y,'Source-produced historical monetary estimate; original displayed decimal/unit retained.',{metric:'Estimated money supply (BCRP historical series CD12050DA)',unit:'millions of silver soles',qualifications:['Annual source estimate, not census, GDP, modern soles or a statement of gold convertibility.','The source monetary aggregate is attributed to historical Peru; political-control/border changes are not translated into a territorial total. No atlas interpolation.']});
add('peru-viceroyal-lima','peru-late-viceroyal-framework','capital','Lima',interval('1800','1819'),[pc,pi],'Colonial Economy capital/administrative hub; Independence viceroy withdrawal fromLima July1821','Historical colonial centre supported across the named late-viceroyal research window.',{role:'Viceregal capital'});
add('chile-bolivia-peace-treaty','chile-parliamentary-practice-framework','relationships','Treaty of Peace and Friendship with Bolivia',interval('1906','1923'),treaty,'Treaty title,signature20October1904,publication27March1905,articleI','Standing treaty relationship only; not unchanged diplomatic staffing or border ownership.',{qualifications:['Conservative postpublication coverage; no ratification day inferred.','This is a treaty association, not a claim that friendly political relations or continuous diplomatic representation were guaranteed. Territorial clauses are not translated into polygon ownership.']});
add('bolivia-chile-peace-treaty','bolivia-late-1880-constitutional-framework','relationships','Treaty of Peace and Friendship with Chile',interval('1906','1934'),treaty,'Treaty title,signature20October1904,publication27March1905,articleI','Standing treaty relationship only, bounded by the existing historical administration.',{qualifications:['Conservative postpublication coverage; no ratification day inferred.','Treaty association, not continuous diplomatic representation or freedom from disputes. No ownership, status succession or modern territory inference.']});
const scopeHeld=claims.filter(c=>['economy','relationships'].includes(c.category));
saveJSON(base+'scope-held-source-observations.json',{method:'Literal source rows retained for further review; missing historical monetary jurisdiction or treaty-persistence proof prevents same-scope production claims.',claims:scopeHeld});
for(let i=claims.length-1;i>=0;i--)if(['economy','relationships'].includes(claims[i].category))claims.splice(i,1);
function prose(s){return s.replace(/\b(on|in|from|of|until|after|before|since)(?=\d)/g,'$1 ').replace(/\b(on|in|from|until)(?=January|February|March|April|May|June|July|August|September|October|November|December)/g,'$1 ').replace(/(\d{1,2})(January|February|March|April|May|June|July|August|September|October|November|December)/g,'$1 $2').replace(/([A-Za-zÀ-ÿ])(?=\d{4}\b)/g,'$1 ').replace(/(\b\d{4})(?=[A-Za-zÀ-ÿ])/g,'$1 ').replace(/BancoNacional/g,'Banco Nacional').replace(/Law50/g,'Law 50').replace(/100centavos/g,'100 centavos');}
for(const c of claims){if(typeof c.value==='string')c.value=prose(c.value);c.scope.description=prose(c.scope.description);c.qualifications=c.qualifications.map(prose);for(const e of c.evidence){e.locator=prose(e.locator);e.note=prose(e.note);}}
const used=new Set(claims.flatMap(c=>c.sourceIds));for(let i=sources.length-1;i>=0;i--)if(!used.has(sources[i].id))sources.splice(i,1);
saveJSON(base+'cohort.json',{id:'regional09-andean-source-families',worker:'regional09-andean-officeholder-sources',sources,claims});
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
saveJSON(base+'source-bindings.json',{cohortHash:digest({id:'regional09-andean-source-families',worker:'regional09-andean-officeholder-sources',sources,claims}),method:'Exact retained web-tool-rendered bodies/search extraction, not raw HTTPbytes. Restricted direct sockets; official/published source URLs and original locators retained. Source access failures are not source evidence.',bindings:['build.mjs',...fs.readdirSync(base+'cache').map(n=>'cache/'+n)].map(p=>({path:base+p,sha256:sha(base+p)})),entityRecordDigests:Object.fromEntries([...new Set(claims.map(c=>c.entityId))].map(id=>[id,digest(db.entities.find(e=>e.id===id))]))});
console.log(JSON.stringify({claims:claims.length,entities:new Set(claims.map(c=>c.entityId)).size,sources:sources.length,cohortHash:digest(readJSON(base+'cohort.json'))}));
