import fs from 'node:fs';
import {createHash} from 'node:crypto';
const dir='research/five-category-01/russia';
const group=JSON.parse(fs.readFileSync('research/flagship-01/audit.json')).rankedWorkload.find(g=>g.id==='russia-soviet');
const catalogue=JSON.parse(fs.readFileSync('research/sources/catalogue.json')).sources;
const sources=[catalogue.find(s=>s.id==='soviet-currency')];
const newSource=(id,url,title,institution,usage)=>{const s={id,url,title,institution,accessed:'2026-10-03',usage};sources.push(s);return id;};
const flagHistory=newSource('five01-russia-prlib-flags','https://www.prlib.ru/node/619479','Day of the State Flag of the Russian Federation — historical account','Presidential Library, Russia','Read body paragraphs on1858heraldic black-yellow-white flag and1896sole-state-status white-blue-red. Pre1858commercial/imperial distinctions are held; no modern state backprojection.');
const rsfsrHistory=newSource('five01-russia-prlib-rsfsr-flag','https://www.prlib.ru/history/619167','State flag of the RSFSR officially established','Presidential Library, Russia','Read1918decree and Constitution article90: red cloth with gold RSFSR letters or full inscription at upper hoist. Used only bounded1920institutional context, not USSR.');
const sovietHistory=newSource('five01-russia-prlib-soviet-flag','https://www.prlib.ru/sites/default/files/u535/den_gosudarstvennogo_flaga_rossiyskoy_federacii.pdf','State Flag Day historical exhibition','Presidential Library, Russia','Read PDFpage8 (zero-index7):1924USSRconstitution flag description red cloth, gold hammer/sickle and gold-edged red star;1936/1977did not fundamentally change description.');
const bankHistory=newSource('five01-russia-cbr-history','https://cbr.ru/eng/about_br/history/','History of the Bank of Russia','Bank of Russia','Read1922–1926monetary reform chronology and1947chervonets elimination. No gold convertibility or value-equivalence beyond specific historical statements.');
const assets=[
 {name:'ru-imperial-1858.svg',commons:'Flag_of_Russia_(1858–1896).svg',attribution:'Bernhard von Koehne; SVG contributors FDRMRZUSA, DanielPietroWiki2022 and Wikimedia Commons contributors',history:flagHistory},
 {name:'ru-imperial-1896.svg',commons:'Flag_of_Russia_(1896–1918).svg',attribution:'Sports9494; optimized SVG by Smasongarrison; Wikimedia Commons contributors',history:flagHistory},
 {name:'rsfsr-1918.svg',commons:'Flag_of_the_Russian_Soviet_Federative_Socialist_Republic_(1918–1925).svg',attribution:'Sergey Chekhonin; SVG by Pianist; subsequent Wikimedia Commons contributors including OwcaGierka',history:rsfsrHistory},
 {name:'ussr-1924.svg',commons:'Flag_of_the_Soviet_Union_(1924–1936).svg',attribution:'Supreme Dragon; Wikimedia Commons contributors',history:sovietHistory}
];
for(const [i,a] of assets.entries()){a.sourceId=newSource(`five01-russia-flag-asset-${i+1}`,'https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(a.commons),a.commons.replaceAll('_',' '),'Wikimedia Commons contributors','Unmodified SVG downloaded through Special:FilePath. File body, attribution and public-domain statements read; chronology independently assigned with Presidential Library bodies.');Object.assign(sources.at(-1),{license:'Public domain',attribution:a.attribution,assetUrl:'https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(a.commons)});a.sha256=createHash('sha256').update(fs.readFileSync(`${dir}/assets/${a.name}`)).digest('hex');}
const claims=[];
const qualification='Entity-associated state symbol or monetary instrument only. Not proof of uniform polygon control, legal sovereignty, exclusive currency circulation or empire-wide local practice.';
function add(id,entityId,category,value,from,until,ids,locators,extra={}){const temporal={kind:'interval',from,until,certainty:'exact'};claims.push({id:`five01-russia-${id}`,entityId,category,value,temporal,scope:{id:`${entityId}-five01-institutional`,description:qualification,relationship:'same'},sourceIds:ids,evidence:ids.map((sourceId,i)=>({sourceId,locator:locators[i],note:'January endpoints delimit selected verified interior calendar research subsets. They are not historical introduction, abolition or denomination-conversion dates. Original source historical precision is retained in the locator.',precision:'year',temporal,interpretation:'contextual'})),status:'supported',risks:[],qualifications:[qualification],origin:{kind:'new-research',reference:'Five-category01 Russia; original institutional bodies and Commons asset/licence review; independent coordinator review required',sourceIdentifier:locators.join('; ')},...extra});}
function flag(id,entityId,value,from,until,index,locator){const a=assets[index];add(id,entityId,'historical-flag',value,from,until,[a.history,a.sourceId],[locator,'Commons file Summary, Licensing and original unmodified SVG'],{flag:{asset:`./assets/flags/${a.name}`,type:id==='flag-heraldic'?'state symbol':'state flag',alt:value,license:'Public domain',attribution:a.attribution,assetSourceIds:[a.sourceId],sha256:a.sha256},qualifications:[qualification,'Representative licensed rendering of the described historical design; exact pigment standard or every physical historical flag is not asserted.']});}
flag('flag-heraldic','russian-imperial-core-pre1906','Black-yellow-white imperial heraldic-colours flag (ceremonial decoration)','1859-01-01','1883-01-01',0,'PresidentialLibrary1858heraldic-colours flag for solemn occasions; Commons1858–1883use. Not asserted to replace all commercial/naval flags.');
flag('flag-1900','russian-imperial-core-pre1906','White-blue-red state flag','1897-01-01','1901-01-01',1,'PresidentialLibrary1896sole state flag; selected1900interior of1896–1917imperial use.');
flag('flag-1914','russian-imperial-fundamental-laws-framework','White-blue-red state flag','1914-01-01','1915-01-01',1,'PresidentialLibrary1896state flag;1914is interior before monarchy ended. Does not assign unofficial imperial-standard-in-canton alternative.');
flag('flag-rsfsr1920','russian-soviet-civilwar-core-1920','RSFSR red flag with gold Cyrillic RSFSR lettering at upper hoist','1920-01-01','1921-01-01',2,'PresidentialLibrary1918Constitution article90;1920whole-year within1918–1925asset chronology. RSFSR, not future USSR.');
flag('flag-ussr1930','soviet-union','USSR red flag with gold hammer and sickle and gold-edged red star','1930-01-01','1931-01-01',3,'PresidentialLibraryexhibition PDFpage8:1924constitutional description; Commons1924–1936rendering. Existing1930SovietUnionmap identity retained.');
add('currency-1878','russian-imperial-core-pre1906','currency','Russian ruble; state credit-note denomination','1878-01-01','1879-01-01',['soviet-currency'],['Historical body paragraphs1839–1843replacement by state credit notes,1860snotes1–100rubles,1895–1897new gold-standard type;1878interior ruble-denominated credit-note period. No claim of silver/gold redemption in1878.']);
add('currency-1920','russian-soviet-civilwar-core-1920','currency','Ruble-denominated RSFSR settlement notes (sovznaks), alongside earlier notes','1920-01-01','1921-01-01',['soviet-currency'],['Early Soviet circulation paragraphs: tsarist and ProvisionalGovernment notes also used; first RSFSRsettlement notes1919in1–10000rubles; new designs1921.1920is an interior circulation year.']);
add('currency-1930-1938','soviet-union','currency','Soviet ruble and chervonets-denominated banknotes','1925-01-01','1939-01-01',[bankHistory,'soviet-currency'],['CBRchronology1922chervonets;1924ruble treasury notes and1926chervonets quotation ceased;1947chervonets abolished. Selected1930and1938interior.','Banknotehistorical body1920sUSSRtreasury notes/chervonets and1930snewtreasury/Gosbanknote designs;1938–1947treasury issues. No claim1938new series existed on1January.']);
const write=(name,o)=>fs.writeFileSync(`${dir}/${name}`,JSON.stringify(o,null,2)+'\n');
write('cohort.json',{id:'five-category01-russia',worker:'empty-india-russia',claims,sources});
write('assets.json',{assets:assets.map(a=>({...a,isolatedPath:`${dir}/assets/${a.name}`,proposedProductionPath:`assets/flags/${a.name}`,license:'Public domain',mutation:'unmodified download'})),review:'XML verified; no SVG scripts or external references; Commons rendition/colour precision limitations preserved.'});
const cats=['historical-flag','population-statistics','capital','leadership','currency'];
const held=[];
for(const o of group.occurrences){held.push({mapId:o.mapId,snapshotYear:o.snapshotYear,entityId:o.entityId,category:'population-statistics',reason:o.categories['population-statistics'].status==='held'?'Preserve existing population scope hold; no new polygon-compatible census total demonstrated.':'No safe census observation with independently matched geographic scope for this polygon/framework. No interpolation or modern-statistics backprojection.'});if([1800,1815].includes(o.snapshotYear))held.push({mapId:o.mapId,snapshotYear:o.snapshotYear,entityId:o.entityId,category:'historical-flag',reason:'Pre1858commercial ensign, personal imperial standard and state-symbol distinctions; held under easy-gain time cap. No national flag inferred from a merchant flag.'});}
write('held.json',{id:'five-category01-russia-held',held});
write('assessment.json',{id:'five-category01-russia-assessment',occurrences:group.occurrences.map(o=>({id:o.id,mapId:o.mapId,snapshotYear:o.snapshotYear,entityId:o.entityId,categories:Object.fromEntries(cats.map(category=>{const additions=claims.filter(c=>c.entityId===o.entityId&&c.category===category&&c.temporal.from<=`${o.snapshotYear}-01-01`&&c.temporal.until>`${o.snapshotYear}-12-31`).map(c=>c.id);return[category,{before:o.categories[category].status,decision:additions.length?'proposed addition':held.some(h=>h.snapshotYear===o.snapshotYear&&h.mapId===o.mapId&&h.category===category)?'held':'preserve supported evidence',claimIds:additions,existingRecordCount:o.categories[category].records.length}];}))})),categories:cats,occurrenceCount:group.occurrences.length,policy:'Capital and Leadership already supported for all11occurrences and not repeated. No population invention. Preserve existing accepted currency/flags.'});
write('source-review.json',{id:'five-category01-russia-source-review',reviewer:'empty-india-russia-extractor',independent:false,requiresIndependentReview:true,reusedExactSourceIds:['soviet-currency'],bodies:[{sourceId:'soviet-currency',url:sources[0].url,locators:['Bodylines39–43:creditnotes1839–1843,1860srubledenominations,1895–1897newtype','Bodylines46–54:earlySovietmix,1919settlementnotes,1921newdesigns','Bodylines54–58:USSRchervonets/treasuryissues;1930snewseries;1947reform'],limits:'No legal-tender exclusivity, redemption promise, monetary value comparison or precise day inferred.'},{sourceId:bankHistory,url:'https://cbr.ru/eng/about_br/history/',locators:['1922–1926chronology,lines247–278','1947chronology,lines386–387'],limits:'Used jointly to establish interior ruble/chervonets monetary-unit period; no foreign-exchangequotation interval treated as currencyabolition.'},{sourceId:flagHistory,url:'https://www.prlib.ru/node/619479',locators:['Bodylines45–47:merchanttricolour distinction,1858heraldicceremonialflag,1896sole-stateflag']},{sourceId:rsfsrHistory,url:'https://www.prlib.ru/history/619167',locators:['1918decree and JulyConstitutionarticle90body paragraph']},{sourceId:sovietHistory,url:'https://www.prlib.ru/sites/default/files/u535/den_gosudarstvennogo_flaga_rossiyskoy_federacii.pdf',locators:['PDFpage8(zero-index7),1924constitutionalflagdescriptionand1936continuity']}],assets,scope:'Symbols and monetary instruments tied to institutional entities, without uniform territorialcontrol.1930rawWhiteRussia retains alreadyacceptedSovietUnionidentity; no newmapping.',productionEdits:false});
