import {create,interval,event,observation} from './design-build.mjs';
const x=create(1),{pkg,source,claim,reuse,investigate,notes}=x;
for(const old of x.preserved.claims)reuse(old,old.temporal.from==='1925-05-12'?interval('1925-05-12','1933-01-01'):{...old.temporal,certainty:'exact'},'production-reuse');
// Both institutional bodies were reread: precise death/inauguration dates and later
// reelection establish the retained dates; Jan1 endpoints are research clipping.
for(const c of pkg.claims.filter(c=>c.category==='leadership'))for(const e of c.evidence)e.precision='day';
const constitution='b03-weimar-framework';
const econ=source('cp-dhm-depression','Die Weltwirtschaftskrise','Deutsches Historisches Museum','https://www.dhm.de/lemo/kapitel/weimarer-republik/industrie-und-wirtschaft/weltwirtschaftskrise','Read introduction and complete substantive sections on exports, unemployment, deflation and state crisis; dated nominal export figures, not GDP.');
const bruning=source('cp-dhm-bruning','Heinrich Brüning1885–1970','Deutsches Historisches Museum','https://www.dhm.de/lemo/biografie/heinrich-bruening','Read complete chronological biography; first cabinet ends7October1931 and final resignation30May1932.');
const kapp=source('cp-dhm-kapp','Lüttwitz-Kapp-Putsch1920','Deutsches Historisches Museum','https://www.dhm.de/lemo/kapitel/weimarer-republik/innenpolitik/luettwitz-kapp-putsch-1920','Read introduction and substantive March1920 attempted-coup/general-strike narrative.');
const ruhr=source('cp-dhm-ruhr','Ruhrbesetzung1923','Deutsches Historisches Museum','https://www.dhm.de/lemo/kapitel/weimarer-republik/aussenpolitik/ruhrbesetzung-1923','Read full substantive occupation, passive resistance and September1923 termination narrative.');
const dawes=source('cp-dhm-dawes','Dawes-Plan','Deutsches Historisches Museum','https://www.dhm.de/lemo/kapitel/weimarer-republik/aussenpolitik/dawesplan','Read complete substantive reparations-plan narrative and29August1924 Reichstag acceptance.');
const einstein=source('cp-nobel-einstein','Albert Einstein — Biographical','Nobel Foundation','https://www.nobelprize.org/prizes/physics/1921/einstein/biographical/','Complete indexed institutional biography read through search result; direct page403. Berlin residence1914–1933 and1920s unified-field work; no claim of institute-director accession date.');
claim('identity','identity','German Reich under the Weimar republican constitution',interval('1920','1932'),constitution,'Substantive paragraphs: parliamentary republic and constitutional continuity','Institutional source identifies the Reich as a parliamentary republic; Weimar is the constitutional framework, not a new modern-country fallback.',{origin:{kind:'production-reuse',reference:'data/historical-entities.json#germany-weimar-framework'}});
claim('legislature','political-institutional','The Reichstag had a four-year electoral term, legislated and controlled the budget; government depended on its confidence.',interval('1920','1932'),constitution,'Substantive paragraph beginning Die Weimarer Verfassung war','This is the constitutional arrangement rather than a claim that parliamentary accountability remained effective during presidential cabinets.',{metric:'constitutional-legislature',qualifications:['Formal constitutional powers; practice diverged after1930.']});
claim('presidential-powers','political-institutional','The directly elected Reich president had a seven-year term, dissolution powers and emergency-decree authority under Article48.',interval('1920','1932'),constitution,'Paragraph beginning Als starkes Gegengewicht','Office rules and emergency powers are grouped as one institutional claim, distinct from individual officeholders.',{metric:'constitutional-executive'});
claim('rights','political-institutional','The constitution guaranteed equality and personal, expression, assembly, petition and religious freedoms.',interval('1920','1932'),constitution,'Paragraph beginning Als klassische bürgerliche Grund- und Freiheitsrechte','Grouped constitutional rights; no assumption that legal guarantees were uniformly realised.',{metric:'constitutional-rights',qualifications:['Textual guarantees, not an assessment of actual enforcement.']});
claim('bruning','leadership','Heinrich Brüning',interval('1930-04','1931-09'),bruning,'1930 March30 and1931 October7 chronology entries','Safely clipped first-cabinet interval; source variants give28/30March appointment/formation, so accession day is not asserted.',{role:'Reich Chancellor',qualifications:['First Brüning cabinet, clipped to fully interior months; second cabinet not collapsed into this interval.','Hindenburg biography gives28March whereas Brüning biography gives30March; no exact accession day resolved here.']});
claim('kapp-event','events-context','The Lüttwitz-Kapp attempted coup occupied Berlin’s government district; bureaucratic refusal and a general strike helped defeat it.',event('1920-03-13'),kapp,'Substantive March13 narrative and conclusion','Recorded at the attempted coup onset; source describes its failure after four days.');
claim('ruhr-event','events-context','French and Belgian forces occupied the Ruhr, prompting government-backed passive resistance and worsening economic crisis.',event('1923-01'),ruhr,'Introduction and substantive resistance paragraphs','Month precision retained; no exact invasion day invented.');
claim('dawes-event','events-context','The Reichstag accepted the Dawes reparations plan.',event('1924-08-29'),dawes,'Substantive paragraph beginning Obwohl der Dawes-Plan','Acceptance date explicitly supplied; neither later Young Plan nor hypothetical end of sovereignty is inferred.');
for(const [year,value]of[['1929',13.5],['1932',5.7]])claim('exports-'+year,'economy',value,observation(year),econ,'Introduction: exports1929–1932','Museum historical comparison reports nominal German goods exports in billions of Reichsmark; retain year and rounding.',{metric:'goods-exports',unit:'billion Reichsmark',qualifications:['Retrospective institutional economic summary; nominal annual export value, not GDP or modern-equivalent money.','Source supplies rounded totals; no interpolation or claim of polygon-level attribution.']});
claim('einstein','important-figures','Albert Einstein — Berlin-based theoretical physicist',interval('1920','1932'),einstein,'Biographical paragraphs: Berlin residence and1920s research','Association rests on residence and scientific work in Berlin during the researched republic, not a timeless nationality list.',{figure:{personId:'albert-einstein',name:'Albert Einstein',categories:['scientist','physicist'],lifespan:{from:'1879-03-14',until:'1955-04-18'},relationship:'Resident researcher in Berlin; the source describes German citizenship1914–1933 and subsequent emigration. Swiss and later American associations are not projected away.',activity:'Worked on unified-field theory in the1920s while based in Berlin.',contribution:'Relativity and quantum-theory research; selected-period work concerns unified fields.'},qualifications:['Earlier relativity achievements are explicit context, not dated as new1920s discoveries.','Nobel biography indexed full body was readable; direct retrieval403 is recorded for independent review.']});
claim('overview','overview','After1929, the withdrawal of foreign credit, collapsing exports and deflationary policies deepened economic and parliamentary crisis.',interval('1930','1932'),econ,'Deflationspolitik and Staatskrise sections','Period-specific contextual interpretation summarises linked economic and political developments.',{origin:{kind:'production-reuse',reference:'Existing presidential-cabinet description enriched by cp-dhm-depression; excluded as synthesis from new-claim throughput'},evidence:[{sourceId:econ,locator:'Deflationspolitik and Staatskrise',note:'Contextual synthesis; separate dated economic observations carry numeric claims.',precision:'year',temporal:interval('1930','1932'),interpretation:'contextual'}],qualifications:['Contextual synthesis, not a separate new empirical measurement.']});
const gaps={
 'population-statistics':['No vetted1920–1932 census table with historical territorial footnotes recovered in this bounded pass; current Destatis series begins later.'],
 'area-statistics':['No compatible dated historical territorial area observation recovered.'],
 density:['Cannot derive without compatible population and area observations.'],
 'historical-flag':['DHM constitutional narrative mentions republican black-red-gold; official use/design dates and licensed asset were not independently established in this pass.'],
 relationships:['Ruhr occupation event does not establish a whole-entity dependent relationship; no independently mapped related-entity relationship proposed.']
};
for(const category of Object.keys(gaps))investigate(category,'unresolved','Applicable category investigated against catalogue, preserved package and source bodies; evidence is insufficient for a safe record.',category==='historical-flag'?[constitution]:category==='relationships'?[ruhr,dawes]:[],gaps[category]);
for(const category of ['identity','political-institutional','leadership','capital','currency','economy','events-context','overview','important-figures'])investigate(category,category==='leadership'||category==='currency'?'partial':'supported','Bounded sourced records supplied; source reuse and new evidence are distinguished.',[...new Set(pkg.claims.filter(c=>c.category===category).flatMap(c=>c.sourceIds))],category==='leadership'?['Other chancellors and1925 presidential interim remain gaps.']:category==='currency'?['Mark/Rentenmark1920–1924 transition not filled by a later Reichsmark fact.']:[]);
notes.push({sourceId:constitution,bodyReviewed:true,locator:'Complete substantive paragraphs before navigation duplicates',note:'Grouped formal institutional rules; formal constitution continued after1933, but no later-period facts enter this dossier.'},{sourceId:econ,bodyReviewed:true,locator:'Introduction and complete substantive sections',note:'Rounded exports13.5billion1929 and5.7billion1932; unemployment end date1933 is outside job and omitted.'},{sourceId:bruning,bodyReviewed:true,locator:'Complete biography1930–1932 entries',note:'First cabinet interval retained; October1931 reconstitution not smoothed.'},{sourceId:kapp,bodyReviewed:true,locator:'Introduction and substantive March narrative',note:'March13 onset and four-day defeat; no expanded casualties.'},{sourceId:ruhr,bodyReviewed:true,locator:'Introduction and complete occupation/resistance narrative',note:'January1923 precision; occupation not inferred from geometry.'},{sourceId:dawes,bodyReviewed:true,locator:'Complete substantive plan narrative',note:'August29 Reichstag approval.'},{sourceId:einstein,bodyReviewed:true,locator:'Complete institution-indexed search body; direct fetch403',note:'Berlin1914–1933;1920s research, birth/death chronology. Direct verification route limitation explicit.'});
x.save();
