import {create,interval,event,observation} from './design-build.mjs';
const x=create(3),{pkg,source,claim,reuse,investigate,notes}=x;
for(const old of x.preserved.claims)reuse(old,{...old.temporal,certainty:'exact'});
const recognition='b02-rok-recognition';
const rhee=source('cp-loc-rhee-era','South Korea: The Syngman Rhee Era1946–1960','US Library of Congress /1990 Country Study mirror','https://countrystudies.us/south-korea/11.htm','Read entire political, social and postwar-economic sections; use only1949–1959events/observations.');
const war=source('cp-loc-korean-war','South Korea: The Korean War1950–1953','US Library of Congress /1990 Country Study mirror','https://countrystudies.us/south-korea/10.htm','Complete historical war narrative read; invasion month and27July1953ceasefire are distinct from governmental territorial control.');
const pop=source('cp-loc-korea-population','South Korea: Population','US Library of Congress /1990 Country Study mirror','https://countrystudies.us/south-korea/33.htm','Read complete population chapter;1949count differs from archives table,1955rounded total; no late1980sforecasts projected backwards.');
const archive=source('cp-korean-archives-census','총조사 인구 추이 — census population trend','National Archives of Korea / Statistics Korea historical table','https://theme.archives.go.kr/next/populationPolicy/statisticsPopup_02.do','Read entire table and source line;1955population21502386, but territorial/citizenship denominator footnotes absent and1949count differs from LoC.');
const whanki=source('cp-whanki-biography','KIM Whanki — Biography and chronology','Whanki Foundation / Whanki Museum','https://whankimuseum.cafe24.com/en/kim-whanki/artist/','Read complete biography and chronology:1949judging,1952Busanexhibition,1952–55Hongikteaching,1954Seoulexhibition,1956Paris move and1959return.');
claim('identity','identity','Republic of Korea',interval('1949','1959'),recognition,'Recognition and diplomatic-relations sections','Existing recognised republican identity; no projection of present territorial control.',{origin:{kind:'production-reuse',reference:'data/historical-entities.json#korea-republic-1948'},qualifications:['Recognition statement records an independent state; wartime control varied and is not equated with legal territorial claims.']});
claim('seoul-reuse','capital','Seoul',interval('1949-01-01','1950-01-01'),recognition,'Recognition paragraph','Retained prewar seat only; no wartime continuity inferred.',{origin:{kind:'production-reuse',reference:'data/historical-entities.json#korea-republic-1948'}});
claim('rhee','leadership','Syngman Rhee',interval('1949','1959'),rhee,'Opening paragraph: Rhee regime1948–1960','Presidency dates support selected-period clip; no1960resignation date disputed here.',{role:'President',qualifications:['Research clip inside1948–1960tenure; not full accession/resignation chronology.']});
claim('presidential-election','political-institutional','The1952constitutional amendment replaced assembly selection of the president with popular election.',interval('1953','1959'),rhee,'Opening constitutional paragraphs','Rule recorded in fully interior post-amendment years, not projected into1949–1951.',{metric:'presidential-election-method'});
claim('term-limits','political-institutional','The1954amendment removed the term-limit barrier to Rhee’s continued presidential tenure.',interval('1955','1959'),rhee,'November1954constitutional-amendment paragraph','Political effect on the incumbent; no inference of a general timeless unlimited presidency.',{metric:'incumbent-presidential-term-limit',qualifications:['Source describes coercive/manipulated constitutional tactics, not an unqualified democratic mandate.']});
claim('land-reform','events-context','A land-reform law was enacted, enabling many tenant households to become small landowners.',event('1949-06'),rhee,'Society under Rhee: June1949land reform','Month precision supplied; numeric beneficiaries are not made into a census or interpolated yearly statistic.');
claim('war-onset','events-context','North Korean forces invaded the south; Seoul fell and South Korean forces retreated into the southeast.',event('1950-06'),war,'June1950invasion and southeastern retreat narrative','Month precision retained; no polygon-based inference of state extinction.');
claim('armistice','events-context','The Korean War ceasefire agreement was signed at Panmunjom.',event('1953-07-27'),war,'War termination paragraph','Ceasefire context affects the republic; does not say its government signed the armistice or that a peace treaty ended the conflict.');
claim('popular-election-amendment','events-context','Rhee forced through a constitutional amendment for popular presidential election during the wartime political crisis.',event('1952'),rhee,'1952martial-law/amendment/election sequence','Exact amendment day absent; year precision preserves the distinction from later institutional coverage.');
claim('recognition','events-context','The United States recognised the Republic of Korea as an independent state.',event('1949-01-01'),recognition,'Recognition paragraph','Dated recognition, not establishment of the republic or proof of control over the entire peninsula.');
claim('hwan-reform','events-context','The won-to-hwan reform at100won to1hwan took effect.',event('1953-02-17'),'c02-bok-hwan','Timeline:15Februaryannouncement,17Februaryeffective date','Source explicitly separates announcement and implementation; proposed transition event supplements preserved safe interior currency intervals.',{qualifications:['Bank page introduction ambiguously labels reform numbers; this claim uses denomination and effective date only.']});
claim('aid-budget','economy',58.4,observation('1956'),rhee,'Postwar Economy: budget-aid paragraph','Foreign aid share of total government budget in1956; a fiscal observation, not GDP.',{metric:'foreign-aid-share-of-government-budget',unit:'percent',qualifications:['Retrospective country-study fiscal figure; source’s total-budget denominator, not national income.','No currency conversion or interpolation across neighbouring years.']});
claim('population1955','population-statistics',21502386,observation('1955'),archive,'1955row and Statistics Korea source line','Retained as a partial historical census-table observation; table does not explain territorial/citizenship inclusions.',{metric:'census-population-reported-in-archive-table',unit:'persons',status:'partial',risks:['statistical-scope-unresolved'],scope:{id:'korea-1955-census-table',description:'1955census total in National Archives retrospective Statistics Korea table; exact enumeration geography/citizenship inclusions not documented here.',relationship:'uncertain'},qualifications:['Table spans pre-partition and post-partition geography without full explanatory footnotes; do not identify count with a map polygon.','Source gives year only; no invented census day.','1949table total20166756differs from LoC20188641; original census definitions require review.']});
claim('whanki','important-figures','Kim Whanki — painter and art educator active in the republic',interval('1949','1955'),whanki,'Biography and chronology1949,1952–1955entries','Selected-period exhibition and teaching activity establish entity relevance;1956Paris emigration is not silently included as domestic residency.',{figure:{personId:'kim-whanki',name:'Kim Whanki',categories:['painter','art-educator'],lifespan:{from:'1913',until:'1974'},relationship:'Artist and teacher participating in the republic’s art institutions, with exhibitions in Busan and Seoul; prior colonial-era career is distinct context.',activity:'Judged the1949National Art Exhibition, exhibited in Busan1952and Seoul1954, and taught at HongikUniversity1952–1955.',contribution:'Advanced modern painting and abstraction through teaching and exhibitions.'},qualifications:['Only1949–1955domestic institutional activity claimed; Paris1956–1959and NewYork after1963are not shown as continuous domestic residency.','Museum dates professor/dean together; no exact dean accession inferred.']});
const gaps={
 'historical-flag':['Recognition site labels its image a modern flag; no historical asset/design/licensing inference from that image.'],
 'area-statistics':['No dated1950sarea observation with territorial/control qualifications verified; current territory cannot supply wartime scope.'],
 density:['No compatible1955population/area pair; partial census denominator remains unresolved.'],
 relationships:['Military assistance and recognition do not establish a dependency; no sourced interval with independently resolved related-entity mapping proposed.']
};
for(const [category,g]of Object.entries(gaps))investigate(category,'unresolved','Applicable category investigated against preserved sources and full country-study bodies; no unsupported fallback.',category==='historical-flag'?[recognition]:category==='relationships'?[war,recognition]:[pop,archive],g);
for(const category of ['identity','political-institutional','leadership','capital','currency','population-statistics','economy','events-context','important-figures'])investigate(category,['capital','currency','population-statistics'].includes(category)?'partial':'supported','Sources support bounded claims; temporal clips and held statistical uncertainty are explicit.',[...new Set(pkg.claims.filter(c=>c.category===category).flatMap(c=>c.sourceIds))],category==='capital'?['Wartime government-seat chronology deliberately remains unresolved.']:category==='currency'?['1949currency mix and exact1953intervals not automatically filled by preserved interior facts; effective reform event separately evidenced.']:category==='population-statistics'?['1955enumeration scope and1949discrepant totals require original census review.']:[]);
investigate('overview','partial','Full country-study wartime/postwar context reviewed; supported developments remain in independently dated events and observations rather than a redundant aggregate counted as a new fact.',[rhee,war],['A wider overview must distinguish changing authority and war years; no all-period generic summary proposed.']);
pkg.conflicts.push({description:'1949population totals differ: National Archives20166756 versus LoC20188641. No1949population claim accepted;1955table denominator remains a held review issue.',claimIds:[pkg.claims.find(c=>c.id.endsWith('-population1955')).id]});
notes.push({sourceId:rhee,bodyReviewed:true,locator:'All25lines, including Society under Rhee and Postwar Economy',note:'1948–1960presidency,1952electionmethod,1954termlimit,1949landreform,1956budgetaid58.4percent;1960facts excluded.'},{sourceId:war,bodyReviewed:true,locator:'Entire13line historical chapter',note:'June1950invasion and27July1953ceasefire; do not imply ROKsigned or war permanently ended.'},{sourceId:recognition,bodyReviewed:true,locator:'Complete recognition/diplomatic relations paragraphs',note:'Independent recognition1January1949; site image is explicitly modern and not historical flag evidence.'},{sourceId:'c02-bok-won',bodyReviewed:true,locator:'1950–1953substantive narrative and note tables',note:'Multiple note issuers/circulation in wartime;June12versus displayedDecember6bank establishment inconsistency omitted.'},{sourceId:'c02-bok-hwan',bodyReviewed:true,locator:'1953–1962narrative and15/17Februarytimeline',note:'100won→1hwan,effective17February1953; no modern1962won backprojection.'},{sourceId:pop,bodyReviewed:true,locator:'Entire population chapter; trends paragraph',note:'1949total20188641;1955rounded21.5million; later1980sseries and forecasts excluded.'},{sourceId:archive,bodyReviewed:true,locator:'Complete table including source line',note:'1955total21502386; no geographic/foreign-citizen footnotes. Historical review remains required.'},{sourceId:whanki,bodyReviewed:true,locator:'Complete biography and chronology lines112–168',note:'Domestic1949–1955activities separately bounded from Paris1956–1959and laterNewYork; no portrait acquired.'});
x.save();
