import {create,interval,event,observation} from './design-build.mjs';
const x=create(2),{pkg,source,claim,reuse,investigate,notes}=x;
reuse(x.preserved.claims[0],interval('1908','1914'));
const laws='b06-russian-fundamental-laws';
const capital=source('cp-prlib-capital-history','Ленинграду возвращено имя Петра','Presidential Library of Russia','https://www.prlib.ru/node/619516','Read full substantive history: capital1732–1918 and dual-calendar1914 renaming; no modern capital fallback.');
const rename=source('cp-prlib-petrograd','Санкт-Петербург переименован в Петроград','Presidential Library of Russia','https://www.prlib.ru/history/1983280','Read complete substantive article by direct HTTP;18August old style/31August Gregorian1914 renaming, retained until1924.');
const bank=source('cp-cbr-imperial-history','History of the Bank of Russia','Bank of Russia','https://www.cbr.ru/eng/about_br/history/','Read substantive imperial chronology:1897gold standard,1913bank lending share,1914gold-conversion suspension; no Soviet or modern currency back-projection.');
const stolypin=source('cp-prlib-stolypin-office','П. А. Столыпин — Деятельность','Presidential Library of Russia','https://www.prlib.ru/node/675618','Read named office section with explicit1906–1911tenure and linked contemporary documents; year-interior clip avoids unspecified old-style dates.');
const lena=source('cp-prlib-lena','Произошли трагические события на Ленских золотых приисках','Presidential Library of Russia','https://www.prlib.ru/history/619175','Read complete substantive article and bibliographical qualifications:4/17April1912 troops fired on workers; casualties explicitly variable.');
const pavlov=source('cp-nobel-pavlov','Ivan Pavlov — Biographical','Nobel Foundation','https://www.nobelprize.org/prizes/medicine/1904/pavlov/biographical/','Full body read via direct HTTP after web403:1890department directorship,1895–1925physiology chair,1907Russian Academy election and conditioned-reflex research.');
claim('identity','identity','Russian Empire within the1906 Fundamental Laws framework',interval('1908','1914'),laws,'Articles4,7,25,86','Bounded institutional identity; no claim to establish full imperial lifetime.',{origin:{kind:'production-reuse',reference:'data/historical-entities.json#russian-imperial-fundamental-laws-framework'}});
claim('framework','political-institutional','The emperor retained supreme power and appointed ministers; legislation required imperial approval and participation of both chambers.',interval('1908','1914'),laws,'Articles4,7,9,17,86','Core framework already present in production; reuse excluded from throughput.',{metric:'government',origin:{kind:'production-reuse',reference:'data/historical-entities.json#russian-imperial-fundamental-laws-framework'}});
claim('legislative-composition','political-institutional','The State Council combined appointed and elected members; the Duma was elected for five years, with annual convocation and sessions controlled by imperial decrees.',interval('1908','1914'),laws,'Articles98–101','Grouped representation and session rules; no universal suffrage or equal electoral representation inferred.',{metric:'legislative-composition',qualifications:['Statutory structure, not a claim of democratic sovereignty.']});
claim('religion','political-institutional','Orthodoxy was the established imperial faith; the emperor upheld it and church administration operated through the Holy Synod, while other faiths were legally permitted worship.',interval('1908','1914'),laws,'Articles62–67','Church-state framework and qualified legal toleration are grouped; enforcement is not inferred.',{metric:'religious-institutional-framework',qualifications:['Legal text, not an assurance of equal treatment or complete religious freedom in practice.']});
claim('civil-rights','political-institutional','The laws protected property and domicile and prescribed legal arrest and prosecution; expression and peaceful assembly remained subject to legal restrictions.',interval('1908','1914'),laws,'Articles72–79','Grouped legal guarantees with restrictions; imperial autocracy is not rewritten as modern liberal democracy.',{metric:'civil-legal-framework',qualifications:['Formal guarantees; their actual enforcement requires distinct evidence.']});
claim('stolypin','leadership','Pyotr Stolypin',interval('1908','1910'),stolypin,'Office section: Председателя Совета министров Российской империи1906–1911','Interior years are supported by explicit office tenure; no Julian date silently treated as Gregorian.',{role:'Chairman of the Council of Ministers',qualifications:['1906–1911 full tenure is source context; research record safely clips before the1911 transition.']});
const oldCapital=claim('st-petersburg','capital','Saint Petersburg',interval('1908-01-01','1914-08-31'),capital,'Capital chronology paragraph and dual-calendar1914 rename','1732–1918 capital continuity; Gregorian renaming date explicitly paired with Julian date.',{role:'Imperial capital',sourceIds:[capital,rename],qualifications:['Research start is a clip, not the city’s establishment as capital.']});
oldCapital.evidence=[{sourceId:capital,locator:'Capital history and dual-calendar rename paragraphs',note:'Explicit capital1732–1918 and18/31August1914rename; January1908 is a research clip.',precision:'day',temporal:interval('1908-01-01','1914-08-31'),interpretation:'direct'},{sourceId:rename,locator:'Complete article:18(31)August1914',note:'Name changes on31August Gregorian1914; no geometrical inference.',precision:'day',temporal:interval('1908-01-01','1914-08-31'),interpretation:'direct'}];
claim('petrograd','capital','Petrograd',interval('1914-08-31','1915-01-01'),rename,'Renaming decree and continued usage through1924','Capital’s name changed; year-end is clipping and not a governmental move.',{role:'Imperial capital',sourceIds:[rename,capital],qualifications:['Gregorian date retained from explicitly dual-calendar source; same city, not a new state.']});
claim('ruble-gold','currency','Ruble under the imperial gold standard',interval('1908','1913'),bank,'Chronology1897 and1914 entries','1897reform establishes gold standard;1914war suspends conversion. Selected interval stops before wartime monetary change.',{qualifications:['Denomination/monetary standard; not a modern exchange-rate equivalent.']});
claim('gold-suspension','events-context','The State Bank suspended exchange of banknotes for gold after the outbreak of the First World War.',event('1914'),bank,'1914 chronology entry','Only year supported; no invented suspension day.');
claim('lena','events-context','Government troops fired on striking workers at the Lena goldfields, provoking investigations and wider protest.',event('1912-04-17'),lena,'Opening dated paragraph and investigation section','Source pairs4April Julian with17April Gregorian; casualties remain disputed and omitted.',{qualifications:['Casualty totals differ between sources; no exact number asserted.']});
claim('bank-portfolio','economy',73,observation('1913'),bank,'1913 chronology entry','Bank lending to banks constituted73percent of the State Bank’s total lending; this is a bank portfolio statistic, not national credit or GDP.',{metric:'state-bank-lending-to-banks-share',unit:'percent',scope:{id:'russian-state-bank-portfolio',description:'Imperial State Bank total lending portfolio in1913; institutional scope differs from imperial population or polygon coverage.',relationship:'different'},qualifications:['Retrospective central-bank institutional series; portfolio denominator is the State Bank’s own total lending.','Explicit scope difference requires historical review; not extrapolated to total Russian lending.']});
claim('pavlov','important-figures','Ivan Pavlov — physiologist and conditioned-reflex researcher',interval('1908','1914'),pavlov,'Biographical sections on institute, physiology chair, Academy and reflex research','Dated institutional career and research establish selected-period relevance, not modern nationality.',{figure:{personId:'ivan-pavlov',name:'Ivan Pavlov',categories:['scientist','physiologist'],lifespan:{from:'1849',until:'1936'},relationship:'Director of physiology at the Institute of Experimental Medicine and Russian Academy of Sciences academician during the imperial period.',activity:'Led physiological and conditioned-reflex research while holding the physiology chair,1895–1925.',contribution:'Experimental study of digestion and conditioned reflexes;1904Nobel award is earlier context, not a1908–1914event.'},qualifications:['Lifespan year precision avoids conflicting Julian/Gregorian birth-day conventions.','Later Soviet career is not projected into the empire.']});
const gaps={
 'historical-flag':['No vetted dated imperial civil/state/royal design plus licensed asset established; do not use a generic modern tricolour.'],
 'population-statistics':['1897census is outside selected1908–1914period; no reviewed later estimate with matching imperial territorial scope acquired.'],
 'area-statistics':['No dated imperial area observation with territorial inclusions vetted.'],
 density:['No compatible dated population and area pair; no derivation.'],
 relationships:['Imperial titles in Article59 do not independently establish each territory’s legal status or an atlas successor relationship.']
};
for(const [category,g]of Object.entries(gaps))investigate(category,'unresolved','Category considered against constitutional text, bank history and preserved evidence; no unsupported inference accepted.',category==='relationships'?[laws]:category==='population-statistics'||category==='area-statistics'||category==='density'?[bank]:[],g);
for(const category of ['identity','political-institutional','leadership','capital','currency','economy','events-context','important-figures'])investigate(category,['leadership','currency','economy'].includes(category)?'partial':'supported','Bounded source-supported records supplied; partial coverage remains explicit.',[...new Set(pkg.claims.filter(c=>c.category===category).flatMap(c=>c.sourceIds))],category==='leadership'?['Chairmanship after1910 not filled;1911transition and subsequent cabinets remain gaps.']:category==='currency'?['1914gold suspension represented as event; exact effective-day monetary interval remains unresolved.']:category==='economy'?['Bank-scope observation held for comparability review; no GDP estimate.']:[]);
investigate('overview','partial','Existing production narrative provides core constitutional context; no redundant synthesis counted as a new fact.',[laws],['Wartime social/economic overview not expanded beyond the sourced events.']);
notes.push({sourceId:laws,bodyReviewed:true,locator:'Complete translated primary text Articles4–101',note:'New grouped religious/civil/representation details distinct from reused core powers.'},{sourceId:capital,bodyReviewed:true,locator:'Complete substantive article lines44–49',note:'1732–1918capital and1914rename;1991material contextual only and omitted.'},{sourceId:rename,bodyReviewed:true,locator:'Complete article by direct HTTP, opening dual-calendar decree through1924continuity',note:'Gregorian31August1914; capital city unchanged, name only.'},{sourceId:bank,bodyReviewed:true,locator:'Complete imperial chronology1860–1917',note:'Gold-standard1897/1914continuity;1913portfolio73percent explicitly bank-specific.'},{sourceId:stolypin,bodyReviewed:true,locator:'Named office heading, explicit tenure and contemporary document list',note:'1906–1911office interval, safely clipped to1908–1910; no inferred appointment from archive coverage alone.'},{sourceId:lena,bodyReviewed:true,locator:'Complete dated narrative and uncertainty section',note:'Gregorian17April1912; casualty precision deliberately withheld.'},{sourceId:pavlov,bodyReviewed:true,locator:'Full Nobel biography via direct HTTP after web403',note:'Institutional tenure supports1908–1914; relevant research programme grouped as one person record.'});
x.save();
