// Candidate-only southern-cone source packet. Never writes production.
import fs from 'node:fs';
import crypto from 'node:crypto';
import {readContext} from '../../../scripts/research-common.mjs';
const root='research/regional-09/southern',ctx=readContext(),store=JSON.parse(fs.readFileSync('data/comprehensive-dossiers.json'));
const known=[...ctx.registry.sources,...store.packages.flatMap(p=>p.sources||[])],sources=[],claims=[];
function source(id,title,institution,url,kind='official-institutional'){
 const s=known.find(x=>x.url===url)||{id,title,institution,url,accessed:'2026-10-03',kind,usage:'Individual factual paraphrases, dated observations and short locators; no wholesale copyrighted source redistribution.'};
 if(!sources.some(x=>x.id===s.id))sources.push(s);return s.id;
}
const ar=source('r09-south-bcra-currency','Emisiones anteriores de billetes y monedas','Banco Central de la República Argentina','https://www.bcra.gob.ar/emisiones-anteriores-de-billetes-y-monedas/');
const arh=source('r09-south-bcra-history','Historia y patrimonio arquitectónico','Banco Central de la República Argentina','https://www.bcra.gob.ar/historia-y-patrimonio-arquitectonico/');
const py=source('r09-south-bcp-guarani','El Guaraní, Signo Monetario del Paraguay','Banco Central del Paraguay','https://www.bcp.gov.py/en/guarani-signo-monetario-paraguay');
const uy=source('r09-south-uruguay-vab','Estimación del Valor Agregado Bruto de la Administración Pública en Uruguay (1870–2017), DT20/2021','Pablo Marmissolle and Henry Willebald; Instituto de Economía, Universidad de la República','https://www.colibri.udelar.edu.uy/jspui/bitstream/20.500.12008/30205/1/dt-20-21-1.pdf','academic-economic-history');
const rodo=source('r09-south-rodo','Casa de la Cultura y Museo José E. Rodó','Intendencia de Canelones','https://www.imcanelones.gub.uy/disfrutamos/lugares/casa-cultura-museo-jose-rodo','institutional-biography');
const figari=source('r09-south-figari','Pedro Figari: Cronología resumida','Museo Figari, Ministerio de Educación y Cultura, Uruguay','https://museofigari.gub.uy/innovaportal/v/7858/20/mecweb/biografia?3colid=6227&breadid=null','institutional-biography');
const roa=source('r09-south-roa','Homenaje a Augusto Roa Bastos','Instituto Cervantes','https://cultura.cervantes.es/espanya/es/HomenajeaAugustoRoaBastos/173175','institutional-biography');
const roaf=source('r09-south-roa-chronology','Augusto Roa Bastos: Perfil biográfico 1917–2005','Fundación Augusto Roa Bastos','https://fundacionroabastos.org/augusto-roa-bastos/','institutional-biography');
const agn=source('r09-south-agn-1815','Bicentenario de la Asamblea del Año XIII y de la Independencia','Archivo General de la Nación, Argentina','https://www.argentina.gob.ar/sites/default/files/bicentenario_de_la_asamblea_xiii_e_independencia.pdf','national-archive');
const un=source('r09-south-un-charter','Charter of the United Nations: participant ratifications','United Nations Treaty Collection','https://treaties.un.org/pages/showDetails.aspx?clang=_en&objid=080000028017ebb8','treaty-depositary');
const int=(from,until)=>({kind:'interval',from,until,certainty:'exact'}),event=date=>({kind:'event',date,certainty:'exact'});
function add(entityId,category,value,temporal,sourceIds,locator,extra={}){
 const id='r09-south-'+crypto.createHash('sha256').update(JSON.stringify([entityId,category,value,temporal])).digest('hex').slice(0,20),precision=temporal.date?.length===10?'day':'year';
 claims.push({id,entityId,category,value,temporal,scope:{id:entityId+'-southern-'+category,description:'Named historical institutional, monetary or cultural entity scope; no geometry-inferred sovereignty or modern nationality fallback.',relationship:'same'},sourceIds,evidence:sourceIds.map(sourceId=>({sourceId,locator,note:'Original source body read. Bounds restrict evidence to the represented research framework and do not assert new historical transition dates.',precision,temporal,interpretation:'direct'})),status:'supported',risks:[],qualifications:['Research-window bounds are scope restrictions, not asserted historical transition dates.'],origin:{kind:'new-research',reference:sourceIds[0]},...extra});
}
add('argentina-pre-1930-federal-framework','currency','Peso moneda nacional',int('1899','1929'),[ar,arh],'BCRA previous-issues table: peso moneda nacional from5November1881; replacement peso ley from1January1970. History identifies1881–1969currency.');
for(const [id,f,u]of [['paraguay-1940-executive-framework','1944','1947'],['paraguay-stroessner-early-framework','1955','1960']])add(id,'currency','Guaraní',int(f,u),[py],'BCP anniversary chronology: DecreeLaw655of5October1943establishedguaraní; banknotes circulated from1944; subsequent1963issue retainsunit.');
for(const [id,f,u]of [['uruguay-late-1830-framework','1890','1916'],['uruguay-dual-executive-framework','1920','1932'],['uruguay-postwar-presidential-framework','1944','1951'],['uruguay-collegiate-government-framework','1953','1960']])add(id,'currency','Peso',int(f,u),[uy],'DT20/2021, printedpage10/PDFpage12, footnote4: Uruguaycurrency1862–1975wasPeso, replacedat1000:1byNuevoPeso. No currentpeso backwardprojection.');
add('argentina-pre-1930-federal-framework','events-context','Gold convertibility was suspended.',event('1914'),[arh],'Monetary system before BCRA: gold-standard link suspended1914–1927; eventualabandonmentDecember1929.');
add('rio-de-la-plata-1815-provisional-framework','events-context','The Provisional Statute directed the Junta de Observación to convene a new congress.',event('1815-05-05'),[agn],'AGNpublication, printed/PDFpage14: ProvisionalStatute5May1815; Junta deObservación convenedCongress whileÁlvarezThomas wasDirectorSupremo.',{qualifications:['Event belongs to the represented provisional framework beginning5May1815; does not back-project1816independence or imply uniform provincial consent.']});
add('paraguay-1940-executive-framework','events-context','Paraguay deposited its ratification of the United Nations Charter.',event('1945-10-12'),[un],'UNTCCharterparticipantrowParaguay: ratificationdeposit12October1945; commonCharterentryintoforce24October1945.',{qualifications:['Deposit date differs from Charter entry into force; not represented as membership beginning12October.']});
add('uruguay-postwar-presidential-framework','events-context','Uruguay deposited its ratification of the United Nations Charter.',event('1945-12-18'),[un],'UNTCCharterparticipantrowUruguay: ratificationdeposit18December1945. CommonCharterentryintoforcecolumnis24October1945, notUruguaydepositdate.',{qualifications:['Actual national ratification deposit date retained; common Charter date is not substituted.']});
function person(id,entityId,name,from,until,life,categories,relationship,activity,contribution,src,locator){add(entityId,'important-figures',name,int(from,until),src,locator,{figure:{personId:id,name,categories,lifespan:{from:life[0],until:life[1]},relationship,activity,contribution},qualifications:['Relationship is explicitly documented historical cultural activity; not inferred from birthplace, modern nationality or officeholding.']});}
person('jose-enrique-rodo','uruguay-late-1830-framework','José Enrique Rodó','1900','1900',['1871','1917'],['literary','philosophical'],'Uruguayan literary and intellectual institutions document his contribution to the generation of1900.','Ariel appeared in1900.','Influential modernist essayist and Latin-American idealist thinker.',[rodo],'Officialmunicipalmuseum biography: lifespan1871–1917, generation900significance, Ariel1900.');
person('jose-enrique-rodo','uruguay-late-1830-framework','José Enrique Rodó','1914','1914',['1871','1917'],['literary','philosophical'],'Uruguayan literary and intellectual institutions document his contemporary essay writing.','El mirador de Próspero, a collection of essays on Hispanic writers, appeared in1914.','Influential modernist essayist and Latin-American idealist thinker.',[rodo],'Officialmunicipalmuseum biography: ElmiradordePróspero1914; lifespan1871–1917andgeneration900significance.');
person('pedro-figari','uruguay-late-1830-framework','Pedro Figari','1913','1914',['1861-06-29','1938-07-24'],['philosophical','artistic','reformist'],'Active in Montevideo institutions before taking the arts-and-trades school directorship in1915.','Author of Arte, Estética, Ideal(1912), while continuing his Uruguayan professional and cultural work.','Philosophical aesthetics, artistic education and social reform.',[figari],'Museumbiography:1905–1915BancoRepública legaloffice;1912aesthetic/philosophicaltreatise;1915educationalreform.',);
person('pedro-figari','uruguay-dual-executive-framework','Pedro Figari','1920','1920',['1861-06-29','1938-07-24'],['artistic','philosophical'],'Living and painting in Montevideo before his1921move toBuenosAires.','Following his1918withdrawal from public activity, he dedicated himself to painting.','Distinctive painter and aesthetic thinker, with documented later international recognition.',[figari],'Museumbiography:1918MontevideoHotelOrientalandexclusivepainting;1921moveBuenosAires;1925Parisrecognition.');
person('augusto-roa-bastos','paraguay-stroessner-early-framework','Augusto Roa Bastos','1960','1960',['1917','2005'],['literary','cultural'],'Exiled writer associated with Paraguayan history and Guaraní cultural experience, living in Buenos Aires rather than serving the government.','Published Hijo de hombre and El naranjal ardiente in1960.','Major Paraguayan narrative and cultural contribution documented by Instituto Cervantes;1959novelcompetitionawardpreceded1960publication.',[roa,roaf],'Cervanteshomage:lifespan,Paraguay/Guaraníassociation,foreignresidence,Hijodehombre1960;foundationchronology:1947exile,1959award,1960publications.');
for(const [id,y,v,benchmark]of [['uruguay-late-1830-framework',1900,5410878,false],['uruguay-late-1830-framework',1914,16378647,false],['uruguay-dual-executive-framework',1920,21391253,true],['uruguay-postwar-presidential-framework',1945,89610880,false]])add(id,'economy',v,{kind:'observation',observationDate:String(y),certainty:'exact'},[uy],'DT20/2021, Cuadro1, printedpages9–10/PDFpages11–12; numeric'+y+'row. Methodsection3.2explainsnationalbudgetbenchmarksandadjustedhistoricalseries.',{metric:'public-administration-gross-value-added-estimate',unit:'historical Uruguayan pesos at current prices',scope:{id:id+'-uruguay-public-administration',description:'Uruguayan public administration sector as defined in the historical economic study, not total national GDP or a population/polygon scope.',relationship:'same'},qualifications:['Retrospective academic estimate published2021; actual series year'+y+'. Original-period currency, not modern pesos, constant-price values, national GDP or contemporary census.',benchmark?'1920is a documented national-budget benchmark in the source.':'Source-supported adjusted/interpolated series between historical budget benchmarks; not an atlas-created interpolation.','Scope and method follow the named study; no density or per-capita inference.']});
for(const c of claims){const walk=o=>{for(const [k,v]of Object.entries(o)){if(typeof v==='string'&&!['id','entityId','sourceId','personId','reference','from','until','observationDate','date'].includes(k))o[k]=v.replace(/([A-Za-zÀ-ÿ])(\d{4})/g,'$1 $2').replace(/(\d{4})([A-Za-zÀ-ÿ])/g,'$1 $2');else if(v&&typeof v==='object')walk(v);}};walk(c);}
const cohort={id:'regional09-southern-monies-culture-institutions',worker:'regional-southern-research-worker',sources,claims};fs.writeFileSync(root+'/cohort.json',JSON.stringify(cohort,null,2)+'\n');console.log(JSON.stringify({claims:claims.length,sources:sources.length,entities:new Set(claims.map(x=>x.entityId)).size}));
