import fs from 'node:fs';
const out='research/five-category-01/ottoman';fs.mkdirSync(out,{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));const a=read('research/flagship-01/audit.json').rankedWorkload.find(g=>g.id==='ottoman-turkey');const old=[...read('data/historical-sources.json').sources,...read('data/comprehensive-dossiers.json').packages.flatMap(p=>p.sources||[])];
const kurus={id:'fc01-ottoman-kurus',url:'https://islamansiklopedisi.org.tr/kurus',title:'KURUŞ — Ottoman currency history',institution:'TDV İslâm Araştırmaları Merkezi; Şevket Pamuk',accessed:'2026-10-03',kind:'academic-institutional',usage:'Source body read, historical monetary-unit paragraphs and1800/1914silver-content table. Factual paraphrases only; no full source text or images redistributed.'};
const selim={id:'fc01-ottoman-selim-iii',url:'https://islamansiklopedisi.org.tr/selim-iii',title:'SELİM III — Sultan1789–1807',institution:'TDV İslâm Araştırmaları Merkezi; Kemal Beydilli',accessed:'2026-10-03',kind:'academic-institutional',usage:'Read biography body and dated office heading; source-dated7April1789accession,1807deposition. Titular office fact only,not conversion to important figure.'};
const cap=old.find(s=>s.id==='c01-ottoman-istanbul-capital');const sources=[kurus,selim,cap];const I=(from,until)=>({kind:'interval',from,until,certainty:'exact'});const claims=[];
function add(key,entityId,category,value,from,until,source,evFrom,evUntil,locator,qual,extra={}){claims.push({id:'fc01-ottoman-'+key,entityId,category,value,temporal:I(from,until),scope:{id:entityId+'-'+key,description:'Named central Ottoman institution/office/monetary issuance only; no claim of uniform administration or circulation over all imperial territories.',relationship:'same'},sourceIds:[source.id],evidence:[{sourceId:source.id,locator,note:qual,precision:'year',temporal:I(evFrom,evUntil),interpretation:'contextual'}],status:'supported',risks:[],qualifications:[qual,'Sourceyearprecision retained; researched calendar subsets do not date accession, capital move, monetary reform or entity creation. Existing accepted facts preserved.'],origin:{kind:'new-research',reference:'Five-category01 Ottoman source-family bounded review',sourceIdentifier:key},...extra});}
const early=[['1800','ottoman-1800-sultanate-core'],['1815','ottoman-1815-sultanate-core']];
for(const[year,entity]of early){add(year+'-capital',entity,'capital','Istanbul (Constantinople)',year,year,cap,'1453','1922','Turkish-period administration paragraph and Republican transition: web484,1488','Ottoman central capital from conquest until imperial dissolution; republican Ankara transition is not projected backward.',{role:'Imperial capital'});add(year+'-kurus',entity,'currency','Ottoman kuruş',year,year,kurus,year==='1800'?'1788':'1808',year==='1800'?'1808':'1839','Kuruş silver-content table1800row; paragraphs1760s–1808and1808–1839,web103–121','Historical silver kuruş monetary unit; repeated debasements altered intrinsic content and value. No fixed exchange rate, modern lira or exclusive circulation assertion.',{metric:'monetary-unit'});}
add('1800-selim','ottoman-1800-sultanate-core','leadership','Selim III','1800','1800',selim,'1789','1807','Office heading1789–1807; biography7April1789accession andMay1807deposition,web71,129,170','Sultan’s office,not a claim of uniform effective control;1800strictly inside verified tenure.',{role:'Sultan'});
add('1815-mahmud','ottoman-1815-sultanate-core','leadership','Mahmud II','1815','1815',kurus,'1808','1839','KURUŞ paragraph identifies reforming sultanMahmudIIand his1808–1839reign;web117–121','Explicitly named sultan and dated reign in monetary history;1815strictly inside that tenure. Monetary policy discussion does not create an important-figure claim.',{role:'Sultan'});
add('adjourned-lira-kurus','ottoman-abdulhamid-adjourned-framework','currency','Ottoman gold lira and silver kuruş','1880','1900',kurus,'1844','1914','1844reform and standards through1914;1879change followed by continuedsilverpayments,web121–128','Gold lira and silver kuruş denominations coexisted.1879change toward gold did not eliminate silverpayments; no constant metalparity, exclusive circulation or allterritory claim.',{metric:'monetary-unit'});
add('1914-capital','ottoman-second-constitutional-core','capital','Istanbul (Constantinople)','1914','1914',cap,'1453','1922','Turkish-period administrative history and Republican capital transition,web484,1488','Ottoman imperial central capital in1914; no claim that lateroccupied1920city represented uniform imperial administration.',{role:'Imperial capital'});
add('1914-lira-kurus','ottoman-second-constitutional-core','currency','Ottoman gold lira and silver kuruş','1914','1914',kurus,'1844','1914','Standards maintained through1914; late monetary system goldlira plus silverkuruş,web125–128','Named imperial monetary units in1914. Not a claim of stable wartime purchasing power, goldconvertibility or uniform circulation in every territory.',{metric:'monetary-unit'});
const cats=['historical-flag','population-statistics','capital','leadership','currency'];const held=[];const assessment=a.occurrences.map(o=>({id:o.id,mapId:o.mapId,snapshotYear:o.snapshotYear,entityId:o.entityId,categories:Object.fromEntries(cats.map(category=>{const prior=o.categories[category],matched=claims.filter(c=>c.entityId===o.entityId&&Number(c.temporal.from)<=o.snapshotYear&&Number(c.temporal.until)>=o.snapshotYear);const ids=matched.filter(c=>c.category===category).map(c=>c.id);const action=ids.length?'bounded-source-proposal':prior?.records?.length?'preserve-accepted-evidence':'hold';if(action==='hold'||['held','partial'].includes(prior?.status))held.push({id:o.id,category,statusBefore:prior?.status,reason:category==='population-statistics'?'No date-matching territorially compatible total verified; do not use modernTurkey to describe Ottoman empire.':category==='historical-flag'?'Exactdateddesign,entity association andlicensedasset not verified; no modernflag fallback.':!o.entityId?'Within-year constitutional/occupation/coup transitions and existing mappinggaps preserved; no whole-year regime or leader imposed.':'Dated office/unit/seat evidence not sufficient for missing orpartialcalendarcell; retain acceptedrecords and leave residualgap.'});return[category,{statusBefore:prior?.status||'missing',acceptedRecords:prior?.records?.length||0,action,claimIds:ids}];}))}));
function readable(obj){if(Array.isArray(obj))return obj.map(readable);if(obj&&typeof obj==='object')return Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,typeof v==='string'&&['value','note','locator','reason','title'].includes(k)?v.replace(/([A-Za-z])(\d)/g,'$1 $2').replace(/(\d)([A-Za-z])/g,'$1 $2'):readable(v)]));return obj;}
const write=(name,obj)=>fs.writeFileSync(out+'/'+name,JSON.stringify(readable(obj),null,2)+'\n');write('cohort.json',{id:'five-category01-ottoman',worker:'five-category01-ottoman',claims,sources});write('registry-patch.json',{mode:'proposal-only',entities:[],mappings:[],note:'Preserve all existing dated frameworks and mappings; no whole-year transition identity invented.'});write('source-review.json',{status:'root-independent-review-required',sources:[{sourceId:kurus.id,url:kurus.url,bodyReviewed:true,locator:'Silver-content table and monetary-history paragraphs,web103–128',supports:claims.filter(c=>c.sourceIds.includes(kurus.id)).map(c=>c.id),notes:'1800table;MahmudIIreign1808–1839;kuruş throughdebasements;1844lira/kurus reform,standardsto1914;silverpaymentsafter1879. Avoid further fiscal/goldstandard claims.'},{sourceId:selim.id,url:selim.url,bodyReviewed:true,locator:'Office heading1789–1807; accession7April1789;May1807deposition,web71,129,170',supports:claims.filter(c=>c.sourceIds.includes(selim.id)).map(c=>c.id)},{sourceId:cap.id,url:cap.url,bodyReviewed:true,reusedExactSourceObject:true,locator:'Turkish-period administrative paragraph484;Republicantransition1488',supports:claims.filter(c=>c.sourceIds.includes(cap.id)).map(c=>c.id),notes:'Source explicitly identifiescapitalstatus afterconquest untilimperialdissolution andlossofcapitalrolewithRepublic; new1800/1815/1914researchclippings do not overwriteaccepted1880/1900capitalfact.'}]});write('held.json',{cells:held,difficultCells:'1878,1920and1960whole-year transitions retained. Exactframework day/month bounds do not promote source-year precision. No stats/flags invented.'});write('assessment.json',{group:a.id,occurrenceCount:assessment.length,categoryCount:5,cellsAssessed:assessment.length*5,newClaims:claims.length,assessment});console.log({claims:claims.length,sources:sources.length,cells:assessment.length*5});
