import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const base='research/bulk-01/worker-officeholders';
const m=JSON.parse(fs.readFileSync(`${base}/officeholder-manifest.json`));
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const entities=JSON.parse(fs.readFileSync('data/historical-entities.json')).entities;
const ids=new Set(entities.map(e=>e.id));
for(const s of m.sources)assert.equal(sha(fs.readFileSync(s.cachePath)),s.sha256);
for(const r of m.rows){assert(r.name.length>3);assert(/^(18|19)\d{2}-\d{2}-\d{2}$/.test(r.from));assert(r.from<=r.until);if(r.from===r.until)assert(r.entityIdsSuggested.length===0);assert(r.originalRow.includes(r.name)||r.sourceId==='bulk01-victoria-premiers');assert(m.sources.some(s=>s.id===r.sourceId));for(const id of r.entityIdsSuggested)assert(ids.has(id));}
const canada=m.rows.filter(r=>r.sourceId==='c01-canada-ministry-tenures');
assert.equal(canada.length,18);assert.equal(canada[5].name,'Sir Mackenzie Bowell');assert.equal(canada[0].from,'1867-07-01');assert.equal(canada[17].until,'1963-04-22');
const japan=m.rows.filter(r=>r.sourceId==='japan-cabinets');assert.equal(japan.length,59);assert.equal(japan.at(-1).from,'1885-12-22');assert.equal(japan[0].sourceOrdinal,'59th');
const counts=Object.fromEntries(m.sources.map(s=>[s.id,m.rows.filter(r=>r.sourceId===s.id).length]));assert.deepEqual(counts,{'japan-cabinets':59,'c01-canada-ministry-tenures':18,'bulk01-victoria-premiers':60,'bulk01-queensland-premiers':36,'bulk01-nsw-premiers':50});
const review={schemaVersion:1,reviewer:'worker-officeholders original-body research review',reviewedAt:'2026-10-02',purpose:'Source-bound extraction review. This is neither production acceptance nor an independent historical adjudication.',parserPath:`${base}/extract.mjs`,parserSha256:sha(fs.readFileSync(`${base}/extract.mjs`)),checks:['All immutable downloaded source body hashes match manifest.','All suggested entity ids are actual production entities.','All source dates parse as valid day-precision dates and retain real tenure endpoints.','Canada 18 ministries and Japan 59 cabinets through 1960 extracted; split strong-tag Bowell surname regression checked.','Victoria full premier table uses Assumed office / Left office columns, with six-column guard.','Queensland list source uses DD/MM/YYYY; full given names retained.','NSW card boundaries tested against first Donaldson card so current-office name cannot bleed into history.'],sourceSemantics:{'japan-cabinets':'Each his-block is a numbered cabinet term. Adjacent same-person terms are often a continuous Prime Minister tenure; do not count cabinet reappointments as distinct new persons or claim improvements if existing tenure covers them. Official English spelling HATOYMA is present in body; preserve original label as evidence, reconcile display spelling separately.','c01-canada-ministry-tenures':'Intro explicitly defines ministry by prime minister tenure, oath to resignation/death/dismissal. Date columns are DD-MM-YYYY. Historical transfer gaps shown by body are preserved; do not interpolate to successors.','bulk01-victoria-premiers':'Table explicitly says Premier leader with Legislative Assembly support. Assumed office and Left office full dates are explicit. Roman reappointment suffix stripped from person but retained in originalRow. Pre-1902 blank party cells not filled.','bulk01-queensland-premiers':'Government official named-office list of former Premiers. Source first Herbert term begins 1859-12-10 whereas parliamentary list found during discovery begins 1860-05-22: hold that pre-snapshot row; do not reconcile automatically.','bulk01-nsw-premiers':'Government served-as-premier cards give real full dates; end dates sometimes precede next start by one day and sometimes equal next start. Preserve endpoints; automatic exclusive/inclusive normalization unsafe.'},rows:m.rows.map(r=>({sourceId:r.sourceId,locator:r.locator,evidenceSha256:sha(r.originalRow),suggestedMappingCount:r.entityIdsSuggested.length,proposedDisposition:!r.entityIdsSuggested.length?'held-outside-curated-scope':r.sourceId==='bulk01-nsw-premiers'?'held-endpoint-semantics':r.entityIdsSuggested.length>1?'historical-review-transition':'source-row-extracted',cautions:r.evidenceCautions}))};
fs.writeFileSync(`${base}/source-bound-review.json`,JSON.stringify(review,null,2)+'\n');console.log(JSON.stringify({passed:true,rows:m.rows.length,sourceBodies:m.sources.length,rowsWithSuggestedMappings:m.rows.filter(r=>r.entityIdsSuggested.length).length,counts}));
